### ISSUE TITLE
ORA-00911: Invalid character on 'From'

### ISSUE THREAD

**Issue by MingoDynasty** [flyway/flyway#1080]
[ERROR] SQL State  : 22019
[ERROR] Error Code : 911
[ERROR] Message    : ORA-00911: invalid character

Taken from the Flyway First Steps documentation:

File V1__foo.sql:
create table PERSON (
    ID int not null,
    NAME varchar(100) not null
);

File V2__bar.sql:
insert into PERSON (ID, NAME) values (1, 'From');
insert into PERSON (ID, NAME) values (2, 'Mr. Foo');
insert into PERSON (ID, NAME) values (3, 'Ms. Bar');

Flyway fails to execute the first line of V2__bar.sql, because of the 'From' word. Changing it to anything else works. Tried Flyway 3.2.1 and 3.2; both have the issue. I tried Flyway 3.1 and did not encounter this issue.

**Comment by SCHERPEREEL** [comment]
When the label starts with "Then" we have the same error
insert into PERSON (ID, NAME) values (1, 'Thendkdkdkdkdk");

**Comment by aetelani** [comment]
Different capitalization doesn't seem to help either. Had to downgrade flyway to 3.1

**Comment by lzuyderhoff** [comment]
Same issue for me with a label ending with the character 'N'.

After debugging flyway:migrate (Version 3.2), I think the problem comes from the method :  OracleSqlStatementBuilder.cleanToken(String token);

Looking at the code I think the bug can occur if one the following conditions applies on the label : 
starts with : USING or THEN or FROM
AND/OR
ends with : N or IF of ELSIF or SELECT or IMMEDIATE or RETURN or IS

I hope it can helps.

**Comment by axelfontaine** [comment]
Thank you reporting and investigating and thank you @ysobj for the fix!

Merged.
