### ISSUE TITLE
Allow configFile paramter in maven plugin to be load file from classpath

### ISSUE THREAD

**Issue by wemu** [flyway/flyway#1091]
Using the maven plugin I would like to be able to pass a classpath file to the "configFile" parameter as well. Similar to the "locations" parameter which supports "filesystem" and "classpath".

The goal is to pack a jar file containing all sql scripts and db-settings for different target environments together and later be able to retrieve that archive and populate different databases with the same scripts (but different connection settings).

**Comment by influence160** [comment]
I have the same problem,
i have tow projects A and B. A is a dependency of B
i want to use flyway maven plugin in the process-test-resources phase to create a h2 database for the unit tests
in project A i have a file h2.properties who is the flyway configFile and sql files all located in src/test/ressources

i use maven-jar-plugin with the goal test-jar to package all the test resources in a jar and i want to use this ressources in project B by using a similar flyway maven plugin to the project A
but in project B i cant configure configFile to point in the h2.properties because it is in the class path

**Comment by MikielAgutu** [comment]
Closing for lack of interest. There is a workaround - before running a Flyway goal, use the [`dependency:unpack`](https://maven.apache.org/plugins/maven-dependency-plugin/unpack-mojo.html) goal to unpack the config file, which you can then read from the disk.
