### ISSUE TITLE
OsgiClassPathLocationScanner takes wrong classpath

### ISSUE THREAD

**Issue by GianniGiglio** [flyway/flyway#1098]
When flyway is used in osgi the classpathLocationScanner uses the methode FrameworkUtil.getBundle(getClass()) which gives the bundle from flyway core instead of the bundle using flyway.  This results in flyway looking for it's resources on the wrong classpath.

**Comment by chrsoo** [comment]
Hi, I got tired of trying to make Flyway classpath scanning work in an OSGI environment and decided that using the Extender Pattern was the way to go instead. So I created #1102 and [started a fork](https://github.com/chrsoo/flyway/tree/osgi-extender) to see if this was feasible. Feel free to contribute -any feedback is welcome!

**Comment by GianniGiglio** [comment]
Isn't it an option to simply use the classloader passed to Flyway?  Doing so when using a bundleactivator we could pass the classloader of the activator class. I've seen that you can set the classloader on flyway but the classpathLocationScanner isn't using it.

**Comment by chrsoo** [comment]
You may very well be right in which case the easiest fix to get Flyway working for OSGI would be to simply ensure that `ClassPathLocationScanner` uses the classloader set on the `Flyaway` instance.  I will look into this tonight.

To set the `Flyway` classloader to that of our bundle one option is to use an Activator as you suggest, you could also do the same in a custom Blueprint bean.

However, I kind of like the idea of using the OSGI Extender Pattern with Flyway which means that you only would have to add a default configuration in a standard location (`META-INF/flyway/name.properties` in my fork) and an environment specific configuration in a `ManagedServiceFactory` configuration (`org.flywaydb.core-name.cfg`) and then Flyway would automatically pick up your migrations. As soon as I get the pesky Maven integration tests working I will submit a pull request to include this functionality.

Yet another option is to use a Blueprint extension (custom XML configuration); I have not yet looked to closely into this.

**Comment by chrsoo** [comment]
Just checked the code and the snippet you are referring to is found in the class `OsgiClassPathLocationScanner`. The assumption here is that when you specify the `bundle:` protocol scheme your migrations will be found in a framgent of the Flyway fragment host which is why `FrameworkUtil.getBundle(getClass())` should work - the classloader of the fragment host has access to all resources in the fragment bundle that contains the migrations.

Thus I believe that the right classloader is taken given that the OSGI implementation is based on the migrations being provided in a fragment bundle of the Flyway fragment host. I think this issue can be closed.

Cheers,

Chris
PS I am not sure why the classloader set on Flyway is not used but I would not be surprised to find that there are classloading issues when classes are loaded using `Class.forName(..)` in `ClassUtils`. Also if I remember correctly there are issues scanning/reading resources if not using the bundle.

In any case, fragments are a mess to deal with, at least in my limited experience and I would rather get away from this solution.

**Comment by GianniGiglio** [comment]
Hi,

Thanks for your answer. Indeed I've also got it working using fragments. I didn't test it further on large scale but still think it doesn't feel ideal. Anyway you are right and it can work with fragments. 

Thanks for your response,

Gianni
