### ISSUE TITLE
Execution of migration scipts and update/insert of meta data table(schema version) not in one transaction

### ISSUE THREAD

**Issue by AloisMuehlederDynatrace** [flyway/flyway#1236]
###### What version of Flyway are you using?
3.2.1

###### What database are you using (type & version)?
db2, oracle, derby, mssqlserver, postgresql

We also use the dbcp connection pool.

if there migration was interrupted beetween the commit of the migration script (e.g: create table x..)and the update from the meta data table(schema_version) the next migration will try to execute the migration script again, failed and throws a "already exists exception". 

Is it possible to run the migrations and the update/insert of meta data in one transaction?

Regards,
Alois

**Comment by axelfontaine** [comment]
The short answer is: no.

This is by design as Flyway uses two connections to allow recording failed migrations in the metadata table for databases that don't support DDL transactions (ex.: Oracle).

There is however no reason why it shouldn't be possible for databases that do support DDL transactions to modify Flyway to only use a single connection and a single transaction.

**Comment by AloisMuehlederDynatrace** [comment]
ok, thanks for the quick answer. 
In future we will implement our migration scripts that we can handle a rerun(e.g. check if table already exists...).

Regards,
Alois
