### ISSUE TITLE
Flyway 4.0 automatically updates the schema_version table and breaks backwards compatibility

### ISSUE THREAD

**Issue by cheister** [flyway/flyway#1248]
###### What version of Flyway are you using?
We're currently using 3.2.1 and want to update to 4.0

###### What did you do?
We attempted use Flyway 4.0 to check if the migrations were up-to-date.

###### What did you expect to see?
That it would report whether the tables were up-to-date and not modify the database.

###### What did you see instead?
Just by running the check for pending migrations the schema_version table was automatically updated and the version_rank column was removed which breaks rolling back to 3.2.1.

We use Flyway to check that migrations are run before starting our applications.  The actual migrations are run in an offline process. The automatic update of the schema_version table during the pending migrations check means we cannot rollback to Flyway 3.2.1 in any simple way after running Flyway 4.0.  It is surprising that a read-only check of pending migrations updates the schema_version table and breaks backwards compatibility with the previous version and that there is no rollback option.  The easiest fix was to restore the schema_version table from a backed up version so Flyway 3.2.1 was usable again.

I had proposed a PR https://github.com/flyway/flyway/pull/1247 to allow a user to update to Flyway 4.0 and not have it automatically update the schema_version table.  This would allow to keep the pending migration check in our application and update the schema_version table the next time we run migrations.

I could also see an update for Flyway 3.2.x that automatically rolls the schema_version table back to the 3.2.x version after a Flyway 4.0 update but that seems more awkward.

I'm fine with the backward incompatible change to the schema_version table, I just don't want it to run automatically anytime Flyway is used.  Can the update only be run automatically when Flyway is doing a write operation such as running a migration?  Or can we add the advanced option to allow the automatic update to be disabled?

**Comment by axelfontaine** [comment]
Works as designed and as documented in the release notes https://flywaydb.org/documentation/releaseNotes

**Comment by cheister** [comment]
Why is the schema_version table not being held to the same standard as all Flyway migrated tables.  If calling `flyway.info().pending()` on a database actually started running Flyway migrations then you would agree that there was a bug in the code.  Why should the migrations for on internal Flyway table be different?

If the schema_version table was versioned with Flyway migrations, then you could roll forward and backwards between Flyway versions and the table would only be modified when you migrated it.  Why should the schema_version table be migrated automatically?  Especially when it making a breaking change between versions.

**Comment by mrbelowski** [comment]
This behaviour is really surprising and disappointing.

Having recently inherited a (production) system which uses Flyway, I ran 'flyway info' from the command line on the production DB, which (without asking) "upgraded" the schema_version table to version 4. A subsequent production deployment failed because it attempted to run 'flyway migrate' Flyway version 3.

I don't see where this behaviour is documented in the release notes linked above, and it's certainly not documented in the commands documentation.

I really think this behaviour is 'broken' and should be changed, but if you're going to claim it "works as intended" then the info command documentation needs to make it *very* clear that it will make breaking changes to the schema_version table

**Comment by axelfontaine** [comment]
@mrbelowski The first line of the release notes for Flyway 4.0 literally says

> This version comes with a **new metadata table format**. Migration is transparent and automatic on first run.

Apart from adding a blink tag, how much clearer can we make it?

**Comment by mrbelowski** [comment]
"first run" implies (to me at least) the first flyway:migrate run (where changes are expected), not the first flyway:info run. Something that retrieves "info" wouldn't normally be expected to make changes, especially changes that break backwards compatibility

**Comment by Cyc1one** [comment]
"This version comes with a new metadata table format. Migration is transparent and automatic on first run."

It could be made much more clear that this means even on running -info, which it's pretty obvious should make no changes.
If -info MUST make changes for some reason, then it should only be after warning the user and getting confirmation.  But it would be better if it simply did what it should and reported the status, including the fact that the metadata table will be updated.

**Comment by axelfontaine** [comment]
I updated the release notes last week to this:

> This version comes with a **new metadata table format**. Migration is transparent and automatic on first run of any Flyway command. This new format is not compatible with older Flyway versions.

Please feel free to submit any wording improvements as pull requests against flyway/flywaydb.org

No changes to the code will be made.

**Comment by Cyc1one** [comment]
I think it's unlikely that all flyway users will read the release notes when downloading a client and intending to run the info goal, nor do I think they should have to, as by contract info should be something that makes no changes.
I'll be happy to advise my enterprise customers to reconsider using flyway if this is how you treat legitimate concerns.

**Comment by segfaultcoredump** [comment]
This bit me in the ass the other day. I expected the metadata table to be upgraded upon the application of a migration, not simply checking to see if a migration was pending.  The note that it is updated on _ANY_ command tells me that there is no blessed way of checking to see if an update is required and therefore this is no graceful way of dealing with the issue. 

Here is some suggested wording:

"This version comes with a new metadata table format. Migration is transparent and automatic on first run of any Flyway command. This new format is not compatible with older Flyway versions. **If you allow flyway v4.0 or newer to connect to the database, the flyway library will automatically upgrade the metadata table and prevent you from ever using a previous version, even if there are no migrations pending.**  

As a crude hack/workaround, initially connect to the database with a read-only account and surround a call to info() with a try/catch for a org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException exception.  If an exception is thrown, then you know that you have a pending medatadata update to run.  Handle the exception via whatever procedure is appropriate for your system. 
"

In my case, I have an app that stores data in a local H2 database. If the user tries to use the newer 1.5 version of the app to open a file created with v1.0 of the app, I save a copy of the original file to "pre_v1.5" and then perform an upgrade on the database. This allows the user to use version 1.0 of my app if they have an issue with the new 1.5 version. The flyway library "modify before we tell you that we need to modify anything" behavior breaks this check, and in the process it prevents v1.0 from ever reading the older file since flyway modified the original file before the newer version of my app had a chance to react to the fact that it needed an update.  As a workaround I now do a double open: one with a read only account to see if flyway pukes, and then again to perform the actual migration.
