### ISSUE TITLE
Multiple Users for multiple Schemas

### ISSUE THREAD

**Issue by computerlyrik** [flyway/flyway#1308]
###### What version of Flyway are you using?

4.0.1
###### What database are you using (type & version)?

Oracle DB 11g
###### What operating system are you using?

*nix / Windows
###### What did you do?

We have a multi schema configuration, as mentioned here: https://flywaydb.org/documentation/faq#multiple-schemas
They all use the same lifecycle.

Configuration like:
flyway.schemas=schema1,schema2,schema3
###### Question

How do i configure a user per schema? 
A single user with any-rights across all schemas is not allowed at the moment.

Is it possible to define different users for different schemas?

Remember: Sometimes a Migration will create some DB-Objjects in schema1 which are used then in schema2. And a Migration in schema3 (with user3) should result in a entry in the flyway-metadata-table in schema1 (with user1).

Thanks for any help.

**Comment by axelfontaine** [comment]
Thanks for the feature request. This is a really niche requirement and I see the chances of a solution to this making it in the main distribution as virtually zero as there are 3 clear workarounds available:

1. Create a special user just for Flyway that has all the necessary rights for those 3 schemas
2. Give the user of schema 1 all the rights for those 3 schemas
3. Run Flyway 3 times: once for each schema with the matching user

**Comment by S2-** [comment]
> 1. Create a special user just for Flyway that has all the necessary rights for those 3 schemas

At least in oracle, packages and other executable objects when executed, are executed with the rights of the user that compiled them. so if I create a user `flybase` and give him grants to create objects in schema `schema1` and `schema2`, those packages, procedures and functions when executed by the `app` user will have all the rights of the `flybase` user. This can esaly become a scurity risk and cause strange behaviour, because usually stored procedures in `schema1` get compiled with user `schema1`.

> 2. Give the user of schema 1 all the rights for those 3 schemas

Same as 1.

> 3. Run Flyway 3 times: once for each schema with the matching user

This is really the only real workaround, but with serous drawbacks: the lifecycle can not be managed in an atomic manner anymore: the flybase instances must be executed in the right order (probably always different), in case tables created in one schema need tables from an other schema. So if I need to create `schema1.table1` that references `schema2.table2` that references `schema1.table2`, I need to be super extra careful about what I write in the migration scripts and the order in which the `flybase` instances are executed.

**Comment by sunjain** [comment]
FYI. We have similar requirement. We tested with using "alter session set current_schema = my_schema:" and it seems to work...Basically you can go with option 1(create a special user with perms). And in your script you can first session to whichever user you want to run as...This alter session command worked with flyway (as part of the script it is running).

**Comment by S2-** [comment]
@sunjain now all your packages, functions and procedures are executed with the user that compiled them. that means the user that has rights of `alter schema` on all schemas. this could be ok in your case, but i think in most cases this is a security risk, because a bug in one of the procedures could potentially `alter` stuff in all schemas the flybase user has access to.

**Comment by sunjain** [comment]
That's a valid concern.

**Comment by gintsgints** [comment]
+1 for this feature.

**Comment by pesse** [comment]
For it's not possible in Oracle to have CREATE/DROP Privileges for specific Schemas but only the very powerful CREATE ANY PROCEDURE etc. we couldn't go with any of the given workarounds (the different Schemas are in the same lifecycle)
I came up with another workaround where I have one common Version-Number, one migration repository but several separate schemas. All of them have own config-files and the config files have a migrationSuffix _<SCHEMANAME>.sql.
With that convention I could write a little batch-script (development is on Windows) to encapsulate the flyway command:

```
@echo off
IF [%~1] == [] (
    SET /p FLYWAY_COMMAND="Enter Flyway command: "
) ELSE (
    SET FLYWAY_COMMAND=%~1
)

IF [%~2] == [] (
    SET FLYWAY_SCHEMA=SCHEMA1,SCHEMA2,SCHEMA3
) ELSE (
    SET FLYWAY_SCHEMA=%~2
)

Setlocal EnableDelayedExpansion
for %%a in ("%FLYWAY_SCHEMA:,=" "%") do (
    rem echo ../flyway-4.2.0/flyway -configFile=conf/flyway-%%~a.conf %FLYWAY_COMMAND%
    call ../flyway-4.2.0/flyway -configFile=conf/flyway-%%~a.conf %FLYWAY_COMMAND%
    IF !ERRORLEVEL! NEQ 0 (
        ECHO ABORTING
        EXIT /B !ERRORLEVEL!
    )
)
```
With that I'm able to just call 

`.\flyway_all migrate`

or 

`.\flyway_all info`

SCHEMA1-Migration files (named *_SCHEMA1.sql) will only be applied to SCHEMA1 and so on.
Of course there is the drawback that eventually someone could add a migration-script V1_smth_SCHEMA1.sql and someone else V1_smthelse_SCHEMA2.sql and flyway wouldn't mind, but you can easily prevent this by source checks in your git flow.
It was actually the best way to live with the limits of both, flyway and Oracle :)

**Comment by jcamilli** [comment]
Hi @axelfontaine, I know this issue is closed and I see the reason for closure that you provided, but would be great if you would revisit. I have currently forked Flyway and I am diving into the code trying to figure out how to support multiple users for each schema. This is a show-stopper for us.

I am on a team of about 30 people who are actively contributing to a single Oracle database that contains about 10 schemas. Each of these schemas has a separate user and corporate policy does not allow Flyway to run with a system level user that has access to all schemas. If I implement your suggested approach of "Run Flyway X times" (one for each schema) then there is no 1-place where all scripts are tracked. Each schema will have its own flyway_schema_history table. Correct? Another problem with this approach is that it limits the ordering of the versioned sql files. For example, what if schema A.t1 depends on B.t1 which first requires A.t2 be created. 

I have seen your recommendation in the FAQ and as noted above, this does not work for us. The below FAQ states, "Make sure the user of the datasource has the necessary grants for all schemas" ... https://flywaydb.org/documentation/faq.html#multiple-schemas

My first attempt to resolve the above was to attempt to set new credentials in a BEFORE_EACH_MIGRATE callback event: 
```
public void handle(Event event, Context context) {
   flyway.setDataSource(dbProps.getConnString(), userName, password);
}
```

Unfortunately the above code did not work. Setting the flyway datasource does not seem to affect the current migration process.

My second attempt to fix (in addition to the above handle() code) was to fork Flyway and modify Database.java so that it returns a ```getConnection(JdbcUtils.openConnection(configuration.getDataSource()));``` instead of returning the existing connection. The problem is the database transaction operations occur before and after this code is called and those operations use connection objects that are saved outside of this scope. Anyway... i shall keep digging.

Any advice would be very appreciated.

Thank you
Jared

**Comment by gintsgints** [comment]
@axelfontaine We, at our company, consider donation/payment to push forward this feature. Would you be ok to implement it?

**Comment by gintsgints** [comment]
Final solution would be like having multiple username/passwords given in config but all them applied in order like it would be one schema.

As example I have schemas:

- books (login: books/books_234)
- cd (login cd/cd_234)

And booth schemas have reaptable migrations for two packages which depends on each other:
books/
R__100_1_Header_ofCDpackage
R__200_1_Body_ofCDpackage
cd/
R__100_2_Header_ofBooksPackage
R__200_2_Body_ofBooksPackage

and they got applied in order-
- login to books schema, execute header
- login to cd schema, execute header
- login to books schema, execute body
- login to cd schema, execute body

**Comment by jcamilli** [comment]
Hi @gintsgints, I ended up creating a wrapper around Flyway in order to accomplish the desired behavior. The wrapper takes as input a directory whose contents are files with a naming convention such as V1_USER_OBJ.sql

The code moves these files into separate folders and loops through the folders while calling flyway for each. For each iteration of the loop, the folders are added to the Flyway classpath and Flyway is re-executed with this new classpath included.

**Comment by gintsgints** [comment]
> Hi @gintsgints, I ended up creating a wrapper around Flyway in order to accomplish the desired behavior. The wrapper takes as input a directory whose contents are files with a naming convention such as V1_USER_OBJ.sql
> 
> The code moves these files into separate folders and loops through the folders while calling flyway for each. For each iteration of the loop, the folders are added to the Flyway classpath and Flyway is re-executed with this new classpath included.

Huh.. we ended up with some solution. But this is not good because it takes much more time for all migrations to be executed. And also it requires quite sofisticated workarounds for keeping up with correct execution order.

**Comment by jcamilli** [comment]
@gintsgints, yes it does slow things down a bit. At first it was very slow, but I made a code change related to caching the history table (i think, it's been a while now) and that really sped things up.

**Comment by jcamilli** [comment]
@gintsgints We are also not recreating the Flyway instance for each iteration.

**Comment by sakke** [comment]
We would also need this feature in our current setup. Any ideas if Liquibase can handle this issue?

**Comment by gintsgints** [comment]
@sakke No as far as I know, Liquibase cannot it too. I saw some trying make some customisations for that. But no real results seen.

**Comment by vitas** [comment]
We also need it, who can share some workaround? We were close to buy Pro version but without feature we cannot, even if some coding possible we cannot fork pro version.

**Comment by jvizueta** [comment]
hi, very interesting thread you guys have here. What do you think about this approach from dbmaintain?

https://dbmaintain.github.io/docs/

![image](https://user-images.githubusercontent.com/1859246/83926721-467c6080-a750-11ea-8dec-e4122e4a4752.png)

**Comment by gintsgints** [comment]
I see some movement there - https://flywaydb.org/blog/multipleschemas?utm_source=flywaynewsletter&utm_medium=email&utm_campaign=databasedevops&utm_content=JuliaFWJan21&mkt_tok=eyJpIjoiTVdGaU4yWXdZVEZsTW1ReSIsInQiOiI4SnBTeXAwK1hcL1NSRXB0dkF2Y3dLSzJ5dUNycXNhZERud1wvc3hGSk1CaHc5c3lQajE2eTJKOUdMa3V3dUVOdXhvXC8ycWpCM3hjQjVxcTdoOEFpT045UDFMMEQwNjFFWEtkYmU1UzNjcFl4Z3Y0c2Z5allGZDRCckQ1YkJHN29yMyJ9

**Comment by ArnoHollanders** [comment]
> @gintsgints We are also not recreating the Flyway instance for each iteration.

Would you mind to share what exactly you changed?

**Comment by JasonLuo-Redgate** [comment]
Hi @computerlyrik , in the latest V10 release of Flyway, different `environment` can be configured for through toml configuration in Flyway. 
So I think this requirement can be achieved through creating different environments for each different schema, and each environment can have its own user setting.
