### ISSUE TITLE
Repair does not fix "Migration Description mismatch" error

### ISSUE THREAD

**Issue by nathansgreen** [flyway/flyway#1351]
I want to avoid manually updating `schema_version`. It seems to me this is the purpose of the `repair` command, but it doesn't fix everything.
###### What version of Flyway are you using?

3.2.1
###### What database are you using (type & version)?

PostgreSQL 9.4
###### What operating system are you using?

OSX
###### What did you do?

I renamed a migration file and ran the migration process. When that failed, I ran the repair command. The error message looked like this:

```
FlywayException: Validate failed. Migration Description mismatch for migration 2.22.0
-> Applied to database : Updates to some stuff
-> Resolved locally    : Add constraints to mandatory client info
    at org.flywaydb.core.Flyway.doValidate(Flyway.java:1108)
    at org.flywaydb.core.Flyway.access$300(Flyway.java:62)
    at org.flywaydb.core.Flyway$1.execute(Flyway.java:1012)
    at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
    at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
    at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
```
###### What did you expect to see?

I expected the repair command to fix the metadata table.
###### What did you see instead?

The repair command did nothing because all the checksums matched.

**Comment by nathansgreen** [comment]
It's also worth mentioning that `validate` fails in the same way as `migrate`, and I would expect `validate` to succeed if `repair` is successful.

**Comment by axelfontaine** [comment]
Good point. That makes sense.

**Comment by compwron** [comment]
I am also having this problem. 

OSX 10.11.6
compile 'org.postgresql:postgresql:9.4.1209'
compile "org.flywaydb:flyway-core:4.0.3"

running gradle flywayRepair does not prevent me from seeing the error 
"Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Validate failed: Migration checksum mismatch for migration"

**Comment by nathansgreen** [comment]
Everyone will have this problem until this issue is resolved.

**Comment by tejasshah0107** [comment]
This is not an issue. It is the way Flyway behaves.This error is because of the fact that there were certain SQL scripts earlier which, probably, now either aren't there or are missing. are now you have some new files which have been added. So it would interpret these new files added as the previous ones if you have given them the same version number. 
Solution to this would be using the command **_flyway:info_** This will give you an idea of migrations that have already taken place. Check if the version that you specified in the new files have already been given earlier. If yes use different one. The whole concept of flyway lies on the fact that it works on versioning and one is bound to makes mistakes while allocating version numbers to the newly added scripts if there are multiple developers working on it without they being in sync. 
And last and most important point is about the "repair" command. It is and should be only used for failed migrations and NOT in these scenarios where there is a migration mismatch.
