### ISSUE TITLE
Incremental and Repeatable scripts without specifying Prefix.

### ISSUE THREAD

**Issue by darkio14** [flyway/flyway#1388]
###### What version of Flyway are you using?

Flyway 4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Javap API, Gradle Plugin.
###### What database are you using (type & version)?

Oracle 10.2
###### What operating system are you using?

Windows 7
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

When I settings this properties:

`properties.setProperty("flyway.sqlMigrationPrefix","");`

The Incremental Scripts executed perfectly.

But in the case of repeatables:

`properties.setProperty("flyway.repeatableSqlMigrationPrefix","");`

flyway try to run as incremental.

The deployment command was: `flyway.migrate ()`
###### What did you expect to see?

Run the scripts correctly by following this structure:

```
scripts/incremental/01_products_and_orders.sql
                              02_users.sql

```

```
scripts/repeatable/proc_purge_old_orders.sql
                            proc_refresh_materialized_views.sql

```
###### What did you see instead?

`org.flywaydb.core.api.FlywayException: Invalid version containing non-numeric characters. Only 0..9 and . are allowed. Invalid version`

**Comment by aquimi** [comment]
I also need to work with those same directory structures, I hope that improvement rise.
Greetings.

**Comment by axelfontaine** [comment]
This is a really niche requirement which can be addressed today by writing your own MigrationResolvers. Also a simple rename of the files should allow you to work with the existing standard resolvers.

**Comment by jvizueta** [comment]
I think flyway is a very powerful tool and pretty much up to date, but having a file structure that makes the whole team rename repeatable files adding an R or any pattern like that is not friendly to a bigger codebase.

Axel, it would be great if you consider this change. Think about it, if this were a "niche requirement", it wouldn't be the default file structure for another database migration like dbmaintain, don't you think? You can see what I'm talking about here: http://www.dbmaintain.org/tutorial.html It makes the codebase look cleaner and more organized. I would use dbmaintain instead if it wasn't as outdated as it is right now.

"A simple rename of the files" is not so simple, neither friendly, as most teams use SQL IDEs and these save files in different (many times pre-stablished) formats. 

Making this change would only expand where the pattern for repeatable files needs to be, taking in consideration the whole file path instead of just looking at the filename.

Writing MigrationResolvers for something really basic, doesn't seem so intuitive or out-of-the-box.

What are your thoughts on this?

**Comment by aquimi** [comment]
We are developing this change, a parameter was created to decide whether sqlMigrationPrefix and repeatableSqlMigrationPrefix MUST be treated as prefix file or folder prefix.

@axelfontaine  Let's help with an opinion of yours to proceed with this change and make a pull-request?

**Comment by axelfontaine** [comment]
This can currently be achieved almost fully by setting the `sqlMigrationPrefix`to `0` and `repeatableSqlMigrationPrefix` to a blank string. The only requirement is your versioned migration files msut start with a leading 0.

**Comment by mbklaene** [comment]
Sorry. To comment on an old, and closed, thread but wanted to confirm the last comment here is accurate. I tried to implement a repeatable migration solution that does not require a prefix and it did not work. The separator cannot be blank. 

Was hoping 'mytables.sql' would be recognized as a repeatable solution by marking the prefix as blank, and the separator as blank. But the separator field cannot be blank.
