### ISSUE TITLE
Flyway migration ordering

### ISSUE THREAD

**Issue by tfsoares** [flyway/flyway#1403]
##### Environment
I'm using Ubuntu 16.04, PostgreSQL 9.4 and the Java client.

##### Problem
Run repeatable migrations that depend on another repeatable migration. 

##### Explanation
This brings a problem because the implicit sorting is alphabetical and I needed to order them differently.

Imagine I have this 2 migrations:
- `db/migrations/R__vw_a.sql`
- `db/migrations/R__vw_b.sql`

The current sorting would lead to `vw_a` to be ran before `vw_b`. The problem in this is that `vw_a` might perform a query on `vw_b`. So migrating `vw_a` before `vw_b` will generate an error and the migration will never succeed.

So a Custom Migration Resolver might be used to retrieve a list of Resolved Migrations with the correct sorting.
But at Flyway current state, after using the Custom Resolver, it will reorder migrations again.

##### Possible Solution
One solution might be add a property to set wether to use or to skip default sorting. This property would be used by an if condition on Composite Resolver.
Then, on MigrationInfoServiceImpl, change some collections from Unordered to Ordered types and tweak MigrationInfoImpl's compareTo method to return 0 when comparing Repeatable Migrations.

This way it would be possible to keep the ordering retrieved from Resolvers.

**Comment by axelfontaine** [comment]
In your case the simplest this is probably to combine both sql files into 1 or look at versioned migrations instead for those objects.

I currently don't feel that adding an additional flag here would carry its additional conceptual weight.

**Comment by albertocsm** [comment]
I don't agree with you @axelfontaine.
Combining those scripts in just one file doesn't make sense to me. Separate objects should have their own life cycle and evolve separately.
Besides,  the object scripted in 'a.sql' can be used in multiple other views ('b.sql', 'c.sql', ect) and scripting those dependencies all over the place is tremendously difficult to maintain. 

On the other hand, versioning stateless objects with 'versioned migrations', IMHO, its not a good way to keep track of the changes. We followed that road in @Bikeemotion and you can get lost pretty quickly after a few iterations.  
SVC can handle stateless object's repeatable scripts a lot better and help me maintain whats left of my sanity!

**Comment by alkamo** [comment]
The proposed solution only works if the two views were created as part of separate releases. If I were trying to solve this problem, I think I'd resort to adding a sequence number as a prefix in the file name, in order to ensure the correct ordering if two related views are added as part of the same release
```
db/migrations/R__002_vw_a.sql
db/migrations/R__001_vw_b.sql
```

As a side note, I get around this issues in Oracle by using the Force keyword when creating views. This allows views to be created even if they're invalid at the time of creation. I then have a post-release script that checks for invalid objects. Since Postgres doesn't have equivalent functionality, that's not terribly useful at this time, but it might be a helpful feature request to send to the Postgres team.

**Comment by albertocsm** [comment]
"The proposed solution only works if the two views were created as part of
separate releases"

Not sure I understand what you are saying.
Depending on the custom migration resolver impl, *all* the dependencies can
be caught and re-run in the appropriate order.

The custom migration resolver we have implemented finds all the stored
procedures and views referred in the body of a new/updated migration and
from there it determines and *sorts* everything that needs to run.

I would be glad to provide that custom migration resolver impl if that
helps anyone.

It seems to me though that the subject or impl details of some custom
migration resolver falls out of the scope of the proposed change.
The goal of the changes being proposed is just making flyway a lot less
opinionated about custom migration resolvers and allow those custom impl
actually do something useful.
Without the changes being proposed, flyway overrides any sorting made by
any custom migration resolver.

That's a limitation I don't find any good reason to be exist. Especially
taking in consideration that no breaking changes are being made to the API
(just a new setter!), no change in the default behavior is being made, and
the internal changes are so small, contained and simple.

I would be more then happy discussing a better approach or changing
anything on the PR that could help on getting this merged. Unfortunately
the door on this subject seems to be completely shut right from the bat.

Having said all this, I have no problem with @axelfontaine feel of keeping
this out because of the 'conceptual weight' added here!
Im pretty happy with flyway even if I have to run a custom build.

Either way, thks for the input @alkamo.

**Comment by axelfontaine** [comment]
Thanks for the suggestions. For now I feel the workaround outlined by @alkamo is sufficient for the core Flyway distribution.
