### ISSUE TITLE
HBase support

### ISSUE THREAD

**Issue by mkrcah** [flyway/flyway#1459]
Any plans to add support for [Apache HBase](http://hbase.apache.org/)?

**Comment by alextercete** [comment]
Closing due to lack of interest.

**Comment by oswaldo** [comment]
Just wanted to share some opinion about this one. I feel it is not a lack of interest situation but a market one, in the sense it is already covered by something else and people tend to just take what they already know instead of searching for something new (or taking the time to let their fellow opensource developers know about that need if taking the shortcut takes less time).

What I mean is, someone that is already using flyway in some project or research and finds that it doesn't support HBase will just take some workaround. For instance, knowing PDI (Pentaho Data Integration), one can just take an HBase Output component to interact with it, having some relational "flyway managed database" as reference (also useful for small scale tests if one has the need for that).

In any case, congratulations to the team for the great project that is flyway :)
