### ISSUE TITLE
Flyway does not clean sequences in Oracle

### ISSUE THREAD

**Issue by collingridge** [flyway/flyway#1580]
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
command line

###### What database are you using (type & version)?
Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production

###### What operating system are you using?
Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Having set up schemas in conf/flyway.conf
I run migrate which creates sequences in another schema.
If I then run clean and migrate again, I get an error from Oracle saying the sequence already exists.
All other objects in managed schemas including the one with the sequences seem to have been dropped successfully.

###### What did you expect to see?
Sequences should get dropped from all managed schemas

###### What did you see instead?
sequences were not dropped

**Comment by axelfontaine** [comment]
We just made a number of major changes in this area for the upcoming Flyway 4.2.0 release. Could you give it a try again with the latest sources from GitHub?

**Comment by vosolovskiy** [comment]
Flyway seeks objects for cleaning in ALL_OBJECTS data dictionary view.

According to the source code of ALL_OBJECTS:
```sql
...
  or
    ( o.type# = 6 /* sequence */
      and
      exists (select null from v$enabledprivs
              where priv_number = -109 /* SELECT ANY SEQUENCE */)
    )
...
```
the issue reported only happens when the deploy user doesn't have `SELECT ANY SEQUENCE` system privilege. In this case other schemas' sequences remain unseen for the Clean procedure.

I bet your deploy user has already been granted `CREATE ANY SEQUENCE` and `DROP ANY SEQUENCE` privileges to work with different schemas. In order to fix the issue, grant the deploy user this extra privilege (as it seems less harmful than those others) .

**Comment by vosolovskiy** [comment]
When I finish work on #1550 (goal 1), there will appear another workaround: instead of granting a user `SELECT ANY SEQUENCE` privilege, you can grant it `SELECT` on DBA_OBJECTS.

**Comment by collingridge** [comment]
@vosolovskiy It seems that `SELECT ANY SEQUENCE` was my problem. Thanks very much for your help.
