### ISSUE TITLE
Incorrect Flyway version in published Jar

### ISSUE THREAD

**Issue by mion00** [flyway/flyway#1635]
###### What version of Flyway are you using?

Flyway 4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What did you do?
Using the [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin) to check for available updates for dependencies, I noticed that the last version found by the plugin is 3.2.1.

###### What did you expect to see?
The latest version is 4.2.0

###### What did you see instead?
This is the output of the gradle plugin:
```
The following dependencies exceed the version found at the milestone revision level:
 - org.flywaydb:flyway-core [4.0.3 <- 3.2.1]
```
Using Artifactory to browse the Maven artifacts, I noticed in the maven-metadata file of flyway-core reports 3.2.1 incorrectly as the latest version.
![selection_024](https://cloud.githubusercontent.com/assets/4510647/26008383/d7741b3e-3744-11e7-8430-247d242b7073.png)

Maybe there is something wrong in your deployment process that doesn't update the metadata file in the published jar?

**Comment by axelfontaine** [comment]
Official versions are released on Maven Central. See http://search.maven.org/#search|ga|1|flyway-core

Check your artifactory configuration.

**Comment by magneticflux-** [comment]
@mion00 I ran into this issue as well and decided to track down the problem once and for all.

This isn't an issue with an invalid Artifactory configuration; it's because Redgate originally published `flyway-core` on Bintray's JCenter repository separately and never removed the old versions when they stopped publishing there: https://bintray.com/redgate/Flyway/org.flywaydb%3Aflyway-core. This causes Bintray's JCenter repository to use Redgate's Bintray repositories' files when present, which haven't been updated since 2015. The only reason the artifact resolution for versions past 2015 doesn't fail is because JCenter falls back to Maven Central on a per-artifact level, so while the old metadata is resolved, the new artifact is resolved as well.

Here are some of the metadata links I inspected:
- Maven Central (Up-to-date): https://repo.maven.apache.org/maven2/org/flywaydb/flyway-core/maven-metadata.xml
- Maven Central Alt (Up-to-date): https://repo1.maven.org/maven2/org/flywaydb/flyway-core/maven-metadata.xml
- Google Maven Central Mirror (Up-to-date): https://maven-central.storage-download.googleapis.com/maven2/org/flywaydb/flyway-core/maven-metadata.xml
- JCenter (Out-of-date): https://jcenter.bintray.com/org/flywaydb/flyway-core/maven-metadata.xml

@axelfontaine That Bintray object is owned by the user "redgate" which has recent (last seen 6/4/2020) activity, so I assume the account is in use and owned by Redgate. I think the easiest solution for this would be for Redgate to delete the unused "Flyway" repository located here: https://bintray.com/redgate/Flyway. This would not cause any resolution failures because any new requests for those files would end up falling back to the correct artifacts on Maven Central (which I assume have the same hashes, if not that's a huge problem that's above my pay grade). This link should take you directly to the Edit page where you can delete the repository, assuming you're logged in to the "redgate" account: https://bintray.com/redgate/Flyway/edit. Again, this should be non-destructive since you publish to Maven Central since 2015.

**Comment by juliahayward** [comment]
The unwanted repo is now deleted and https://jcenter.bintray.com/org/flywaydb/flyway-core/maven-metadata.xml is correctly displaying versions up to 7.0.2 now.
