### ISSUE TITLE
mysql migrations are always assumed transactional

### ISSUE THREAD

**Issue by OlegYch** [flyway/flyway#1725]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
api

###### What database are you using (type & version)?
mysql 5

###### What did you do?
executing a script containing 'alter table' and 'update' statements

###### What did you expect to see?
exception by default (with mixed = false)

###### What did you see instead?
migration succeeds

as an aside, would it be possible to enforce a failure if migration contains multiple non-transactional statements?
ie i expect a failure whenever a migration cannot be executed in single transaction, current mixed transactions implementation even for pgsql allows multiple non-transactional statements per migration
if this behavior is implemented, what might be the strategy to allow already existing migrations with multiple transactions ignore that setting?

**Comment by axelfontaine** [comment]
Please share a small test case that demonstrates this behavior.

**Comment by OlegYch** [comment]
please see https://github.com/OlegYch/flyway-1725/

**Comment by axelfontaine** [comment]
This works as expected. `mixed=false` is meant for databases where certain statements absolutely cannot be run within a transaction. The MySQL statements you used have no such restriction. Works as designed.

**Comment by OlegYch** [comment]
in mysql ddl statements cannot participate in existing transaction
it would be nice to be able to enforce that there is exactly one transaction per migration so that you don't accidentally have partially applied migrations

**Comment by JFCote** [comment]
Hey @axelfontaine 

I have a question related to this thread because I also feel there is a bug.

I use mysql and have this migration:

```
INSERT INTO persons
(ID,
 LastName,
 FirstName,
 Age)
VALUES
(4,
 'TEST4',
 'TEST4',
 67); #Transactional!

CREATE TABLE Persons2 (
	 ID int NOT NULL,
	 LastName varchar(255) NOT NULL,
	 FirstName varchar(255),
	 Age int,
	 PRIMARY KEY (ID)
); #Non-transactional!
	
DROP TABLE Persons2; #Non-transactional!
```
I run `migrate` with the option set to `mixed=false` even if it is also the default value just to be sure.

As you can see if you try it, no exception is issued even if we clearly mix statement that are transactional (insert) and statement that are not (CREATE and DROP).

I did additional testing by creating a migration containing only "INSERT" and making sure the last insert fail and the migration was rollbacked as expected.

I created another migration containing only "CREATE" or "ALTER TABLE" with something that didn't work at the end and it was not rollback as expected.

So it seems Flyway knows whether some statement are transactional or not but it doesn't apply this when enforcing the `mixed` option.

Do you have an explanation for this? Is this a bug? I read you comment above saying it is working as intended but I can't wrap my head around this based on my testing, reading mysql documentation and reading Flyway documentation.

**Comment by axelfontaine** [comment]
@JFCote The docs for mixed were indeed a little unclear. We have now updated them with more details to better reflect what this does. See https://flywaydb.org/documentation/commandline/migrate#mixed

**Comment by JFCote** [comment]
@axelfontaine Thank you very much for the clarification!
