### ISSUE TITLE
Support Multiple Migrations within a single Transaction

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#181]
_Original author: ke...@fidelma.com (April 24, 2013 05:01:42)_

When upgrading a database I would expect all un-applied migrations to be applied within the same transaction. Currently each migration runs within its own transaction.

My use-case looks something like this:
1. Version 1.0 is deployed into Production
2. Developers work on features for Version 2.0, each creating a migration script matching their new feature.
3. As development progresses, V2.x migrations, and the associated application, are put into QA.
4. Eventually we decide we've done enough, and want to release v2, and it's myriad migration scripts.
5. When we run the deployment against v1 in production we expect all the v2.x migrations to run, and if there is a problem with any of them, then the database is rolled back, and we revert the application to v1 while we figure out what went wrong. 

We really don't want _some_ of the v2 scripts to be committed to the production database.

We're using Postgres, so DDL rolls back nicely.

I'm happy to do the change, if nobody else is interested, but it seems like an &quot;obvious&quot; feature to me. None of your competition seem to offer it either. Am I missing something?

_Original issue: http://code.google.com/p/flyway/issues/detail?id=484_

**Comment by alexeev** [comment]
+1
I would appreciate this feature!

**Comment by ice-pro** [comment]
+1

**Comment by orange-buffalo** [comment]
+1 
We really missing this feature !

**Comment by atomixxx** [comment]
+1

**Comment by janeklb** [comment]
+1

**Comment by janeklb** [comment]
@kerryland do you still have your implementation kicking around for this?

**Comment by kerryland** [comment]
On 1 Dec 2015 04:51, "Janek Lasocki-Biczysko" <notifications@github.com>
wrote:

> @kerryland <https://github.com/kerryland> do you still have your
> implementation kicking around for this?
>
I've had a look. It's a hacky mess. In summary I've tried to move the
commits around:

*TransactionTemplate.execute* should not commit or rollback
   simply :

    T result = transactionCallback.doInTransaction();


*Flyway.migrate:*  after dbMigrator.migrate() add
   connectionMetaDataTable.commit()
   connectionUserObjects.commit();

I also commented out the next line. Honestly not sure why:

   dbSupportUserObjects.setCurrentSchema(schemaUserObjects);


*Flyway.configure* I disabled autocommits:

     connectionMetaDataTable.setAutoCommit(false);
     connectionUserObjects.setAutoCommit(false);

Hope this helps.

**Comment by janeklb** [comment]
Thanks @kerryland - much appreicated, I'll see if I can work from here..

**Comment by gionn** [comment]
I am surprised that this feature is still missing, how do you rollback if a production deployment fails? Are you always writing backward-compatible migrations?

@axelfontaine if you can give us some guidance I can try to pick up the task

**Comment by fabioformosa** [comment]
+1
We got this problem, not only over multiple migrations, but over a single migration also (from V00 to V01) obtained by running multiple scripts with a progressive sequence number.
Any update?

**Comment by janeklb** [comment]
@fabioformosa ive tried to follow @kerryland 's advice but haven't made much progress, probably due to my poor understanding of JDBC. Happy to push what I have to a branch but I don't know if it would be of any help..

I expect that @axelfontaine won't be picking this up on his own because of Flyway's business model (funded feature requests), and rightly so. So if we want to see this happen, someone here is going to have to pick up the tab.

**Comment by hmvs** [comment]
Must have feature. Used to it in our own written dbchangemanager for sql server. Just integrated flyway instead of it (because of moving to pgsql) and found that it's not capable to do all migrations in one transaction  :(

**Comment by vovcacik** [comment]
This would make my continuous deployment virtually atomic.

**Comment by patricia-finra** [comment]
Stumbled on this discussion today.

From DB perspective, not sure how this could happen. Currently each migration is wrapped in one explicit transaction of BEGIN/COMMIT(assuming nothing goes wrong). 

To accomplish this, the explicit transaction wrapping for each migration script needs to be taken out, instead, it needs to be done on the group of migration scripts - since I don't think you can have one explicit transaction within another one. I guess a flag can be added to signal if each migration script should be wrapped in one transaction.

**Comment by vovcacik** [comment]
@patricia-finra I don't see problem with that. Flyway is already managing transactions for us. Right now it starts and commits transaction for each script individually and this feature request is basically matter of changing transaction scope from individual scripts to batch of scripts. No need to mess with savepoints.

**Comment by patricia-finra** [comment]
@vovcacik Yes, but to do that they have to take out wrapping the transaction for each migration. Currently that seems the default. Now they have to say: ok now it is batch of scripts, so don't wrap each migration in transaction, only wrap it for the batch. That's why I said they might need a flag to know at which level to set the transaction.

**Comment by cowwoc** [comment]
I agree with @vovcacik. This doesn't seem too hard to me. Ideally, we want *all* pending migrations applied in a single transaction so that if a failure occurs the database is left in a good state.

**Comment by patricia-finra** [comment]
@cowwoc Not sure I've made myself clear. Currently lets say I have 2 migrations, one with 2 updates: update tblA; update tblB; and a 2nd migration with just 1 update: update tblC;

When flyway gets it what it does is: let's call this case1
begin;
    update tblA;
    update tblB;
commit;
begin;
    update tblC;
commit;

The transaction is added by flyway by default. lets say now those 2 migrations are for the same release, so we want to apply them in 1 transaction: lets call this case2
begin;
    /* do not issue BEGIN here */
    udpate tblA;
    /* no COMMIT here either. ditto below */
    update tblB;
    update tblC;
commit;

To get to caes2 from case1, flyway needs to not wrap each migration in an explicit transaction, which is what they are doing by default now. That's all. Not hard, but need a flag or something to know not to wrap in a transaction for each migration.

**Comment by cowwoc** [comment]
@patricia-finra I don't understand the difficulty here.

As you said, it is flyway who decides to open and close each transaction. Nothing prevents it from beginning a transaction, running all pending scripts, and committing the transaction at the end.

Flyway is in control of its own logic. Am I missing anything here?

**Comment by cowwoc** [comment]
@patricia-finra We don't need nested transactions. Flyway controls when it starts each transaction so it can run all migrations under a single top-level transaction.

**Comment by janeklb** [comment]
thanks @axelfontaine !

**Comment by kerryland** [comment]
Excellent news. Thanks very much @axelfontaine

**Comment by cowwoc** [comment]
For what it's worth: http://stackoverflow.com/a/4736346/14731

It seems the vast majority of databases support transactional DDL operations. Hopefully MySQL will add support in the future.

**Comment by bseib** [comment]
In the 4.2 code, if a migration fails, is a rollback still attempted, regardless of the type of database you are connected to? Or does it not even attempt a rollback if `supportsDdlTransactions()` returns false?

If non-DDL code fails to migrate, it would be nice if it still rolled back. That might require migration filenames to indicate if they contained DDL commands or not.

**Comment by cowwoc** [comment]
@bseib

> If non-DDL code fails to migrate, it would be nice if it still rolled back.

Why? Especially given that this feature request has a cost associated with it:

> That might require migration filenames to indicate if they contained DDL commands or not.

What is gained by rolling back in these cases?

Or alternatively, what is lost by assuming that migration files always contain DDL commands and always rolling back on failure regardless of the database type and the contents of the files?

**Comment by kerryland** [comment]
Keep it simple. Don't treat DDL and DML differently.

begin work
try {
    <whatever is inside migration script 1>
    <whatever is inside migration script 2>
    commit
} catch {
    rollback
}

I guess you could offer a property to support legacy behaviour too,
although I doubt new users would want it.

**Comment by jottveridian** [comment]
Since our flyway needs to manage Oracle plsql (ConfigBuilder) for the time being, we already need to tie our flyway sql to Oracle specific constructs.  For DML, we can hopefully just manage our own commit/rollback within a plsql block within a single flyway migration.  For Oracle DDL, I've successfully made extensive use of "create or replace" over the years, for views/functions/procedures/packages.  But for some objects it's not until Oracle 13 that we get a similar "create if not exists" for hard objects like tables.  Pre Oracle 13, our automate V1033 tries to solve the same problem with a plsql block that catches Oracle 955 table already in use, and continues on.  We used that successfully for Gap, and dev1/dev2, although I recently found out that V1033 does not work against an Oracle 11 database (which we do still claim we support Oracle 11 in our documentation).  It happens our hal_build Oracle is still 11.  So at some point we probably need to bump our support to Oracle 12, since those on 11 are really significantly behind the upgrade curve.  I'm going to move this to P5, with the idea that we'll end up with a specific pain point to bump it.
