### ISSUE TITLE
flyway command line using oracle wallet

### ISSUE THREAD

**Issue by csudeer** [flyway/flyway#1826]
###### What version of Flyway are you using?

4.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

Oracle 12c

###### What operating system are you using?

Mac IOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I am trying to run flyway through command line using oracle wallet.  The URL configured is
flyway.url=jdbc:oracle:thin:/@walletname

And username and password were not passed.

I went through this and tried the approaches referred, 
https://github.com/flyway/flyway/issues/1373

###### What did you expect to see?
Want to run flyway using command line through oracle wallet without providing database username and password in flyway configuration file

###### What did you see instead?
getting the below error. 

ERROR: 
Unable to obtain Jdbc connection from DataSource (jdbc:oracle:thin:/@walletname) for user '/@walletname': IO Error: Unknown host specified 
---------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08006
Error Code : 17002
Message    : IO Error: Unknown host specified

**Comment by axelfontaine** [comment]
Related to #1373

**Comment by MikielAgutu** [comment]
I'm wondering if Oracle Wallet support is completely broken, or if the problem reported here is an isolated case.

@vigneshkumaresan @rikcarve can you confirm that #1373 fixed your problem and that you can use Oracle Wallet?

@csudeer This issue was reported a while ago. Can you confirm this is still broken - to rule out the possibility it was an environmental issue etc.

**Comment by MikielAgutu** [comment]
@vigneshkumaresan @rikcarve @csudeer  ?

**Comment by rikcarve** [comment]
Sorry for my late response.
Basically using flyway with Oracle wallet does work since #1373. What we did is adapting the flyway shell script to add the additional system properties needed for Oracle wallet:
```shell
-Doracle.net.tns_admin=${HOME}/tnsadmin
-Doracle.net.wallet_location=${HOME}/tnsadmin/wallet
```
Since JDBC driver 18.3 you can skip this by directly providing the parameter in the connection string:
https://docs.oracle.com/en/cloud/paas/autonomous-data-warehouse-cloud/user/connect-jdbc-thin-wallet.html
```
jdbc:oracle:thin:@dbname_high?TNS_ADMIN=/Users/test/wallet_dbname
```

**Comment by MikielAgutu** [comment]
Documented here https://flywaydb.org/documentation/database/oracle#oracle-wallet
