### ISSUE TITLE
Change default for flyway.table from schema_version to flyway_schema_history

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#1848]
Also provide automatic fallback to old default with a warning to avoid breaking existing installations using the old default

**Comment by relgames** [comment]
Hi, is there a reason for the schema table rename?
The reason is not mentioned anywhere in documentation, also I could not find it on this Github project.
I don't see an easy way to change it in Java API (again, could not find it in the documentation). 

Can I just rename the table using `ALTER TABLE schema_version RENAME TO flyway_schema_history`? Maybe makes sense to mention it in the documentation as well?

**Comment by vorburger** [comment]
Just wanted to let you know that this caused us pain :smiley_cat: over in https://issues.apache.org/jira/browse/FINERACT-979, but now that we figured it's because of this, we'll hopefully be able to fix it.
