### ISSUE TITLE
Colorize output

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#1871]
To make it easy to distinguish debug, info, warning, success and error messages.

With a simple flag to disable.

**Comment by chrascher** [comment]
where is the switch to disable it ?

**Comment by andrewlmurray** [comment]
@chrascher FYI I think you tagged me by mistake.

**Comment by alextercete** [comment]
@chrascher We decided to drop the switch to disable it because we automatically disable it when there's no console attached (e.g. in a redirect).

I think you might be experiencing a bug -- would you mind opening a [new issue](https://github.com/flyway/flyway/issues/new) with a bit more detail so that we can troubleshoot the problem?

**Comment by chrascher** [comment]
i reviewed our situation, and there is no bug, cause the flyway installation was not correct, sorry ;-) 
switch might still be a good option though

**Comment by allenatdecisiv** [comment]
@alextercete  I disagree. Please re-add the option to disable this on invocation. Your colorization doesn't play nice in my Cygwin.
