### ISSUE TITLE
Flyway mysql driver does not resolve database host with CNAME records

### ISSUE THREAD

**Issue by swarupdonepudi** [flyway/flyway#1895]
###### What version of Flyway are you using?
Flyway Community Edition 5.0.5 by Boxfuse

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line using boxfuse/flyway docker containers

###### What database are you using (type & version)?
AWS Aurora MySQL 5.6.10a

###### What operating system are you using?

```
root@ef72e1a6cf81:/flyway/drivers# uname -a
Linux ef72e1a6cf81 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 GNU/Linux
```

###### What did you do?
Used flyway command to run a migration.

## Works:

```
flyway migrate -driver=com.mysql.jdbc.Driver -url=jdbc:mysql://my-aurora-cluster.cluster-sadfe2341435.us-east-1.rds.amazonaws.com/flyway -password=test-password
```

## Does not work:

```
flyway migrate -driver=com.mysql.jdbc.Driver -url=jdbc:mysql://db.text.example.com/flyway -password=test-password
```

###### What did you expect to see?

Since I added "db.text.example.com" as a CNAME record with "my-aurora-cluster.cluster-sadfe2341435.us-east-1.rds.amazonaws.com" as the value, I expect mysql jdbc drvier used by flyway to resolve the DNS and connect to the database and run the migration successfully.

I verified that the DNS is resolving:

```
$ dig db.test.example.com CNAME

;; ANSWER SECTION:
db.test.example.com.	299	IN	CNAME	my-aurora-cluster.cluster-sadfe2341435.us-east-1.rds.amazonaws.com.
```

> I modified the response to remove all the unnecessary content.

Also I verified that I can connect to the database using other mysql clients using this dns.

```
mysql -h db.test.example.com -u admin -p
````

###### What did you see instead?

"flyway migrate" command just hangs forever.

**Comment by axelfontaine** [comment]
This is an issue somewhere in your infrastructure as obviously the `my-aurora-cluster.cluster-sadfe2341435.us-east-1.rds.amazonaws.com` DNS entry was resolved successfully, so the driver is able to do that. Not a Flyway issue.

**Comment by jpact** [comment]
I have the same issue :/
@swarupdonepudi  Have you solved it somehow?

**Comment by thatderek** [comment]
lol, no @axelfontaine , if mysql can resolve the address, if `nc` can resolve it, if literally everything can resolve a cname pointing to a cname pointing to an IP address but your tool can't, that's not a problem with the infrastructure. Ran into this issue today, flyway hangs at:

`Flyway Community Edition 5.1.3 by Boxfuse

DEBUG: Java 1.8.0_171 (Oracle Corporation)
DEBUG: Linux 3.10.0-862.3.2.el7.x86_64 amd64

DEBUG: Loading config file: /flyway/conf/flyway.conf
DEBUG: Unable to load config file: /root/flyway.conf
DEBUG: Unable to load config file: /flyway/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /flyway/jars
DEBUG: flyway.password -> ************
DEBUG: flyway.url -> jdbc:mysql://db.local/redacted
DEBUG: flyway.user -> redacted
DEBUG: flyway.locations -> filesystem:/flyway/sql
DEBUG: Adding location to classpath: /flyway/drivers/derby-10.14.2.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/derbyclient-10.14.2.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/h2-1.4.197.jar
DEBUG: Adding location to classpath: /flyway/drivers/hsqldb-2.4.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /flyway/drivers/mariadb-java-client-2.2.4.jar
DEBUG: Adding location to classpath: /flyway/drivers/mssql-jdbc-6.4.0.jre7.jar
DEBUG: Adding location to classpath: /flyway/drivers/postgresql-42.2.2.jre6.jar
DEBUG: Adding location to classpath: /flyway/drivers/sqlite-jdbc-3.20.1.jar
[root@ip-10-1-5-187 sql]# echo "killed the above because it was hanging" 
killed the above because it was hanging
[root@ip-10-1-5-187 sql]# 
`

Excellent support to your community though. Way to really get after it! Seems like with that kind encouragement, you'll have lots of people spending their time to help find issues.  /s

**Comment by swarupdonepudi** [comment]
@axelfontaine can we please re-open this?

**Comment by axelfontaine** [comment]
@swarupdonepudi I am afraid there is simply nothing in Flyway that influences this. It is either an issue in the MySQL driver or somewhere else in your stack (OS, JVM, ...). I would be happy to reopen this if you can prove me wrong by debugging through the code and pinpoint where Flyway should be doing something differently.

**Comment by thatderek** [comment]
It's in the driver you're using. Giving flyway the wrong creds surfaces an a clean "bad permissions" error. Giving it the right creds to use against a cname->cname->ip set of records fails against the jdbc driver in the way I posted above.

**Comment by jeshan** [comment]
I face the same issue and I didn't get Axel's explanation. Shouldn't this just work?

`docker run --rm boxfuse/flyway -url="jdbc:mysql://rds-mysql.awsstaging.project.local/dbo" -schemas=flyway -user="..." -password="..." -cleanDisabled=true migrate`

Flyway hangs at this:

> Flyway Community Edition 5.1.3 by Boxfuse

If it's indeed an issue with the driver and flyway bundles it in the docker image, then isn't this a valid bug report?
