### ISSUE TITLE
Disable scanning on Android

### ISSUE THREAD

**Issue by fabianbergmark** [flyway/flyway#1910]
###### What version of Flyway are you using?

5.0.6

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API on Android

###### What database are you using (type & version)?

Android SQLite

###### What operating system are you using?

Android 7.0

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

```
org.flywaydb.core.Flyway flyway = new org.flywaydb.core.Flyway();
flyway.setSkipDefaultResolvers(true);
flyway.setResolvers(new BaseMigrationResolver() {
    @Override
    public Collection<ResolvedMigration> resolveMigrations() {
          return migrations;
    }
});
flyway.setDataSource(dataSource);
flyway.migrate();
```
###### What did you expect to see?

No scanning

###### What did you see instead?

org.flywaydb.core.api.FlywayException: Unable to scan for Migrations! Context not set. Within an activity you can fix this with org.flywaydb.core.api.android.ContextHolder.setContext(this);

**Comment by axelfontaine** [comment]
To disable scanning completely, also use `flyway.setSkipDefaultCallbacks(true);` as this would otherwise cause Flyway to scan for SQL callbacks.

This will however still not eliminate the exception. For that you should indeed invoke `org.flywaydb.core.api.android.ContextHolder.setContext(this);`.

When both of these actions have been taken, no more scanning will happen and no error message will be produced.

I am however not very satisfied with the current state of affairs regarding this. The configuration functionality will be revisited in Flyway 5.1. You can expect this to improve as part of that release as well.

**Comment by axelfontaine** [comment]
Postponing as no one as stepped up yet to push out a release of SQLDroid 1.1.0

**Comment by MikielAgutu** [comment]
This will be easier to workaround in the Flyway 6.0 release. You should be able to do this:

- Call `setLocations` on the configuration object passing an empty array
- Call `setJavaMigrations` on the configuration object to supply your pre-instantiated Java migrations

Because you are passing an empty array to `setLocations` Flyway will not scan for migrations. It'll just use the ones provided via `setJavaMigrations`.
