### ISSUE TITLE
Allow to fake migrations

### ISSUE THREAD

**Issue by KrzysztofMadejski** [flyway/flyway#1986]
I have a feature request. It would be great to be able to fake migrations. It means that the status/internal flyway table is updated, but statements changing actual tables are not performed.

Case: I've applied migrations by hand (by executing SQL statements). I want flyway to understand that some migration has already been applied and SQL statements for it shouldn't be run. 

Proposed execution: `flyway migrate -target=0003 -fake=true` 
- if migrations are at a lower version flyway would mark migrations up to version 3 (included) as run successfully.
- if migrations are at a higher version flyway would mark all migrations above version 3 as not run

###### Which version and edition of Flyway are you using?
Flyway Community Edition 5.0.5 by Boxfuse

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using (type & version)?
MySQL

**Comment by KrzysztofMadejski** [comment]
For reference: https://docs.djangoproject.com/en/2.0/ref/django-admin/#cmdoption-migrate-fake

**Comment by axelfontaine** [comment]
Related to #923

**Comment by walec51** [comment]
instead o calling them fake I would propose tho following API:

```
flyway skip -target=0003
```

if no flyway table is create then this should also create it

**Comment by fullyinchristswonder** [comment]
I too like this functionality, in my use case, there is a production release which has an issue with one script.  I need release engineers to be able to easily skip a script if that is the solution deemed appropriate and necessary by DBA and Dev.

I'd prefer the script be tagged in the flyway table as skipped.  I'd also prefer to use a callback mechanism to ask Flyway to skip the script.

Our implementation is using XL Deploy Python plugins.

**Comment by MikielAgutu** [comment]
We've thought about how this feature could work, and have decided an approach.

The Baseline command is a variation of the skip behavior described here. Baseline is limited as it only works on the initial deployment. It doesn't work on databases with an existing schema history table.

It could be possible to expand the baseline command to allow re-setting the baseline up to any version. This would have the effect of 'skipping' migrations.

However, we think it makes sense to deprecate the baseline command in favor of a more general Skip command.

The new Skip command shall allow you skip migrations since the last applied migration, and up to a specified version. It will work on a per-database basis, inserting a 'skipped' entry in the schema history table.

We'll do the following:

- Add a new Skip command
- Deprecate the Baseline command
  - It will have a deprecation period, wherein it will produce a warning to avoid breaking changes
  - The behavior will remain unchanged
- Update existing schema history tables to remove references to 'baseline' migrations
  - It's not decided which release will do this

**Comment by way0utwest** [comment]
I would give you two pieces of feedback here.
1. The baseline command is still needed. As I deploy to new places, or new clients, I need a way to set up an initial new database for a client. This is also valuable for intermediate environments if they don't exist, i.e., client testing. 
2. Re-baselining is important for the same reason. I have removed support for v2 and am selling v3, I need to set up a client with v3. I wouldn't necessarily want to run all v1 and v2 migrations.
3. Re: skip. There are times I would want to skip a migration for a client, such as a large index build. We could still release a patch of migrations 12, 14, 15, skipping 13 that is going to take too much time. However, I'd want to run this later, perhaps at a down period. I would also envision a case where we release 13 and hope 12, 14, 15 for now.
This could be in the VCS ,branch area, but often it's an Ops decision to reorder or release work out of order for some reason that is after code has been committed and verified in a VCS release or master branch.
