### ISSUE TITLE
Repeatable migrations that were updated in a newer version should be marked as future

### ISSUE THREAD

**Issue by agentgt** [flyway/flyway#1999]
###### Which version and edition of Flyway are you using?

4.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?

I haven't tested on the latest as 4.2.0 is the latest w/ JDK 7 compat (we can't afford enterprise).

But it appears looking at the code and documentation the behavior should be the same.
If really desired I could setup a project w/ the latest.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java and Maven

###### Which database are you using (type & version)?

Postgresql

###### Which operating system are you using?
Linux

###### What did you do?
Ran flywaydb (maven and java) on a schema with a future migrations already applied w/ the default of ignoreFutureMigrations = true

###### What did you expect to see?
While I expected the application not to fail fast given `ignoreFutureMigrations` doc I didn't expect the **old** repeatable migrations to be applied. 

###### What did you see instead?
See above.

I didn't even know about `ignoreFutureMigrations` allowing repeatable migrations to run being  the default till we had extremely unusual behavior in **production** where we were systematically updating and sort of canary testing images. Older images were needed to be run albeit rebooted while new images were working with a new schema.

Unfortunately one of the older images kept migrating a stored procedure back (in hindsight we should have put that in a different repeatable SQL script but we still probably would have had the issue).

Now we enforce `ignoreFutureMigrations` to false almost everywhere but I'm still extremely shocked about the above behavior and how little its documented. 

This could have been far more damaging but luckily was not.

If a new migration is present and `ignoreFutureMigrations` is `true` I would expect the flywaydb to do nothing if run on an older version and not migrate anything.

Give that some people are possibly expecting this behavior (backwards compatibility) it seems new configuration is required to enable what we were originally trying to do in production.

**Comment by axelfontaine** [comment]
This is really a tricky one.

A. Your situation is as follows: 
- one had an original repeatable migration in V1 of the software
- updated it for V2
- wasn't happy with the changes and reverted the software to V1
- expected the migration to not be reapplied and instead of having it being marked as future.

B. The very same situation could also be interpreted very differently: 
- one had an original repeatable migration in V1 of the software
- updated it for V2
- wasn't happy with the changes and reverted them for V3
- fully expecting them to be applied as part of the V3 rollout instead of having the migration being marked as future

Since Flyway doesn't have access to the application version, both of these appear identical with no way to automatically decide which variant should used.

Flyway currently always chooses the B variant which is the correct choice in the overwhelming majority of the cases. Until we find a clean way to differentiate, I don't see how we could support the A variant.

**Comment by MikielAgutu** [comment]
As Axel's comment says, Flyway has an opinionated workflow. Unfortunately we can't support every case.
