### ISSUE TITLE
PostgreSQL: Parse search_path to determine name of first non-existing schema to create

### ISSUE THREAD

**Issue by jnatten** [flyway/flyway#2182]
This might just be me doing something stupid, or even an issue with HikariCP or something else, but I'll try here first.

###### Which version and edition of Flyway are you using?
5.2.0 Community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API from Scala.
(`"org.flywaydb" % "flyway-core" % "5.2.0"`)

###### Which database are you using (type & version)?
postgres 9.5

###### Which operating system are you using?
archlinux

###### What did you do?
Empty database (without schema) and:
```
val dataSourceConfig = new HikariConfig()
dataSourceConfig.setUsername("user")
dataSourceConfig.setPassword("pw")
dataSourceConfig.setJdbcUrl("jdbc:postgresql://localhost:5432/mydb")
dataSourceConfig.setSchema("apischema")
dataSourceConfig.setMaximumPoolSize(30)
val ds = new HikariDataSource(dataSourceConfig)

val flyway = Flyway
  .configure()
  .table("schema_version") // I used 4.x before
  .dataSource(ds)
  .load()
flyway.migrate()
```

I can work around it like this, but i _think_ flyway could do this itself?
```
val flyway = Flyway
  .configure()
  .table("schema_version")
  .schemas(ds.getShema())
  .dataSource(ds)
  .load()
```

###### What did you expect to see?
Expected flyway to create the schema i specify with `dataSourceConfig.setSchema(...)`

###### What did you see instead?
Flyway crashes:
```
org.flywaydb.core.api.FlywayException: Unable to determine current schema as search_path is empty. Set the current schema in currentSchema parameter of the JDBC URL or in Flyway's schemas property.
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.doGetCurrentSchema(PostgreSQLConnection.java:64)
	at org.flywaydb.core.internal.database.base.Connection.getCurrentSchema(Connection.java:92)
	at org.flywaydb.core.Flyway.prepareSchemas(Flyway.java:1650)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1571)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1249)
```

**Comment by axelfontaine** [comment]
How exactly do you believe Flyway could get access to the schema info within knowing anything specific about HikariCP?

**Comment by deepd** [comment]
I see the same issue. In version 4.2.0 the `execute(Command<T> command)` was creating a DbSupport using `DbSupportFactory.createDbSupport(connectionMetaDataTable, !dbConnectionInfoPrinted)` and corresponding PostgresDbSupport would return correct schema in `getOriginalSchema()` method but in version 5.2.3 the `execute(Command<T> command, boolean scannerRequired)` creates a DataBase using `DatabaseFactory.createDatabase(configuration, !dbConnectionInfoPrinted)` and corresponding `PostgresSQLConnection#doGetCurrentSchema()` for `PostgresSQLDatabase` throws error. It can get correct schema by using `getCurrentSchemaNameOrSearchPath()`.

I was able to solve by explicitly setting the schema in `FluentConfiguration` and using it in `Flyway` instance creation.

**Comment by axelfontaine** [comment]
I dug a little deeper. With `Connection.setSchema()` (used behind the scenes by HikariCP) the PostgreSQL JDBC driver sets the `search_path` to this value. In general the `search_path` may contain any number of comma-separated schema names, regardless of whether they exist or not. Flyway then uses PostgreSQL's `SELECT current_schema` query to obtain the first one that exists. In this specific example this rightly returns nothing.

I am currently not sure we want to change this behavior as doing things differently requires quite a bit more work when accounting for all edge cases, while providing marginal additional benefit.

Deferring.

**Comment by andersthorbeck** [comment]
I am experiencing what I believe to be essentially a variant of this issue (which is why this is a comment and not raised as a separate issue).

My environment:
OS: macOS Sierra 10.12.6
Application on Spring Boot version: v2.1.0.RELEASE
Application gradle dependencies: org.flywaydb:flyway-core:5.2.1, org.postgresql:postgresql:42.2.2
Flyway version: Flyway Community Edition 5.2.1 by Boxfuse
Database version: PostgreSQL 9.6
Database driver: PostgreSQL JDBC Driver 42.2.2

In a Spring Boot application, I specify datasource config of the following format:
```
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb?currentSchema=myschema
spring.datasource.username=user
spring.datasource.password=pwd
```

I have a local PostgreSQL database cluster running on port `5432` of `localhost`, with an existing database named `mydb`, but which _lacks_ the schema `myschema`. Upon start-up of my application I expected Flyway to create this missing schema, as it already provided in the JDBC URL. Instead, however, the following exception is being thrown at start-up:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Unable to determine current schema as search_path is empty. Set the current schema in currentSchema parameter of the JDBC URL or in Flyway's schemas property.
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
  ...
Caused by: org.flywaydb.core.api.FlywayException: Unable to determine current schema as search_path is empty. Set the current schema in currentSchema parameter of the JDBC URL or in Flyway's schemas property.
  at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.doGetCurrentSchema(PostgreSQLConnection.java:64) ~[flyway-core-5.2.1.jar:na]
  at org.flywaydb.core.internal.database.base.Connection.getCurrentSchema(Connection.java:92) ~[flyway-core-5.2.1.jar:na]
  at org.flywaydb.core.Flyway.prepareSchemas(Flyway.java:1742) ~[flyway-core-5.2.1.jar:na]
  at org.flywaydb.core.Flyway.execute(Flyway.java:1663) ~[flyway-core-5.2.1.jar:na]
  at org.flywaydb.core.Flyway.migrate(Flyway.java:1341) ~[flyway-core-5.2.1.jar:na]
  at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.1.0.RELEASE.jar:2.1.0.RELEASE]
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
  ... 16 common frames omitted
```

Notably, the exception states that (emphasis mine)
> org.flywaydb.core.api.FlywayException: Unable to determine current schema as **search_path is empty**. **Set the current schema in currentSchema parameter of the JDBC URL** or in Flyway's schemas property.

However, this is precisely what I have already done. The datasource URL specifies `currentSchema=myschema` as a query parameter. Consequently, upon debugging my application, `search_path` is also demonstrated to be `myschema` as expected, when `org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection#getCurrentSchemaNameOrSearchPath` is called:
```
    @Override
    protected String getCurrentSchemaNameOrSearchPath() throws SQLException {
        return jdbcTemplate.queryForString("SHOW search_path");
    }
```

However, although this method is called in `org.flywaydb.core.internal.database.base.Connection#doGetCurrentSchema`, it is _not_ called in the overridden method `org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection#doGetCurrentSchema`, which instead queries for `SELECT current_schema`. Upon finding that result to be empty, it does not try using `search_path`, but instead immediately fails.

This behaviour seems wrong to me, because
1. The exception claims `search_path` is empty when it is not.
2. The exception's suggested solution of setting the "currentSchema parameter of the JDBC URL" does not work.
3. The [flyway documentation](https://flywaydb.org/documentation/commandline/migrate) indicates that Flyway will create schemas which do not already exist.

As far as point 3. goes, I realize that this documentation is talking about the flyway properties, and not the `currentSchema` of the JDBC URL. I think it could be a useful feature if flyway could extract the schema from the JDBC URL if none is provided to Flyway directly. However, if nothing else, I think my other points still stand that the exception message is misleading. I think it would be more useful to point out that the schema specified in `currentSchema` does not actually exist.

**Comment by agebhar1** [comment]
@andersthorbeck try to add the property setting
```
spring.flyway.schemas=myschema
```
From Spring Boot Documentation:
> spring.flyway.schemas= # Scheme names managed by Flyway (case-sensitive).

**Comment by andersthorbeck** [comment]
Thank you @agebhar1. I should probably have made that clear in my previous post; I am (after some head-scratching) already aware that this is the solution. It will undoubtedly fix the issue. My main point however, although I may not have expressed it clearly enough, is that I feel like specifying the schema in a separate property should not be necessary when it can already be deduced from the JDBC URL.

**Comment by agebhar1** [comment]
I agree with you @andersthorbeck this is cumbersome.

**Comment by ErwanLeroux** [comment]
What can be done about this issue ? Should the method org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection#doGetCurrentSchema call the method org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection#doGetCurrentSchema ?

**Comment by MikielAgutu** [comment]
If I understand this correctly, the problem is really an inconsistency between JDBC url params and Flyway's config properties. Of course conceptually these are different, but it's reasonable to expect Flyway to look at the JDBC url also.

We're either going to make Flyway parse the schema correctly from the JDBC url, or at least make the exception message clearer and more consistent.

**Comment by OctavioCega** [comment]
@andersthorbeck I was facing the same weird problem. Flyway was not creating the schema. I just updated to 
`Springboot 2.3.4.RELEASE `
and 
`dependency management to 1.0.10.RELEASE`
And It is now working as Expected!
I really dont know why, I didn't do any research.
Note: if you are using the jaxav validation api, you could need to add 'org.springframework.boot:spring-boot-starter-validation' as it is not longer included in web starters
