### ISSUE TITLE
Add flag to fail-fast in case a location cannot be found

### ISSUE THREAD

**Issue by artjomsimon** [flyway/flyway#2205]
###### Which version and edition of Flyway are you using?
5.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-Line

###### Which database are you using (type & version)?
Postgres 10.5

###### Which operating system are you using?
Arch Linux

###### What did you do?

* `flyway -configFiles=app/config/flyway.dev.conf migrate`
* with `flyway.locations=filesystem:<location>` in the config file
* `<location>` being an in accessible folder.

###### What did you expect to see?
A non-zero return code so that my CI/CD pipeline doesn't think everything went alright and it can continue deploying.

###### What did you see instead?
A zero return code.

---

This was already noted in the last comment in issue #168 but probably got forgotten.

**Comment by juliahayward** [comment]
Not convinced it deserves an option in its own right, it feels correct to Mikiel and me that we should fail rather than warn on a location not found (or inaccessible) as it may reveal deeper problems - but it's a potentially breaking change for people who just ignore the warning. Any thoughts?

**Comment by Lyeeedar** [comment]
Maybe we want this potentially breaking change be for flyway 7, but add an extra message if there were any non-existent paths that this would become an error in 7 (like the default schema one)?

**Comment by MikielAgutu** [comment]
For Flyway 7 we'll promote these to errors. In the meantime we'll update the warning messages to give notice of this breaking change.

**Comment by MikielAgutu** [comment]
These now produce errors.

**Comment by joehorsnell** [comment]
@MikielAgutu (cc @artjomsimon) - we've just encountered this exact issue. A change was made in our Flyway migrations code to move the locations of some scripts, which had the unintended consequence of breaking a relative path to the `flyway.locations` property.

In CI, the build did not fail, as the flyway script still exits 0, it just printed out `ERROR: Skipping filesystem location:... (not found).` in the logs. This seems like pretty dangerous default behaviour to me, as you don't generally look at the logs of successful (or "successful" in this case) builds, so there is nothing to alert you to the fact that migrations haven't in fact run.

Can I just confirm - is this the expected and intended behaviour? If so, I'd like to politely question again whether this is desirable and ask if you would you accept a PR to fix this, to either make Flyway raise an exception in this case (rather than just `ERROR` log) and exit non-zero, or at least to provide a backwards-compatible, opt-in mechanism (as per the title of this issue) to add a command-line argument to switch on this exit-non-zero behaviour in the case of the specified locations not being found?

Should I raise a new issue for this to track? Thanks.

**Comment by MikielAgutu** [comment]
@joehorsnell This is the expected behavior, yes. I agree that you'd always want to be alerted if your locations are invalid. However making Flyway blow up completely would be a significant breaking change which might break many installations which are relying on this behavior (rightly or wrongly).

I suppose from your comment it looks like the error wasn't quite enough. I'll re-open this and we can re-consider adding a flag to enforce this behavior.

**Comment by joehorsnell** [comment]
> @joehorsnell This is the expected behavior, yes. I agree that you'd always want to be alerted if your locations are invalid. However making Flyway blow up completely would be a significant breaking change which might break many installations which are relying on this behavior (rightly or wrongly).
> 
> I suppose from your comment it looks like the error wasn't quite enough. I'll re-open this and we can re-consider adding a flag to enforce this behavior.

Thanks for the quick response @MikielAgutu - yep, the error silently logged in the console is not a great deal of use if the build succeeds - it's like tests printing to the console that they'd failed, but then the build still succeeding.

I think adding a `--strict` or `--fail-on-errors` command-line switch would be a good approach as this is opt-in and could be made the default in the next major version?

In the meantime, do you have any suggested workarounds? The only (hacky) thing I can think of is to `grep` for the presence of `ERROR:` in the log and fail the build manually if found.

**Comment by MikielAgutu** [comment]
One of our assumptions was that errors would be detected by a CI/CD system and surfaced in a reasonable way. If your system isn't doing that, then it's unfortunate... I suppose the only workaround at that point is to manually search through the logs with something like `grep` as you suggest.

**Comment by joehorsnell** [comment]
> One of our assumptions was that errors would be detected by a CI/CD system and surfaced in a reasonable way. If your system isn't doing that, then it's unfortunate...

I see. How would you expect that to work, out of interest? There is no "standard interface" (as far as I'm aware?) in logs for "here is an error" and "here is a warning", etc. It's just text in stdout/stderr, so how would a CI/CD tool know what to look for? It _happens_ that the Flyway output has a prefix of "ERROR: ", but without prior knowledge of that, it's just a line of log output? Shell exit codes on the other hand are a pretty standard and well understood mechanism of denoting success from failure.

>I suppose the only workaround at that point is to manually search through the logs with something like `grep` as you suggest.

Yep, ok thanks I'll do that for now 👍.

**Comment by joehorsnell** [comment]
@MikielAgutu - it looks like it would be pretty easy to add this support. Possible design:
- Add a new boolean config setting called, say, `flyway.ignoreErrors` (default to true) or `flyway.exitOnErrors` (default to false), with associated command-line switch and env var support (not sure if the docs on the website get automatically updated?)
- Add a new util method (maybe to `ExceptionUtils`?) called `throwExceptionIfRequired(String message)` that checks the boolean config setting above, either logging an error (current behaviour) or throwing a runtime exception
- Replace all calls to `LOG.error` (primarily in `org.flywaydb.core.internal.scanner` package) with calls to the new method above

My assumption here is that raising an exception would then bubble up and cause the command-line process to exit non-zero, or if Flyway was being run programatically, to just blow up, then the calling code would have to deal with that.

It would obviously be fully backwards compatible as the default would be set to current behaviour, but you could opt-in by setting the new config param, through whichever config mechanism was most convenient.

I don't want to waste my time if this doesn't sounds reasonable, but if you'd be willing to accept a PR for this, I'm happy to look at this. Also, just to confirm, would you be OK adding this feature to the 7.x branch for a minor/patch release on the current version, as well as main development line, as it's backwards compatible, if appropriately defaulted?

**Comment by MikielAgutu** [comment]
@joehorsnell If you can wait for us to prioritize this work, I think it makes sense for us to take this on. I think we agree on how the feature should ultimately work, but I'm not quite sold on your approach to implementation.

It probably makes more sense to introduce another implementation for the `Log` interface that throws when the `error` method is called. Also there is a lot of tedious boilerplate required in adding a new configuration option which I would spare you.

That said, if you'd like to try anyway then go ahead.

Also, we can probably do this as a minor version update, since it should be backwards compatible.

**Comment by joehorsnell** [comment]
Thanks for the quick response @MikielAgutu 👍.

Do you have any feel for when you'd realistically be able to do this? Depending on whether the answer was days, weeks, months (or years! 😀) it would influence the answer to your question.

Noted your suggestion re the different log interface 👍.

**Comment by MikielAgutu** [comment]
Hard to say exactly, sorry! It's not a huge piece of work but we have to weigh it up against other priorities.

I can tentatively give a timeframe of within the next month or two.
