### ISSUE TITLE
SQL*Plus: SHOW and SET should allow multiple commands on same line

### ISSUE THREAD

**Issue by pjchester** [flyway/flyway#2210]
###### Which version and edition of Flyway are you using?
flyway-5.2.1 Enterprise

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using (type & version)?
Oracle 12.1

###### Which operating system are you using?
Windows 10

###### What did you do?
sqlplus script with the initial line: `set define off verify off feedback off`

command: `flyway -enterprise migrate`

###### What did you expect to see?
That `set define off` would be processed and the `&var` placeholders ignored

###### What did you see instead?
The multiple `set` options on the same line means `set define off` is not processed.  As a result the `&placeholders` are attempted to be evaluated and script fails.

The script is an **auto generated export of an Oracle Apex application**, so editing the file is not encouraged.

In addition, the `set verify` and `set feedback` commands are ignored.

**Comment by axelfontaine** [comment]
Thanks for the report. As part of the fix for this issue we're adding support for

- [X] `PROMPT` without arguments
- [ ] `SET` without arguments
- [ ] `SET` with multiple arguments
- [ ] `SET VERIFY`
- [ ] `SET FEEDBACK`
- [X] `SHOW` without arguments
- [X] `SHOW` with multiple arguments
- [X] `SHOW DEFINE`
- [X] `SHOW ESCAPE`
- [ ] `SHOW FEEDBACK`
- [X] `SHOW NULL`
- [ ] `SHOW VERIFY`

**Comment by axelfontaine** [comment]
This has now been implemented and will be released in the next few days as part of 5.2.2.
