### ISSUE TITLE
MariaDB 10.4 support

### ISSUE THREAD

**Issue by axelfontaine** [flyway/flyway#2300]
This is the current beta release

**Comment by TheUltimateDeployer** [comment]
We are using Spring Boot in combination with MariaDB.
Upgrading to MariaDB driver failed due to this issue. Moving to Flyway 6.0.0-beta is blocked by 
"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration': Unexpected exception during bean creation; nested exception is java.lang.TypeNotPresentException: Type org.flywaydb.core.api.callback.FlywayCallback not present"
It  seems that Spring Boot isn't supporting the 6.0.0-beta version.

I think this issue should also be fixed in the 5.2.x release branch and I will create a PR for this. 
Do we need to take care of your corresponding changes in the  PositionTrackingReader.java and RecordingReader.java?

KR Christian
