### ISSUE TITLE
Question on transactionality of migration in a dialect implementation

### ISSUE THREAD

**Issue by mrotteveel** [flyway/flyway#2375]
I'm currently working on a dialect implementation for Firebird (to replace #1889, see also #441). I'm wondering how to handle a problem with transactional behaviour of combining DDL and DML involving the same tables.

In Firebird, DDL is transactional, and DDL and DML can be combined in a single transaction, but DML cannot use objects created by the DDL. So, when creating a table, you cannot insert into that table in the same transaction, or when adding a column, you cannot use that column in DML in the same transaction.

Does this need to be addressed in some way in the dialect implementation (and if so, how?), or should this be something that users need to be aware of and handle by defining separate migrations?

**Comment by juliahayward** [comment]
The principal means is for an override of `Parser.detectCanExecuteInTransaction()` to determine whether a statement is possible in a transaction or not. The problem is that currently this looks on a single statement level and so won't catch the case where two statements are each transactional on their own but can't be in the same one.

Cockroach has a similar behaviour and their dev team recommended simply not running anything in transactions. If that is too drastic, then users should be prompted either to override `executeInTransaction` on a per-script basis, or make sure that conflicting DML and DDL go in separate migrations.
