### ISSUE TITLE
Cannot run migrations with "jdbc:sqlite::memory:" url

### ISSUE THREAD

**Issue by igorya7v** [flyway/flyway#2403]
###### Which version and edition of Flyway are you using?

5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

SQLite (in-memory)

###### Which operating system are you using?

Ubuntu 18.04 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

When try to run migration with "jdbc:sqlite::memory:" url the
flyway.migrate() returns 1, means the migration was successful, however there where no table created at all.

When try to run exactly the same code with "jdbc:sqlite::test.db" url it works, the tables are successfully created.

###### What did you expect to see?

Migration successfully creates tables when run with "jdbc:sqlite::memory:" url. 

###### What did you see instead?

No tables are created.

**Comment by axelfontaine** [comment]
This is due to the way SQLite handles connections. Once a connection to the in-memory database closes, all contents of the database are lost. As Flyway always closes the resources it opens to avoid any leaks, you need to first wrap your connection and suppress the close method. Spring's SingleConnectionDataSource lets you easily achieve this.
