### ISSUE TITLE
How and when does contributed code get merged?

### ISSUE THREAD

**Issue by RohitJain13** [flyway/flyway#2480]
Hi Flyway developers,

I have contributed changes to Flyway to support Apache Trafodion and EsgynDB.  The Pull Request is waiting on someone with write access to merge it.  What is the process for these changes to get reviewed and merged?

Rohit

**Comment by MikielAgutu** [comment]
Thanks for your question.

We're always happy to see community contributions! However, the type of contribution affects how easy it is for us to accept.

Bug fixes are likely to be accepted and merged, whereas bigger changes require more consideration since they incur ongoing maintenance costs.

As for supporting new databases, these fall under the category of bigger changes. There's a fair bit for us to keep track of: differences between versions, new releases, setting up testing infrastructure, and so on. We are still in the process of clarifying our policy, and we intend to publish it soon.

**Comment by MikielAgutu** [comment]
An article explaining our policy can be found here https://flywaydb.org/documentation/contribute/contributingDatabaseSupport
