### ISSUE TITLE
Getting unsupported error with correct versions?

### ISSUE THREAD

**Issue by Tauri28** [flyway/flyway#2481]
###### Which version and edition of Flyway are you using?
6.0.0 Community Edition
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI
###### Which database are you using (type & version)?
MariaDB (ver. 10.2.20)
###### Which operating system are you using?
Windows 10 Pro 1809
###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
flyway migrate -url=jdbc:mysql://127.0.0.1/hmvc_listing?serverTimezone=UTC -user=xxx -password=xxx -table=xxx -locations=xxx -sqlMigrationSeparator=- -baselineOnMigrate=true -baselineVersion=000 -sqlMigrationPrefix='.
###### What did you expect to see?
Successful migration.
###### What did you see instead?
ERROR: Flyway Enterprise Edition or MariaDB upgrade required: MariaDB 5.5 is no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition.

**Comment by goekay** [comment]
[we](https://github.com/RWTH-i5-IDSG/steve/) experience the same issue with builds using travis ci.

**Comment by pzygielo** [comment]
@Tauri28:
> flyway migrate -url=jdbc:mysql://127.0.0.1/hmvc_listing?serverTimezone=UTC -user=xxx -password=xxx -table=xxx -locations=xxx -sqlMigrationSeparator=- -baselineOnMigrate=true -baselineVersion=000 -sqlMigrationPrefix='.

On https://flywaydb.org/documentation/database/mariadb the format of url is `jdbc:mariadb:...`, but you are using `jdbc:mysql:...`. Do you get the same error with url corrected?

**Comment by MikielAgutu** [comment]
I've managed to reproduce this. As @pzygielo suggested the problem is that you're using a MySQL JDBC url instead of a MariaDB one. If you use `jdbc:mariadb://127.0.0.1/hmvc_listing...` it should be fine.

I can't see a reason why we'd need to support such interchangeability. Is there an advantage to using the MySQL JDBC url?

**Comment by goekay** [comment]
in our case, our product leaves the choice of database (mysql or mariadb) to the user/client. and since mariadb is supposed to be a [drop-in replacement](https://mariadb.com/kb/en/library/mariadb-vs-mysql-compatibility/) _with some limitations_ and since mariadb connector/j itself allows [both usages](https://mariadb.com/kb/en/library/about-mariadb-connector-j/#connection-strings) `jdbc:(mysql|mariadb)` i see this as a minor problem.

moreover, this was working with flyway 5.2.4 but stopped with 6.0.0 even though mariadb version we use (10.2.26) did not change. mariadb 10.2.26 is for sure newer than mariadb 5.5. therefore the report is not true.

**Comment by MikielAgutu** [comment]
Fair point! This is due to slightly odd behavior in the way JDBC reports Maria DB versions. We've introduced a fix that should be in the next release.

**Comment by goekay** [comment]
thanks! as i understand from the commit, the version identification is corrected, which means we can continue using the prefix `jdbc:mysql:...` with mariadb, right?

**Comment by MikielAgutu** [comment]
Yes you can continue using that url.

**Comment by JavaNeed** [comment]
Could you please guide me here: https://stackoverflow.com/questions/61558150/caused-byorg-flywaydb-core-internal-license-flywayeditionupgraderequiredexcepti ?

**Comment by ADAMBRITTRG** [comment]
This restriction is no longer in place from Flyway version 10 (October 2023). We have updated Flyway so that it works with ALL supported database versions, so if you upgrade to version 10 you can access all supported versions of MariaDB.

The community version of Flyway now works with All versions of MariaDB.

You can access the latest download from https://www.red-gate.com/products/flyway/community/download/
