### ISSUE TITLE
Azure MySQL database version incorrectly detected (5.6 instead of 5.7)

### ISSUE THREAD

**Issue by antoniomateo** [flyway/flyway#2519]
###### Which version and edition of Flyway are you using?

6.0.4 - Community edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using (type & version)?

Azure MySQL 5.7, not 5.6 as the error says. See this note in Azure:

NOTE: In the service, a gateway is used to redirect the connections to server instances. After the connection is established, the MySQL client displays the version of MySQL set in the gateway, not the actual version running on your MySQL server instance. To determine the version of your MySQL server instance, use the SELECT VERSION(); command at the MySQL prompt.

Extracted from: https://docs.microsoft.com/en-us/azure/mysql/concepts-supported-versions

###### Which operating system are you using?

Ubuntu:latest

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Ran the flyway maven plugin to migrate an Azure database for the first time:
goals: 'flyway:migrate'

###### What did you expect to see?

The database tables created.

###### What did you see instead?

[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:6.0.4:migrate (default-cli) on project initializer: org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException: Flyway Enterprise Edition or MySQL upgrade required: MySQL 5.6 is no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition. -> [Help 1]

**Comment by MikielAgutu** [comment]
Looks like this is a [bug within the MySQL Azure service itself](https://docs.microsoft.com/en-us/azure/mysql/concepts-limits#current-known-issues):

> MySQL server instance displays the wrong server version after connection is established. To get the correct server instance engine version, use the `select version();` command.

I don't think we can do anything about it unfortunately. We'll have to wait for Microsoft to fix the issue on their end.

**Comment by juliahayward** [comment]
Actually, I have a workround. Reopening...

**Comment by antoniomateo** [comment]
Hi Julia. Great, that's good news. Could you explain the workaround please? Thanks in advance.

**Comment by juliahayward** [comment]
Essentially we can spot the case where the JDBC metadata and result of `select version();` return conflicting information, and in that case assume that the latter is correct - at least until such time as Azure is confirmed fixed. I hope to get it into 6.0.5 which should happen early this week.

**Comment by Matonen** [comment]
Trying to migrate using Flyway Community Edition 6.0.6 by Redgate but i get following error:

```
WARNING: Azure MySQL database - reporting v5.6 in JDBC metadata but database actually v5.7.26-log
ERROR: Version may only contain 0..9 and . (dot). Invalid version: 5.7.26-log
```

**Comment by Matonen** [comment]
I also run `select version()` using the  MySQL Workbench and it returns `5.7.26-log`.  MySQL server tier is Basic and version is 5.7. Server is created to WestEurope.

**Comment by stevenenen** [comment]
I have the exact same issue, but I just found out that it's because of the `Basic 5.7` version. Try to create a `General Purpose, 2 vCore(s), 100 GB` and then it works for now.

**Comment by juliahayward** [comment]
Many thanks - I've reproduced it now. A fix on the way for 6.0.7.

**Comment by tygern** [comment]
I'm still seeing this issue using MySQL 8.0 in Azure and version 6.1.1 of the Flyway gradle plugin.

**Comment by stevenenen** [comment]
I also still have this issue when using a Basic 5.7 tier. It only works for me with a General Purpose, 2 vCore(s), 100 GB.

**Comment by juliahayward** [comment]
@tygern @stevenenen Would you be able to run `SELECT VERSION()` on your dbs and let me know what the results are?

**Comment by juliahayward** [comment]
@tygern I've got a repro for you, a fix will go in v6.1.2. @stevenenen No joy when I create a Basic 5.7 db... could you also send me the output of `flyway info -X` please (do redact any database names, credentials, etc.)?

**Comment by tygern** [comment]
@juliahayward Great, thanks. Just to answer your question, I saw `8.1.0` when I ran `SELECT VERSION()` on my db on Azure.

**Comment by javaHelper** [comment]
Could you please guide me here: https://stackoverflow.com/questions/61558699/caused-by-org-flywaydb-core-api-flywayexception-migration-failed-and-spring ?

**Comment by juliahayward** [comment]
Hi Ash, as mentioned in the SO post the underlying problem is that you migration is invalid for the version of MySQL you're using.

I see in your Stack Overflow post that you are using Flyway 5.2.4. There were a number of fixes around MySQL versioning in v6 a while back and we recommend you upgrade as far forward as possible.

**Comment by brent777** [comment]
I am using Flyway with a Kotlin / Micronaut application and I am still running into this same issue with an Azure MySQL 8 database. My Flyway version, etc:

16:16:42.946 [main] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 6.4.4 by Redgate
16:16:43.257 [main] INFO  o.f.c.i.database.DatabaseFactory - Database: jdbc:mysql://xxx (MySQL 5.6)

I have confirmed that the database is MySQL 8. Also I have confirmed that when connecting to a local MySQL 8 database, as opposed to one on Azure, I get the correct version coming through in the second info log statement above.

I believe this issue was fixed prior to version 6.4.4, any idea why I am still running into it given that I am running version 6.4.4?

**Comment by juliahayward** [comment]
@brent777 What is the exact output of `select version()` on this database please?

**Comment by juliahayward** [comment]
@brent777 Any news?

**Comment by juliahayward** [comment]
Revisited it with the current version (v8.0.15). The correct string comes through from MySQL `SELECT VERSION()` and Flyway identified the database as v8.0. In the absence of more feedback, closing. (as possibly an Azure MySQL problem that has been fixed)

**Comment by pschwager** [comment]
@juliahayward I just tested it with MySQL 8.0.15 on Azure and flyway still detects it as 5.x. Are you sure that you aren't parsing something from the welcome header? (which reports a 5.6 instead of the 8.0)

`Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 64864
Server version: 5.6.47.0 Source distribution

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.15    |
+-----------+
1 row in set (0.00 sec)
`

**Comment by DoodleBobBuffPants** [comment]
@pschwager Do you still get the `no longer supported by Flyway Community Edition` exception? It should still succeed and only be printing the (incorrect) version returned by the metadata

**Comment by juliahayward** [comment]
@pschwager We certainly don't parse the header, although it is quite possible the JDBC driver does under the hood (which would explain the consistent problems with incorrect JDBC metadata we have to work around). Could you confirm the version of the JDBC driver you're using?

**Comment by pschwager** [comment]
OK, after a long search through the code, I found a property which sets the `org.hibernate.dialect.MySQL57Dialect`. After that was removed flyway also wasn't failing. So my issue is also fixed. Sorry for the tumult...

**Comment by juliahayward** [comment]
Thanks for letting us know! It's really helpful for us as we weren't aware of that property - it might help out some of the other people on the thread.
