### ISSUE TITLE
Ignore line endings when calculating checksums

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#253]
_Original author: micha...@utest.com (September 28, 2011 15:49:50)_

We ran into the following problem.

Developer on Mac/Linux creates a sql migration file and checks it into Git.  It runs on production (which is on Linux) just fine.

Then a Windows developer takes a copy of the production database and loads it into their local machine.  But when they pulled the sql migration file from Git, it automatically converted the line endings to CRLF (Windows style).  Now Flyway validate and migrate fail saying there is a checksum mismatch.

One solution I can think of would be to ignore line endings when doing the checksum. 

_Original issue: http://code.google.com/p/flyway/issues/detail?id=167_

**Comment by kylecordes** [comment]
I am really surprised to run in to this problem - it is exactly the sort of thing I expected to "Just Work".

I am even more surprised to see resistance to fixing it!

Hopefully the suggest workaround of converting all files to LF-only, before letting Flyway see them, won't be too awful to hack together.

**Comment by axelfontaine** [comment]
Hi Kyle,

you may be surprised and you're probably thinking that since it's only a matter of adding ```script.replace("\r", "")``` it should be fixed in an instant. However there is more than meets the eye. This seemingly trivial fix **invalidates the metadata table on every single Flyway installation out there**. And so great care must be taken to make this transition as smooth as possible, with no surprises. And since Flyway follows the tried and true principles of semantic versioning, it is something that'll have to wait until the next major release.

Cheers
Axel

**Comment by kylecordes** [comment]
While that smallest fix has the problem above, the software is *already* completely broken in the way you describe for anyone working across platforms. So while invalidating metadata is a bad thing, it is already invalidated for lots of people.

There is an easy fix could be made, even without a major version: add an optional setting that brings in the new behavior now. Well I very much agree with the bias against adding settings, a "stop being completely broken on cross platform projects" setting would be welcomed, even by the most vigorous opponent of settings.

There is also a more involved approach, which avoids the setting and produces immediately good results: start calculating the checksum both ways, and accept either is a match. This would be perfectly backward-compatible, so it would not require a major version, and it would fix the problem without invalidating any old metadata.

**Comment by axelfontaine** [comment]
Hi Kyle,

Truth be told the problem is really Git's "convenient" autocrlf feature. However, since it dominates the market, I agree we need to compensate for it within Flyway, so that users have a good experience.

Adding a temporary band-aid property in 3.2 is not an option. And unfortunately your last suggestion, which sounds very good on paper, is not fail-proof either. Example:

A windows & a linux user share the same DB. The windows user migrates it first with CRLF files. The linux user can now never validate the migrations. That is unless we go further and re-add the CRs in the migration files. But then by that point I must say, let's all just wait until April when this is fixed properly in 4.0 :-)

Cheers
Axel

**Comment by rallengrc** [comment]
There are two workarounds for this:
Don't use Git with core.autocrlf
Set the checksum to null on the DEV DB after the restore from PROD

I set the checksums to null and now its more broken than before I did that.  What can I do to get the checksums recalculated?  I'm running flyway from a WAR file on deployment and it breaks the app since it won't start.

**Comment by IRus** [comment]
@rallengrc This should help: http://flywaydb.org/documentation/command/repair.html

**Comment by rallengrc** [comment]
@IRus Thanks, I did not realize that command could be run from WAR file but it did work with <beans:bean class="org.flywaydb.core.Flyway" init-method="repair" id="flyway"> bean entry in my spring config

**Comment by liefke** [comment]
If I understand this thread correctly: The only reason that prevents fixing this issue is backward compatibility.

I think you need to think about a strategy for working with backward compatibility anyway:
* Either keep the structure and format of `schema_version` for all times
* Or allow changes for major versions and provide a migration tool
* Or add a `flyway_version` column to `schema_version` which helps to identify the format of the corresponding row

From my point of view the first option is the worst one, because it prevents improvements. I'm indifferent about the last two, because the migration tool would need an explicit action but keeps the remaining code clean from any "historic garbage", while the last one could help to build automatic migration or version switches.

**Comment by hohwille** [comment]
I also ran into this problem and am quite annoyed. Accepting #1031 is better than doing nothing.
Even better would be to add a property to disable ignoring of CR so one could gain backward compatibility and add this to the release notes.

**Comment by mymasse** [comment]
Running into this problem just now... Some devs use Windows and some Linux having a flag to make it ignore CR would be the best solution... And like previous commenters would make it backwards compatible.

**Comment by valery-barysok** [comment]
Running into this issue too...Sadly that it has no option for resolving this issue. And everyone have to do ugly fixes for that. For instance, put fixed SqlMigrationResolver on classpath before flyway or repack flyway through build process.

I vote for internal option (that will be removed in next version) that can ignore LE.

**Comment by mac2000** [comment]
Wondering can it be done in some kind of pluggable way. E.g. will be nice if I will be able to put some kind of jar somewhere with custom checksum calculation to override native one.

In my case I do want to strip not only new line symbols but also all space symbols before checksum calculation to avoid tab vs. space indentation in different editors.

**Comment by kylecordes** [comment]
Stripping all whitespace is great - clearly better than stripping only just CR.

This project has a bunch of recent commits, maybe there is hope for this long-known issue!

**Comment by axelfontaine** [comment]
Fixed. Line-endings are ignored and individual lines are stripped of leading and trailing whitespace before calculating the checksum. The upgrade to 4.0 will force a full checksum recalculation on existing metadata tables.

**Comment by mac2000** [comment]
@axelfontaine it is great news but to be fair that fix not going to solve issue (at least if we are speaking about white space symbols), for example if you are using something like SQL Management Studio - it will format your code in one way, but if in same time I will use something like DataGrip it will reformat code in another way. For example code like this:

```
CREATE TABLE Acme (
....Username.NVARCHAR(100),
....Age.INT
)
```

may become

```
CREATE TABLE Acme (
....Username.NVARCHAR(100),
....Age......INT
)
```

and checksums will be broken.

To me its seems that all whitespace symbols should be trimmed before calculating checksums rather than forcing people to use tabs/spaces/editorconfigs

**Comment by mymasse** [comment]
I don't agree with you @mac2000 
this:
```
insert into table values ('....Test....');
```
Is not the same as:
```
insert into table values ('Test');
```
You can't blindly trim all whitespace. Your problem is that both formatters are not the same. This fix resolve GIT line endings being different on Windows vs Linux.

**Comment by mac2000** [comment]
@mymasse you are totally right, but that can be respected while trimming all other whitespaces, and sorry for offtopic just wanted to share my thoughts of how can checksum calculation be improved.

**Comment by axelfontaine** [comment]
Come to think of it, I have now also removed the line trimming as it could potentially lead to different multiline string literals have the same checksum. Think of this issue as a workaround for the Git autocrlf "feature".

And yes, in an ideal world, Flyway would semantically parse the SQL file and ignore differences in formatting, spaces vs tabs, header comments (but not those inside Oracle packages and not the MySQL comment directives), complete vs concatenated strings with the same contents, etc.

However to avoid opening up a bottomless pit, for Flyway 4.0 this will be an autocrlf workaround and nothing more.

**Comment by mymasse** [comment]
@axelfontaine  Wow missed that one from your original comment, thought you fixed it by only ignoring line endings... By the way when roughly can we expect version 4.0? Couldn't find any info about a release date

**Comment by hohwille** [comment]
> However to avoid opening up a bottomless pit, for Flyway 4.0 this will be an autocrlf workaround and nothing more.

Feedback: This is totally fine with me. One can use additional tools to keep SQLs normalized. You could also say the normalizing EOL can be done by tools such as git. However, this is a very common pitfall and can easily happen when building on different platforms (one release on windows and one on linux). As this one is easy to fix, it is great that flyway is doing so and saving lots of headaches in the future.
In an ideal world it would also be nice to not take pointless whitespace changes or comment changes into checksum but at least this should be out of scope for this issue that needs a more urgent fix.

**Comment by ctapobep** [comment]
Waiting to see Flyway 4.0, this fix will be very helpful :)

**Comment by kiview** [comment]
How does this fix perform when upgrading to 4.0? Will it still be compatible to existing checksums?

**Comment by axelfontaine** [comment]
@kiview All checksums are automatically recalculated and updated with the new algorithm on first run

**Comment by steliomo** [comment]
Hi I simple fix this issue by running flyway:repair the flyway:migrate

**Comment by Halfbitscrambler** [comment]
I lately discovered that you calculate the CRC32, using the SQL file by first deleting any line endings. I see there a possible problem where e. g. the flyway file contains e. g. initial data with **and with more... without line breaks - that could change, but the CRC stays the same, even if the content in special cases changes drastically:**

`INSERT INTO AnInitialDataTable (Key, TextValue) VALUES ('uninstallToolCommand', 'rmdir e:\tools
rem use format e: in case it does not work'),
('connectionStringTemplate', 'server=<server>;db=<db>;user=<user>;password=<password>##<do not log:password>');`
 
Whether such values should be stored like this in the database and so on is an other topic.
A mean/unintentive hacker could exchange the SQL file with one, that is mean and has identical checksum, just by inserting line breaks:

`INSERT INTO AnInitialDataTable (Key, TextValue) VALUES ('uninstallToolCommand', 'rmdir e:\tools
rem use 
format e:
in case it does not work'),
('connectionStringTemplate', 'server=<server>;db=<db>;user=<user>;password=<password>
##<do not log:password>');`

--> instead of just deleting a folder, a whole drive would be deleted
--> a hacker could attempt to let a database connection setup fail and then read the plain text database password from a log file.

If the multi line text values contain **Python code** (snippets) an added line break could change the whole control structure... 
And adding e. g. 4000... line breaks won't change the CRC neither - but open a security hole?

Therefore I would have liked a more tamper secure approach for EOLs before calculating a CRC:
\r\n --> \n
\n --> \n
\r --> \n

**Comment by ctapobep** [comment]
@Halfbitscrambler it doesn't seem like you understand what these checksums are for in Flyway. They don't relate to security in any way. If anything, Flyway will see that the checksum didn't change and thus it will *NOT* apply the migration again.
