### ISSUE TITLE
Log output from resolvers and callbacks

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2606]
From a support email:

"We are using flyway via Java-API and need to get the log output of resolvers and callbacks under control of the flyway application to access them via flywayClient.log_results.

It would be great if you could consider enabling this feature in upcoming flyway versions."

**Comment by ebongard** [comment]
Hi there,

the situation is as follows. We are using sql based migrations e.g.
V1__Initial.sql
V1.1__Initialize.sql
V1.2__Populate_table.sql

as well as Java based Resolvers and Callbacks. Resolvers and Callbacks either implement or extend the appropriate Interfaces/Baseclasses, and we see that they are executed (based on the results).

We are starting the Migration process via a python wrapper (because of the local deployment solution), and if we are using the log_results method of the flyway client (after executing the migrate method), we are able to see information the sql scripts produce, but we are not able to see output that is generated by the Resolvers and Callbacks.

Could you pls advice on how to setup the logging within Java-Based resolvers and Callbacks so that the information can be collected via the log_results method of the Flyway client, or - in case this is not implemented - pls consider this as a feature request.

Many thanks in advance..

**Comment by juliahayward** [comment]
Are you able to give us more details about the python wrapper - is it calling the Flyway command line and capturing standard output, using the Java API, or some other means?

**Comment by MikielAgutu** [comment]
@ebongard Any news?

**Comment by MikielAgutu** [comment]
Closing for lack of response.
