### ISSUE TITLE
[SOLVED] Flyway does not recognize spring.flyway.locations config with spring boot 2 and junit 5

### ISSUE THREAD

**Issue by anderson-fachini** [flyway/flyway#2614]
###### Which version and edition of Flyway are you using?
6.1.3 (in fact I have already tried 5.x version and had the same problem)

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven or runnig through Eclipse

###### Which database are you using (type & version)?
H2

###### Which operating system are you using?
Windows 10

###### What did you do?
I created a maven project using Spring Boot 2.2.2 and Junit 5.  
The location of the migrations script is `src/test/resources/db_other/migration/h2`.  
I configured application.properties with `spring.flyway.locations=classpath:db_other/migration/{vendor}`  

Then I created a simple test that executes a query on database (select 1) to force Flyway to execute.

###### What did you expect to see?
I expected the migration to run.

###### What did you see instead?
I got the following exception:  
`org.springframework.boot.autoconfigure.flyway.FlywayMigrationScriptMissingException: Cannot find migration scripts in: [classpath:db/migration] (please add migration scripts or check your Flyway configuration)`

By the stack trace is possible to see that the custom locations configuration was not loaded.

**This work when running the application; just when I try to run a Junit 5 test the problem happens**

**Comment by alextercete** [comment]
@anderson-fachini Can you share more details on your project structure? For instance:

- Where is your `application.properties` file? Do you have one for the application and a separate one for the tests? If so, how are you specifying it?
- Are your test migrations supposed to run in addition to the application migrations?

My suspicion is that this is a `ClassLoader` issue. It looks like Spring Boot [uses the `ResourceLoader`](https://github.com/spring-projects/spring-boot/blob/a9b0b78cb2bcc4077179a926ff463a42129e96fc/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration.java#L251-L258) to check if the specified location exists, which suggests `src/test/resources` isn't in the classpath, probably because the tests has a dependency on the application and not the other way around (I don't know much about Spring, so I might be wrong).

The Flyway integration is built by the Spring Boot team themselves, so it might also be worth [asking them](https://github.com/spring-projects/spring-boot/issues/new) for advice.

**Comment by anderson-fachini** [comment]
I found the problem: My test class was annotated with @ExtendWith(SpringExtension.class) AND @ContextConfiguration(classes = { MyConfiguration.class }) instead of @SpringBootTest . When making this change the test worked.
