### ISSUE TITLE
Location of migration sql file

### ISSUE THREAD

**Issue by figo2264** [flyway/flyway#2615]
###### Which version and edition of Flyway are you using?
6.1 Version

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-Line

###### Which database are you using (type & version)?
Tibero  6

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

###### What did you expect to see?
I'm working on creating Tibero-Support feature and now I'm quite successful until running baseline.
However, it can't find any sql file when I run migrate. The location of migration sql file is ${project_root}/sql/migrate in my case.

should I put at a different location?

**Comment by MikielAgutu** [comment]
Off the back of https://github.com/flyway/flyway/issues/2599#issuecomment-564458565, you're adding support for a new DB engine, Tibero 6.

We'll need more information to help you. Can you create a Pull Request with your current progress. In the PR give clear reproduction steps (including set up of the DB) so that we, or community members, can help.

**Comment by alextercete** [comment]
On your specific issue, I think you need to specify the `locations` config option (by default, it's set to `<install-dir>/sql`).

See https://flywaydb.org/documentation/configfiles (search for "flyway.locations").
