### ISSUE TITLE
Migrate not validate again on error script in MariaDB

### ISSUE THREAD

**Issue by IvoSestren** [flyway/flyway#2625]
###### Which version and edition of Flyway are you using?
CE 6.0.8

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I dont try latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
MariaDB 10.4

###### Which operating system are you using?
Windows 10 - 64 bits

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
- I create a java class file to run modification in database with errors in SQL.
- I run this migration and show file contains error on execute them on database. (Its ok, has error)
- I correct migration file and run again.
- Now shows error on execute on validate migration.
- On table flyway_schema_history, field success shows 0

On other database servers in second run its all ok (postgresql, firebird), but in mariadb this second run not execute ok.

I not test in mysql.

###### What did you expect to see?
Migration runs ok

###### What did you see instead?
Error validation

**Comment by alextercete** [comment]
@IvoSestren Upon closer inspection, this isn't a bug; the behaviour you described is as intended.

The behaviour is different in Postgres and Firebird because they support DDL statements within a transaction (unlike MySQL and MariaDB), so the failed migration can be [rolled back cleanly](https://flywaydb.org/documentation/migrations#important-note).

When a migration fails in a database that doesn't support DDL statements withing a transaction (like MySQL or MariaDB), an entry is added to the schema history table -- which will appear as "Failed" when you run `flyway info` -- which indicates that manual clean-up might be required. After cleaning up, you should run [`flyway repair`](https://flywaydb.org/documentation/command/repair) to remove the "Failed" entry from the schema history table.

I understand that this might seem like a lot of trouble, especially in Development. In this case, I'd recommend switching on [`cleanOnValidationError`](https://flywaydb.org/documentation/commandline/migrate#cleanOnValidationError). **Be careful not to switch this on in Production, though!**
