### ISSUE TITLE
Multiple configurtion file problem error

### ISSUE THREAD

**Issue by vjkhalse33** [flyway/flyway#2647]
###### Which version and edition of Flyway are you using?
6.1.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
maven plugin

###### Which database are you using (type & version)?
oracle 11g

###### Which operating system are you using?

windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

creating multiple configurations  for single schema.
Hello Flyway,
1) when ever trying to give scripts in flyway in specific order it is not following the specific order,
the dependencies which are need to be picked in earlier script EX: (v1 has tables that need to be picked up first before executing G1,but it directly picks up G1 that throws error).

 2)There some files(scripts) that have different flyway.userid and password in the same schema .
so is ther any method that wee can have Dynamic  userid and password so that we can change when we run after migration

**Comment by MikielAgutu** [comment]
>when ever trying to give scripts in flyway in specific order it is not following the specific order,
the dependencies which are need to be picked in earlier script 

Versioned migrations are executed in version number order, so I assume you mean to order the execution of repeatable migrations.

Script ordering is a known inflexibility of Flyway that we're currently thinking about (See https://github.com/flyway/flyway/issues/2610, and https://github.com/flyway/flyway/issues/2541#issuecomment-547358068). We don't have a concrete timeframe on when a solution to this problem will be available.

Can you provide reproduction steps, including what you did, what you expected, and what actually happened?

> There some files(scripts) that have different flyway.userid and password in the same schema .
so is ther any method that wee can have Dynamic userid and password so that we can change when we run after migration

I'm not sure I completely understand what you mean. The [placeholder feature](https://flywaydb.org/documentation/placeholders) might help. You can configure placeholder values like the other config options (config file, CLI arguments, etc)

So in your script you can have something like:
```
${flyway.userid}
```

In each environment, call migrate like `flyway migrate --placeholders.flyway.userid=my_userid`, inserting the correct user id for each environment.

Does that help?

**Comment by MikielAgutu** [comment]
General problem captured here https://github.com/flyway/flyway/issues/2698
