### ISSUE TITLE
maven community plugin requires to remove pro license

### ISSUE THREAD

**Issue by vitas** [flyway/flyway#2692]
Hi our company bought pro license (we use flyway 6.1.1)
however, developers continue to use community edition via maven plugin and by it-ops we use console app

config files have license property set, but flyway complains we have to use pro edition plugin

Why the license property is not just ignored by community plugin?

we cannot use pro mvn plugin due restriction to download maven plugin from outside (also changing settings.xml is pain to change for all developers)

so developers and it-ops share the same conf files with license provided, develoepr should be able use maven plugin as community even they use conf file with provided license

**Comment by MikielAgutu** [comment]
If I understand correctly, you're providing a license key to the Flyway Community edition Maven plugin. Flyway is then producing a warning because it detects a license key.

I think the exception makes sense because generally if you provide a license key you expect to be using pro/enterprise. So it's to prevent users accidentally using community edition when they meant to use pro or enterprise.

That said, Flyway will also fail if you attempt to use a Pro/Enterprise feature in Community anyway.

We're thinking we should demote the exception to a warning. That way we can still alert users who have potentially made a mistake, whilst also unblocking users in your situation.

**Comment by vitas** [comment]
we use all settings in flyway.conf files and host license there. those files are shared between maven and consol app. We need just a warning not to fail having the license in conf file. Developers do not try to use pro features. 
Also, another big problem it is how to setup pro plugin: we cannot use external repositories in the company, thus cannot also put your repository settings to settings.xml and set password and user as license in pom.xml file. why all of this is so complicated for maven? console app has not this problem - you have a license you can run pro command. For maven you have to fetch pro plugin, do many extra settings, etc - not good

**Comment by MikielAgutu** [comment]
Now you've mentioned the `errorOverrides`, I've realized this is a bit more widespread than it first appeared. Really the general problem is interoperability between different editions. Currently, Flyway Community produces an exception if any pro/enterprise config option is set. The only way to avoid this is to have not set the options in the first place so they appear as `null`.

We don't think this is worth doing. Really you should use the same edition for all your work. Licenses are per production schema, so it doesn't cost any more to have lots of dev usages of paid Flyway editions.

For now I think the workaround is to use two config files, one with pro config, and one with community.

As for your case, you can't get the pro artifacts from our Maven repo due to company policy. It's a fair point that it's inconsistent that they aren't hosted on Maven Central. Given you're a Pro customer you should contact official Flyway support via email.
