### ISSUE TITLE
Building against enterprise flyway command line with gradle fails

### ISSUE THREAD

**Issue by Lyeeedar** [flyway/flyway#2702]
Making a gradle plugin and pulling in flyway commandline makes the build fail.

Execution failed for task ':db:compileJava'.

> Could not resolve all files for configuration ':db:compileClasspath'.

   > Could not find com.oracle:ojdbc8:18.3.0.0.0.

     Searched in the following locations:

       - https://ims-artifactory.ims.ch:443/artifactory/maven/com/oracle/ojdbc8/18.3.0.0.0/ojdbc8-18.3.0.0.0.pom

       - https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/com/oracle/ojdbc8/18.3.0.0.0/ojdbc8-18.3.0.0.0.pom

       - https://repo.flywaydb.org/repo/com/oracle/ojdbc8/18.3.0.0.0/ojdbc8-18.3.0.0.0.pom

     Required by:

         project :db > org.flywaydb.enterprise:flyway-commandline:6.2.4

                       

                         

With 6.1.4, it works

**Comment by nickeeromo** [comment]
Travis CI is producing a log from what looks like something that didn't come from me. We have:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for flyway-parent 0-SNAPSHOT:
[INFO]
[INFO] flyway-parent ...................................... SUCCESS [ 15.404 s]
[INFO] flyway-core ........................................ SUCCESS [ 25.190 s]
[INFO] flyway-gradle-plugin ............................... SUCCESS [ 5.880 s]
[INFO] flyway-maven-plugin ................................ SUCCESS [ 8.304 s]
[INFO] flyway-commandline ................................. FAILURE [ 1.922 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 56.998 s
[INFO] Finished at: 2020-03-07T01:23:25Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project flyway-commandline: Could not resolve dependencies for project org.flywaydb:flyway-commandline:jar:0-SNAPSHOT: Failed to collect dependencies at com.oracle:ojdbc8:jar:18.3.0.0.0: Failed to read artifact descriptor for com.oracle:ojdbc8:jar:18.3.0.0.0: Could not transfer artifact com.oracle:ojdbc8:pom:18.3.0.0.0 from/to flyway-repo (https://repo.flywaydb.org/repo): Not authorized -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project flyway-commandline: Could not resolve dependencies for project org.flywaydb:flyway-commandline:jar:0-SNAPSHOT: Failed to collect dependencies at com.oracle:ojdbc8:jar:18.3.0.0.0

Then further down:
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.oracle:ojdbc8:pom:18.3.0.0.0 from/to flyway-repo (https://repo.flywaydb.org/repo): Not authorized

After doing some research found this:
Create the settings-security.xml and settings.xml files: The Oracle Maven repository requires a user registration including a valid username and an encrypted password to be passed in settings.xml and settings-security.xml. [https://blogs.oracle.com/dev2dev/entry/how_to_get_oracle_jdbc#settings]

Here:
https://blogs.oracle.com/dev2dev/get-oracle-jdbc-drivers-from-the-oracle-maven-repo-netbeans-eclipse-intellij

**Comment by Lyeeedar** [comment]
This is half fixed. The community edition no longer pulls in the oracle driver and as such builds, but the pro/enterprise editions of the commandline still do. This means if you have them as dependencies it will still be broken.

Fixing that is going to be a longer process, but for now the public repo is back up and running.
