### ISSUE TITLE
Parsing bug with views having table with reserved keywords as aliases

### ISSUE THREAD

**Issue by twistyWater** [flyway/flyway#2703]
###### Which version and edition of Flyway are you using?
6.2.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
ORACLE 12.2.0.1

###### Which operating system are you using?
Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I have views with ORACLE keywords as aliases

CREATE OR REPLACE FORCE VIEW test AS
SELECT 1 FROM DUAL end
UNION
SELECT 2 FROM DUAL case
;

If I want the sql to work I need to double quote aliases. Normally I would do it myself but those view comes from a development partner which we have no control.

###### What did you expect to see?
Migration sucessfull like in sqlplus

###### What did you see instead?
ERROR: Unable to parse statement in C:\dev\flyway\flyway-6.2.4\sql\R__Test_View.sql at line 1 col 1: Flyway parsing bug: unable to decrease block depth below 0

**Comment by Lyeeedar** [comment]
The current flyway sql parser assumes that anytime you have end, it is to close a block. We currently do not support objects named like this, and won't be able to support it without a significant rewrite of the parser.

I'll leave the issue open for now to gauge interest.

**Comment by jxbadam** [comment]
I now understand this bug ... I have been hit with it several times, I'm guessing the parser update was after version `6.1.4` as that was the last time several of my migrations ran correctly.

Now that I know that `END` are to be used only as SQL keywords and not as anything else I think I won't have such issues. In my case I was creating a procedure and had `@END` as a variable name.

Fortunately I could change my name to `@END_TIME`, but still not overly intuitive and the error message doesn't help. Maybe add something to the error message to help others identify the problem since a more in depth code fix might not be possible or feasible. (`Flyway parsing bug: unable to decrease block depth below 0 (Did you use a keyword/alias of END?`) ... just my two cents after losing an hour to this today.

**Comment by Lyeeedar** [comment]
In https://github.com/flyway/flyway/commit/1aa99df1a2d0370507b591cfa29966dcf3811f06 we added a message when the parser fails linking to a page containing information about this issue. We can't however add more specific messaging (like your suggestion of `Did you use a keyword/alias of END?`) because the parser does not know which part of the statement broke things (it could be any control flow keyword that the database supports).

Hopefully the new messaging is enough to avoid people losing time to this issue.
