### ISSUE TITLE
Unable to apply repeatable script in schema without flyway_schema_history table

### ISSUE THREAD

**Issue by sdchhabaria** [flyway/flyway#2841]
###### Which version and edition of Flyway are you using?

6.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
MVN

###### Which database are you using (type & version)?
 Oracle 11g

###### Which operating system are you using?
Unix

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
In our databses, we have two schemas one is owner and other is USER schema.
All the database objects are created in OWNER schema's and their synonyms are created in USER schema.

The USER schema has only CREATE SYNONYM privilege. So, I dont have CREATE TABLE privilege for USER schema and unable to create "flyway_schema_history" in USER schema and hence unable to execute repeatable synonym script in user schema.

Is there any solution for this?

The synonym repeatable migration should only be executed in USER schema.

###### What did you expect to see?

Run repeatable migration in USER schema without need to create "flyway_schema_history"

###### What did you see instead?
BUILD FAILURE indicating, flyway is unable to find "flyway_schema_history"

**Comment by MikielAgutu** [comment]
Flyway requires a schema history table in order to run migrations. Maintaining an audit trail of migrations is an important principle of Flyway's design.

With that in mind, Flyway should support your use case. It can be done by setting the `schemas` property to `OWNER, USER`. The order matters, because the first schema in that list is the one where the schema history table is created. In your migration script, change to the `USER` schema. The migration will be recorded in the schema history table in `OWNER`, but the migration will be run by `USER`.

[See the docs for reference](https://flywaydb.org/documentation/configfiles).

Does that help?

**Comment by sdchhabaria** [comment]
Thanks for your response.

Can you please elaborate on "In your migration script, change to the USER schema."

What I have already tried is
flyway.schemas=<<OWNER>>,<<USER>>

it tries to execute the script in OWNER schema and fails, which I dont want.

I just want that script to get executed in USER schema

**Comment by MikielAgutu** [comment]
You can use `SET SCHEMA` in your migration scripts. See the [Oracle docs](https://docs.oracle.com/cd/B28359_01/server.111/b28310/general009.htm#ADMIN02101):

`ALTER SESSION SET CURRENT_SCHEMA = <schema name>`

**Comment by sdchhabaria** [comment]
Thanks a lot!! It worked :)
