### ISSUE TITLE
Create function Error 

### ISSUE THREAD

**Issue by farouqBenarous** [flyway/flyway#2848]
###### Which version and edition of Flyway are you using?
6.4.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes it is 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Mvn 3.6.3 , java 8

###### Which database are you using (type & version)?
posgresql 10

###### Which operating system are you using?
mac os 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**My migration script has functions creation they work fine when executed in database console but they fail in the migration execution** 

```
CREATE OR REPLACE FUNCTION is_tenant_present(tenant_name character varying) returns integer
	language plpgsql
as $$
BEGIN
    IF EXISTS (SELECT * FROM tenant WHERE name = tenant_name) THEN
        RETURN 0;
    END IF;
    RETURN 1;
END
$$;

```

###### What did you expect to see?
creation of function 

###### What did you see instead?
` ERROR: syntax error at or near "$$;
`

**Comment by MikielAgutu** [comment]
I'm unable to reproduce this. Could you share the migration file that's causing the problem?

**Comment by faroukcr7** [comment]
the example is above when u execute that creation of function u get an error

**Comment by MikielAgutu** [comment]
Sorry I wasn't clear. I've tried running that script in a Flyway migration and it seems to work. I need more information about what the problem could be. I'm asking if you could share the actual migration script file that is causing the problem, not just the script contents. Sometimes the file itself can cause problems due to encoding and things like that.

It's also possible that this script fragment isn't enough to reproduce the issue. It could be that the problem only occurs in the context of the entire script.

Could you attach the entire problematic script file?

**Comment by faroukcr7** [comment]
https://drive.google.com/file/d/1xf6cTW-l_ALRN-Y-WO30FRkehCUERss0/view?usp=sharing

here's the file

**Comment by Pharbi** [comment]
For future readers, this issue may be related to how the JDBI script parser works. When attempting to execute statements that have a `BEGIN...END` clause. Related to this [github issue](https://github.com/jdbi/jdbi/issues/2554)
