### ISSUE TITLE
flyway-maven-plugin not picking up properties injected by properties-maven-plugin

### ISSUE THREAD

**Issue by abhi2495** [flyway/flyway#2876]
I am trying to load the flyway properties from my application.yaml , but they dont seem to work.

I am trying to invoke the flyway clean goal, using the command:

```
mvn properties:read-project-properties flyway:clean
```
But getting the error:
```
org.flywaydb.core.api.FlywayException: Unable to connect to the database. Configure the url, user and password!
```

My POM.xml looks like this:

```
...
...
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>properties-maven-plugin</artifactId>
        <version>1.0.0</version>
        <executions>
          <execution>
            <phase>initialize</phase>
            <goals>
              <goal>read-project-properties</goal>
            </goals>
            <configuration>
              <files>
                <file>${project.basedir}/src/main/resources/application.yaml</file>
              </files>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-maven-plugin</artifactId>
        <version>6.5.0</version>
        <configuration>
          <url>${spring.datasource.url}</url>
          <user>${spring.datasource.username}</user>
          <password>${spring.datasource.password}</password>
        </configuration>
      </plugin>
...
...
```

My application yaml:

```
spring:
  datasource:
    url: jdbc:h2:mem:public;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;INIT=CREATE SCHEMA IF NOT EXISTS "public";
    username: root
    password:
```

_Originally posted by @abhi2495 in https://github.com/flyway/flyway/issues/679#issuecomment-657059494_

**Comment by abhi2495** [comment]
Hey @adelinor @axelfontaine @MikielAgutu @Lyeeedar @juliahayward, it's been more than a week now. Is anyone of you aware of this issue or know the solution? It would be great to receive a response from some of you.

**Comment by Lyeeedar** [comment]
The properties-maven-plugin seems to only support .properties files, not .yaml files. You you try it again using a .properties file like:

```
spring.datasource.url=your_url
spring.datasource.username=your_user
spring.datasource.password=your_password
```

**Comment by Lyeeedar** [comment]
Have you had a chance to try this with a .properties file?

**Comment by hamzaashfaq-10p** [comment]
I am still facing this issue , i am using application.properties but it is not picking up in pom.xml file.

**Comment by mtzagkarakis** [comment]
Any news on this one?

**Comment by MikielAgutu** [comment]
I'm not sure if this is a Flyway problem. If this `properties-maven-plugin` is working correctly, then in the configuration block:

```
<configuration>
  <url>${spring.datasource.url}</url>
  <user>${spring.datasource.username}</user>
  <password>${spring.datasource.password}</password>
</configuration>
```

The variables `${spring.datasource.url}` etc are injected just before the Maven build? At which point Flyway should pick them up, since at that point it's as if the values were hardcoded.

Maybe it's a bug due to some weirdness with the Maven build lifecycle? If that's the case, what can Flyway reasonably do? We read Maven config using the API that's provided.

Can you try putting in the values without the properties plugin (e.g. `<url>jdbc:h2:mem:public;DB_CLOSE_DELAY=-1;...</url>` and see if it works? That will confirm that this is a valid setup to begin with.

Also perhaps try using [Maven properties](https://flywaydb.org/documentation/usage/maven/#maven-properties) instead of configuration. So delete the `<configuration>` block, and your properties file says `flyway.url=your_url` and so on.

I'm not really sure what to suggest otherwise. Surely the idea of this properties plugin is to seamlessly integrate with existing processes? At which point, if Flyway works normally, surely the bug is in the properties plugin?

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity

**Comment by smlcodes** [comment]
@DoodleBobBuffPants @MikielAgutu  @Lyeeedar @mtzagkarakis @abhi2495 Is this fixed??? I'm still getting same issue. Can you please share resolution if it is fixed.

**Comment by stickfigure** [comment]
Just to fill in some background here since I did a deep dive (though I'm by no means a maven expert). It doesn't look possible. The `flyway:migrate` (or whatever) target isn't part of the normal lifecycle. The properties maven plugin binds to an early stage of the normal lifecycle but of course never gets called.

This seems to be the most relevant information on SO:

https://stackoverflow.com/questions/16264059/maven-bind-plugin-execution-to-the-execution-of-another-plugin-not-to-a-lifecy

If someone else wants to play with it, here's my test pom. 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>pomtest</artifactId>
	<version>1.0-SNAPSHOT</version>

	<dependencies>
		<dependency>
			<groupId>com.github.ekryd.echo-maven-plugin</groupId>
			<artifactId>echo-maven-plugin</artifactId>
			<version>2.1.0</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.codehaus.mojo</groupId>
			<artifactId>properties-maven-plugin</artifactId>
			<version>1.2.1</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-maven-plugin</artifactId>
			<version>10.13.0</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-plugin-api</artifactId>
			<version>3.9.4</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.maven.plugin-tools</groupId>
			<artifactId>maven-plugin-annotations</artifactId>
			<version>3.7.0</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>properties-maven-plugin</artifactId>
				<version>1.2.1</version>
				<executions>
					<execution>
						<id>normal</id>
						<phase>initialize</phase>
						<goals>
							<goal>read-project-properties</goal>
						</goals>
						<configuration>
							<files>
								<file>readthis.properties</file>
							</files>
						</configuration>
					</execution>

					<execution>
						<id>migrate</id>
						<phase>pre-integration-test</phase>
						<goals>
							<goal>read-project-properties</goal>
						</goals>
						<configuration>
							<files>
								<file>readthis.properties</file>
							</files>
						</configuration>
					</execution>

				</executions>
			</plugin>

			<plugin>
				<groupId>com.github.ekryd.echo-maven-plugin</groupId>
				<artifactId>echo-maven-plugin</artifactId>
				<version>2.1.0</version>
				<inherited>false</inherited>
				<configuration>
					<message>database.url is ${database.url}</message>
				</configuration>
				<executions>
					<execution>
						<id>welcome</id>
						<goals>
							<goal>echo</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

 			<plugin>
				<groupId>org.flywaydb</groupId>
				<artifactId>flyway-maven-plugin</artifactId>
				<version>10.13.0</version>
				<configuration>
					<url>${database.url}</url>
					<user>${database.user}</user>
					<password>${database.password}</password>
					<outOfOrder>false</outOfOrder>

					<locations>
						<location>filesystem:db/migration</location>
					</locations>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.flywaydb</groupId>
						<artifactId>flyway-database-postgresql</artifactId>
						<version>10.13.0</version>
					</dependency>
				</dependencies>
			</plugin>
 		</plugins>
	</build>
</project>
```

If you try this out, you'll notice that the echo-maven-plugin gets the value right if you run `mvn package` or one of the other normal lifecycle targets. It does not work if you run `mvn echo:echo`.

I'm switching to Gradle.
