### ISSUE TITLE
the best practice when executed sql script against test enviroment need to update?

### ISSUE THREAD

**Issue by zhouwenyang** [flyway/flyway#2929]
Hi guys, i have a question about when a sql scripts execute successful against  test environment and have been recorded into flyway_schema_history table, but the developer or tester find something wrong with the sql scripts. they need to update or fix the sql scripts. what is the best practice to do it. we can not create a new version of sql scripts, because we don't want run the older version against production, it may break something.

so we need to update the sql scripts directly. but the thing is when I update the sql scripts , flyway will check the checksum of files, it will failed in the next execution. so what i have to do now is that:

1. Fix sql scripts on the old version directly.
2.Run "flyway repair" to generate new checksum value.

it means every time I need to fix or update sql scripts, i need do repair first. 
so i want to know how you guys do this?

**Comment by juliahayward** [comment]
Hi! Updating the script and using `repair` to fix the checksums is the simplest and best way to do it. The only issue might be that you haven't actually run the script in its final form against the test environment, and that may be problematic for you if the changes made are risky.

You could also try:
- write an undo script for each migration; if your script needs a fix then `flyway undo` to back it out and then `flyway migrate` again after you have fixed the script, or

- take a database backup before the migration; if your script needs a fix then restore the backup and then migrate again after you have fixed the script (warning: only for environments where you don't mind data changes since the migration being lost).

**Comment by zhouwenyang** [comment]
@juliahayward yeah the problem is that when I fixed the sql scripts and run flyway migrate again.
it will not run the fixed scripts against test env. i have to do it manually.

for undo and backup, it's too complex for us. i wonder is there something that like R__ I can rerun the fixed sql scripts against test env when the V__ scripts updated.

**Comment by juliahayward** [comment]
That's a workable idea - turn the problematic V-script into an R-script while you're working on it, and then rename it back when you're ready to commit. This would require that you make the script idempotent (for example `CREATE TABLE foo` would have to be preceded by `DROP TABLE IF EXISTS foo`) but that's not a bad thing in itself; plus you'd need a certain amount of care not to introduce more V-scripts as the sequencing would potentially be wrong.
