### ISSUE TITLE
Migration form Version 3.2 to 7.0

### ISSUE THREAD

**Issue by sanketh-shetty-incontact** [flyway/flyway#2951]
###### Which version and edition of Flyway are you using?
3.2

Problem Statement
We want to use the capability added in V7.0 to use S3 bucket to have the script files.

I know we cannot migrate directly from 3.2 to 7.

Can you please guide how we go about with the migration from 3.2 to latest version?

**Comment by juliahayward** [comment]
The only supported path is to migrate from 3.2 to 4.x, then 5.x, 6.x, 7.0; so install each version in turn and run at least one command (so that the history table is updated to the newer version).

As this is likely to be quite tedious, an alternative might be to remove the schema history table, upgrade to v7, baseline at the appropriate version and continue. This obviously loses past Flyway history, which will probably not be acceptable to you.
