### ISSUE TITLE
Flyway 4.2.0 Deployment MSSQL - connection reset by peer: socket write error

### ISSUE THREAD

**Issue by Tech-Med7** [flyway/flyway#3011]
###### Which version and edition of Flyway are you using?

4.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

The deployments were working fine with this version . 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven Plugin

###### Which database are you using (type & version)?

MSSQL 2012

###### Which operating system are you using?

Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

We are trying to deploy some DB objects (stored procs etc) and the deployment fails random with the connection reset by peer error. the objects deployed successfully manually and the issues not specific to any object.

###### What did you expect to see?

Objects are deployed fine

###### What did you see instead?

[ERROR] SQL State : 08S01
[ERROR] Error Code : 0
[ERROR] Message : Connection reset by peer: socket write error

**Comment by DoodleBobBuffPants** [comment]
Hi. As we don't directly modify existing Flyway releases, this is likely to be an environmental issue. Some things you could try:

- Check if your database driver has recently been updated and if this is the cause
- Check if any network settings have changed that are causing connections on certain sockets to be dropped
- Try connecting via JDBC outside of Flyway - this will identify whether the problem lies within Flyway

Here is a [stack overflow](https://stackoverflow.com/questions/1573315/connection-reset-by-peer-error) post that may help, and one from [stack exchange](https://dba.stackexchange.com/questions/108485/connection-reset-by-peer-socket-write-error)

You may also try a different version of Flyway to see if it is a subtle error that has been fixed in a later version

**Comment by Tech-Med7** [comment]
> Hi. As we don't directly modify existing Flyway releases, this is likely to be an environmental issue. Some things you could try:
> 
> * Check if your database driver has recently been updated and if this is the cause
> * Check if any network settings have changed that are causing connections on certain sockets to be dropped
> * Try connecting via JDBC outside of Flyway - this will identify whether the problem lies within Flyway
> 
> Here is a [stack overflow](https://stackoverflow.com/questions/1573315/connection-reset-by-peer-error) post that may help, and one from [stack exchange](https://dba.stackexchange.com/questions/108485/connection-reset-by-peer-socket-write-error)
> 
> You may also try a different version of Flyway to see if it is a subtle error that has been fixed in a later version

We are kind of isolating the issue to the windows agents used for running flyway. we ran it from a Linux agent and it is deploying fine . Probably some security patch . Thanks much for the feedback . Will update the group once I have more details ..

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
