### ISSUE TITLE
Flyway cannot resolve repeatable migrations on 7.2.1

### ISSUE THREAD

**Issue by HendrikJanssen** [flyway/flyway#3012]
###### Which version and edition of Flyway are you using?
Flyway 7.2.1 Community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API (Autoconfigure from Spring boot)

###### Which database are you using (type & version)?

Postgresql 10.2

###### Which operating system are you using?

Docker (I dont know which base image the spring boot buildpack uses)

###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

We have a very small and easy configuration - we use 3 folders under our Base `db` folder in the `resources` folder:

- migration
- testdata
- production

We configure which folders are included in our stages (master, preview, production) via springs profiles and the `spring.flyway.locations` config setting.

So for master, the config would look like:

`spring.flyway.locations=classpath:/db/migration,classpath:/db/testdata`

for production it would look like

`spring.flyway.locations=classpath:/db/migration,classpath:/db/production`

Additonally, we use the `${flyway:timestamp}` feature to always re-run our Repeatable migrations in the `testdata`folder.

We have upgraded now from Flyway 6.5.7 to 7.2.1 and the deployment fails.

###### What did you expect to see?

A succesfull migration.

###### What did you see instead?

`Detected applied migration not resolved locally: sample user en harry. If you removed this migration intentionally, run repair to mark the migration as deleted.`

We clean our database on the master env (Which comes before the preview env), so i guess that is why we havent noticed the problem before. However, it has worked before with 6.5.7 (For several years now), we have literally changed nothing in our setup, no new migrations, no changed repeatable migrations, it is kinda weird. Are we doing something we should not do here?

Locally, it finds the migrations. If we build our docker image and push it to master, it finds the repeatable migrations and applies them, so we are pretty sure they are on our classpath.

If you need more information let me know and thanks in advance!

**Comment by DoodleBobBuffPants** [comment]
In Flyway V7 we introduced several breaking changes. It may be worth going through our [release notes](https://flywaydb.org/documentation/learnmore/releaseNotes) in order to identify what may apply to you

In your case it is the addition of being able to [delete repeatable migrations](https://flywaydb.org/blog/flyway-7.0.0-beta#delete-repeatable-migrations) which is causing this validation error. Before, missing migrations were accepted but now they lead to this error. In order to retain old behaviour you need to set [`ignoreMissingMigrations`](https://flywaydb.org/documentation/configuration/parameters/ignoreMissingMigrations) to `true`
