### ISSUE TITLE
Feature : Need to disable transaction mode globally not only per sql script file

### ISSUE THREAD

**Issue by JeanFrancoeur** [flyway/flyway#3042]
Using Community command line version of Flyway 7.4.0 with Windows 10 Pro 1703 & Sql Server 2017

Hi! We already have this functionnality per sql script and it works very well.
But adding a .conf for each sql script to a large number of sql files this add too much noise.

There's any way to add executeInTransaction=false globally?

Thank you in advance

**Comment by DoodleBobBuffPants** [comment]
Hi. There isn't currently any option to do this globally

If the pain comes from creating each script config file, you could perhaps automate it for all of your `.sql` files by grabbing their name, let's call it `script`, and creating a new file `script + ".conf"` and writing `executeInTransaction=false` to these

I'll leave this open to see if it gets further interest for now since it's already achievable on a per script basis

**Comment by JeanFrancoeur** [comment]
Hi! It's exactly what I'm talking about.  Here we have not some scripts, but some thousand of them. It's why I ask for a global option and tagged it like a feature. But I can understand that we cannot do each wish and maybe it's not a need for all.

**Comment by MikielAgutu** [comment]
@JeanFrancoeur Flyway has a mechanism to detect non-transactional statements, and exclude them from transactions. Ideally we'd prefer users to rely on this detection logic rather than turning off transactions completely.

The script config option was introduced as a stop-gap to unblock users if non-transactional cases are discovered which Flyway doesn't currently cover.

Can you share more about why you need this feature? Have you come across many non-transactional statements in your scripts?

**Comment by JeanFrancoeur** [comment]
@MikielAgutu We have more than 5000 scripts to run to see if Flyway or your competitor beginning with L or a custom tool is better, more stable or faster. Actually using transaction mode is too slow. And we got some non-transactional errors too. We didn't investigate each, it was quicker to add .conf until now. Because we can't configure the non-transaction keywords dynamically, we have used the per script way. But restarting each time the whole thing is time consuming. We need to be able to see a complete run result in one pass and compare it against the other methods.

**Comment by MikielAgutu** [comment]
Thanks for the extra information. If I understand correctly, you're unblocked for the time being - albeit with a workaround that admittedly isn't ideal?

We'll consider adding a 'disable transactions' flag, but again we'd rather build in this understanding to Flyway itself. If you could provide any non-transactional examples that would be helpful.

I'll keep the issue open to see if others have this problem.

**Comment by JeanFrancoeur** [comment]
@MikielAgutu Yes, the workaround give me the opportunity the get forward, but I'm still getting some hurdles, so I can't give you all the non-trasactional missing tags for now.  I can't understand this one.  Please note that the script is executed with the non-transactional .conf file with executeInTransaction=false like all others.  I understand that the sys.sp_fulltext_database cannot be executed in transaction mode under mssql, but the current sql script only contains an EXEC command against a storedproc, nothing more.  What I'm missing here?

Migrating schema [dbo] to version "7.3.3.30.000230 - C991 RebuildFullTextSearch" [non-transactional]
ERROR: Migration of schema [dbo] to version "7.3.3.30.000230 - C991 RebuildFullTextSearch" [non-transactional] failed! Please restore backups and roll back database and code!
ERROR:
Migration C7.3.3.30.000230_C991_RebuildFullTextSearch.sql failed
----------------------------------------------------------------
SQL State  : S0001
Error Code : 15002
Message    : The procedure 'sys.sp_fulltext_database' cannot be executed within a transaction.

Note: I've been able to run all the same scripts with mssql command line runners and with another engine.

Thank you in advance for your help

**Comment by DoodleBobBuffPants** [comment]
Regarding the warning you are seeing, this is a result of `PRINT` statements, and you can read about how to handle these in our docs for [error overrides](https://flywaydb.org/documentation/concepts/erroroverrides#example-2-display-sql-server-print-messages-as-simple-info-messages). Other than that, if there was no error then execution is successful

Regarding the error in your first case, would you be able to isolate this to a single script or a couple of scripts that cause this when executed together? It might be a result of making all of your migrations execute without a transaction when some actually require a transaction, and having the scripts would help us figure out what the issue is

**Comment by JeanFrancoeur** [comment]
Thank you @DoodleBobBuffPants for your answer.  I know & already tried the error overrides, it works very well but it's a no-go for us, because it's a Teams only feature.

Because our current poc is very complex, it's not easy to investigate and isolate each case.

As previously discussed, @MikielAgutu here's 2 identified commands that cannot be run inside a transaction, they are missing from SQLServerParser:
sp_addsrvrolemember
sp_change_users_login

**Comment by DoodleBobBuffPants** [comment]
Thanks for letting us know. We'll keep this open as a reference to add these sprocs to our parser

**Comment by JeanFrancoeur** [comment]
@DoodleBobBuffPants I did a quick test for our non-transactional case (C7.3.3.30.000230_C991_RebuildFullTextSearch.sql) I simply copied the content of the sproc directly inside the script file and the execution was successfull.  I will try to isolate this case into a smaller poc to see if we got a problem related to the BlockDepth detection.  I thought if the script has a .conf file everything executed from that point was not transactional, but it seems not to be the case.

**Comment by JeanFrancoeur** [comment]
I don't know if it's a good idea to add a new comment here because it's closed, but it's directly linked.  Thank you for adding support for SP_FULLTEXT_DATABASE into the SPROCS_INVALID_IN_TRANSACTIONS in v7.5.2, but you forgot to add the 2 others listed in this issue: _"SP_CHANGE_USERS_LOGIN", "SP_ADDSRVROLEMEMBER"_.  I made great execution progress.  I found that some file extensions were .SQL and I didn't find anywhere the mention that the filename extension is case sensitive.  Windows is not case-sensitive and finding them (only a few) was very painfull inside 5000+ scripts. For reference, I'm using this config : _flyway.locations=filesystem:./sql/**/Sql/M*.*_. Can you add this very important information somewhere like by adding this case here : https://www.red-gate.com/blog/database-devops/flyway-naming-patterns-matter?  I made my snapshot from 7.5.2.  Actually, even if the parser contains SP_FULLTEXT_DATABASE and SP_INDEXOPTION (a new one), it seems that an EXEC SPROC and EXEC sp_executesql @sql hide non-transactional keywords and it's not possible to grab them.  I'm still getting _"The procedure 'sp_xyz' cannot be executed within a transaction"_.  To be able to complete the migration, I need to create a .conf file for each script.  By the way, I don't know if it can makes any difference, but I'm using _migrate_ with the _-target_ parameter.

**Comment by DoodleBobBuffPants** [comment]
Those other 2 sprocs can be executed in transactions and don't need `executeInTransaction=false`. As per their docs, it's only user-defined transactions they cannot be executed in, so we cannot reliably add them to our auto-detection logic

Our official documentation does say that the file suffix should be `.sql` (lowercase). You can specify the migration suffixes to [`sqlMigrationSuffixes`](https://flywaydb.org/documentation/configuration/parameters/sqlMigrationSuffixes), so perhaps providing both the lowercase and uppercase suffix here could help

**Comment by JeanFrancoeur** [comment]
@DoodleBobBuffPants My bad, the default extension was effectively in lower case. Yes you are right, the 2 other SPROCS was a side effect.  Now about the embedded non-transactional issue, I made a little poc.  
[TestEmbededNT.zip](https://github.com/flyway/flyway/files/5904644/TestEmbededNT.zip)

You will find the sql scripts and the sproc.  When doing the migration, the first script is successful with the automatic non-transational detection.  but the second one calling the same sql inside a sproc fail.

Successfully validated 3 migrations (execution time 00:00.037s)
Current version of schema [dbo]: 1
Migrating schema [dbo] to version "002 - TestNT" [non-transactional]
Migrating schema [dbo] to version "003 - ExecEmbeddedNT"
ERROR: Migration of schema [dbo] to version "003 - ExecEmbeddedNT" failed! Changes successfully rolled back.
ERROR:
Migration C003_ExecEmbeddedNT.sql failed
----------------------------------------
SQL State  : S0001
Error Code : 15002
Message    : The procedure 'sys.sp_serveroption' cannot be executed within a transaction.
Location   : .\testsql\C003_ExecEmbeddedNT.sql (D:\flyway\flyway-7.5.0 - Copy\.\testsql\C003_ExecEmbeddedNT.sql)
Line       : 1
Statement  : EXEC [TestEmbeddedNT]

I hope you can find why I'm getting the strange behavior.

**Comment by DoodleBobBuffPants** [comment]
This is actually expected behavior. Our auto-detection logic is based off of the contents of your SQL. In the first case we can see the call to the non-transactional sproc, but in the second case, all we have access to is a call to your own sproc, so we cannot auto-detect the non-transactional sproc being used, and in this case you would have to set `executeInTransaction=false`

**Comment by JeanFrancoeur** [comment]
Ok noted, thank you.  Including an sp_execute_sql containing a non-transactional command like this?

DECLARE @sql NVARCHAR(MAX), @tabName VARCHAR(50), @ndxName VARCHAR(50)
DECLARE cur_indexName CURSOR FOR
  SELECT t.name,i.name
   FROM sys.indexes i
    INNER JOIN sys.tables t ON t.object_id = i.object_id
  WHERE Allow_Row_Locks = 0 OR Allow_page_Locks = 0

OPEN cur_indexName
FETCH cur_indexName INTO @tabName, @ndxName
WHILE @@FETCH_STATUS = 0 
begin
  SET @sql = 'exec sp_indexoption ''' + @tabName + '.' + @ndxName +''', '+ '''AllowRowLocks'''+ ', TRUE'
  --PRINT @sql
  EXEC sp_executesql @sql
  SET @sql = 'exec sp_indexoption ''' + @tabName + '.' + @ndxName +''', '+ '''AllowPageLocks'''+ ', TRUE'
  --PRINT @sql
  EXEC sp_executesql @sql
  FETCH cur_indexName INTO @tabName, @ndxName
END
CLOSE cur_indexName
DEALLOCATE cur_indexName

**Comment by tussosedan** [comment]
Jumping in here to say that we would also like to have a global flag like this, since we're running complex scripts of data changes that have internal transaction management in batches to avoid the long locks of a big transaction. It would be great to be able to tell flyway "hey, don't worry, we're adding transactions where needed" globally, without creating conf files per migration. Thanks!
