### ISSUE TITLE
Unable to execute flyway against Snowflake DB

### ISSUE THREAD

**Issue by asmalls911** [flyway/flyway#3065]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 7.5.1 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
commandline client

###### Which database are you using? (Type & version)
Snowflake Standard edition (5.1)

###### Which operating system are you using?
Linux 0c10d7a194d9 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64 Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Using the flyway/flyway:7.5.1-alpine  (also exists on 7.5.2-alpine)...

Created a new dockerfile to create the image in order to use flyway from the command line

```
#Dockerfile
# Credit: https://www.joaorosa.io/2019/01/13/using-flyway-and-gitlab-to-deploy-a-mysql-database-to-aws-rds-securely/

FROM flyway/flyway:7.5.1-alpine


USER root
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apk add ca-certificates

ENV JAVA_ARGS=-Djava.security.egd=file:/dev/../dev/urandom -Djavax.net.ssl.trustStore=$JAVA_HOME/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=$STORE_PASS

USER flyway
ENTRYPOINT ["/usr/bin/env"]
```

```
flyway.conf file
# Fully qualified classname of the jdbc driver (autodetected by default
# based on flyway.url)
flyway.driver=net.snowflake.client.jdbc.SnowflakeDriver
# Jdbc url to use to connect to the database
flyway.url=jdbc:snowflake://account.us-east-1.snowflakecomputing.com/?db=flyway&warehouse=warehouse&role=flyway&schema=FLYWAY
flyway.user=panto_sys_dev
flyway.locations=filesystem:sql/snowflake,filesystem:sql/dev/snowflake
flyway.defaultSchema=FLYWAY
flyway.schemas=FLYWAY
flyway.password=*****************
```
After building docker image flyway appears to be running normally.  However when connecting to the snowflake database I received the following error:
```
ERROR: 
Unable to determine the original schema for the connection
----------------------------------------------------------
SQL State  : XX000
Error Code : 200001
Message    : JDBC driver internal error: Fail to retrieve row count for first arrow chunk: null.

Caused by: net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver internal error: Fail to retrieve row count for first arrow chunk: null.
```

Testing using the Sample JDBC Driver here works as expected: 
###### What did you expect to see?
I expected to be able to connect to the snowflake database.  my user, schema, warehouse, database and password are all configured, as well as default role, schema and warehouse in snowflake.

###### What did you see instead?

Instead, above error was printed.  

Should be noted, running the flyway/flyway docker container worked as expected (though not the way I'd like to use this container)

**Comment by DoodleBobBuffPants** [comment]
Since the official Flyway image works, and the error is coming from the Snowflake driver, there's not much we can do

However, a few things for you to try:
- Has this image ever worked before Flyway 7.5.1? We updated the version of openjdk we use in 7.5.1, so that may have made a difference
- Your dockerfile is missing some steps compared to what's in the credited post. You don't seem to be invoking `keytool` to add a certificate to Java's certificate store. Presumably you're setting the `STORE_PASS` some other way too?
-  You've added `ca-certificates` but not used it. More information on it is [here](https://hackernoon.com/alpine-docker-image-with-secured-communication-ssl-tls-go-restful-api-128eb6b54f1f)

Hopefully the above helps you complete your dockerfile

Closing as there isn't anything we can do in Flyway

**Comment by asmalls911** [comment]
Thanks for the reply. I didn't need the certs for rds so I didn't add them.
The question I have here, is why does the same docker container work from
the original container, but not when I drop into the console?  I think this
is required to integrate with gitlab ci.

**Comment by DoodleBobBuffPants** [comment]
By dropping into console are you referring to overriding the `ENTRYPOINT`?

If so, our container defines flyway as the entrypoint, meaning you can just execute `docker run --rm flyway/flyway info` without specifying `flyway` before `info`. Since you change the entrypoint, you would need to specify `docker run --rm flyway/flyway flyway info`

**Comment by asmalls911** [comment]
I'm integrating with gitlab, so the requirement from gitlab is that I drop
into a shell, and execute a script.  This is what's not working.  What's
interesting is that it's the jdbc call that fails when I do it this.  The
same operation without using the flyway shell does not work.  I appreciate
your responses, but I'd really like to figure out why this doesn't work
when I change the entry point.  Any suggestions you have would be
appreciated.  It doesn't seem to be a certificate issue, since I can see
flyway executing commands in snowflake, and commands that are executed are
the same.   The problem is that the response from snowflake causes a
org.flywaydb.core.internal.exception.FlywaySqlException when I run from the
command line but does not when I use the same version of the container
without changing ENTRYPOINT.



Please reopen/advise.


Aaron Smalls
aaron.smalls@gmail.com


"Without ambition one starts nothing. Without work one finishes nothing.
The prize will not be sent to you. As to methods there may be a million and
then some, but the principles are few. The man who grasps principles can
successfully select his own methods. The man who tries methods, ignoring
principles, is sure to have trouble."

     -- Ralph Waldo Emerson

**Comment by DoodleBobBuffPants** [comment]
While I haven't been able to figure out why setting `ENTRYPOINT` to `/usr/bin/env` is being problematic like this, you should be able to set the `ENTRYPOINT` to empty as in [this](https://findingpaths.io/blog/validating-flyway-schema-definitions-with-gitlab-cicd/) post in order to run in gitlab. We had a similar need in Azure pipelines, resulting in [this](https://github.com/flyway/flyway-docker/blob/master/flyway-azure/alpine/Dockerfile) dockerfile. Perhaps this dockerfile would also work in gitlab?

**Comment by DoodleBobBuffPants** [comment]
If it still doesn't work, [here](https://nickjanetakis.com/blog/fixing-exec-format-errors-with-docker-entrypoint-scripts-on-windows)'s an interesting post explaining how line endings could cause weird behavior, and it suggests some useful things to try, such as manually connecting to the container and executing flyway from a terminal inside the container

**Comment by asmalls911** [comment]
I'm not sure how this helps.

I can run the container and the flyway command when setting the entry
point. (And when setting entrypoint to nothing).  The problem is the exact
same flyway command the runs from the container without the entrypoint,
fails when run from the terminal inside the docker container.  As far as I
can tell, everything else is the same, drivers, flyway version, etc.



Aaron Smalls
aaron.smalls@gmail.com


"Without ambition one starts nothing. Without work one finishes nothing.
The prize will not be sent to you. As to methods there may be a million and
then some, but the principles are few. The man who grasps principles can
successfully select his own methods. The man who tries methods, ignoring
principles, is sure to have trouble."

     -- Ralph Waldo Emerson

**Comment by DoodleBobBuffPants** [comment]
I have tried your exact dockerfile above on several database engines and been unable to reproduce any kind of failure

Can you confirm if this is only happening in Snowflake or does it happen in other databases too? PostgreSQL and H2 in-mem databases are quick and easy to test against

Could you also provide exact steps and necessary resources to reproduce this?

**Comment by asmalls911** [comment]
1.) The following command using the default container unmodified works as
expected:

`docker run --rm -v
/Users/asmalls/dev/projects/panto/platform/deploy/db/flyway/conf/:/flyway/conf
-v
/Users/asmalls/dev/projects/panto/platform/deploy/db/flyway/sql/:/flyway/sql
 flyway/flyway -configFiles=conf/snowflakedev.conf info
-password=${FLYWAY_PASSWORD} -X`


2.) Using the same container with the following .gitlab-cy.yml
configuration yields the following.

.migrate_snowflake_template: &migrate_snowflake_definition
  image:
    name: ${REPOSITORY_URL}/${REPOSITORY_NAME}:flyway-latest-alpine
    entrypoint: [""]
  stage: migrate-snowflake
  script:
    - export FLYWAY_PASSWORD=${PASSWORD}
    - flyway info
-configFiles=${CI_PROJECT_DIR}/db/flyway/conf/snowflake${PANTO_ENV_KEY}.conf
    - flyway migrate
-configFiles=${CI_PROJECT_DIR}/db/flyway/conf/snowflake${PANTO_ENV_KEY}.conf
-locations=filesystem:${CI_PROJECT_DIR}/db/flyway/sql/snowflake,filesystem:${CI_PROJECT_DIR}/db/flyway/sql/${PANTO_ENV_KEY}/snowflake
-X
    - flyway info
-configFiles=${CI_PROJECT_DIR}/db/flyway/conf/snowflake${PANTO_ENV_KEY}.conf

I have removed my manually created docker image (unneeded). The image
referenced above is a copy

Here's the result from gitlab.
Flyway Community Edition 7.5.1 by Redgate
ERROR: Skipping filesystem location:sql/dev/snowflake (not found).
ERROR: Skipping filesystem location:sql/snowflake (not found).
Database: jdbc:snowflake://eabpantodev.us-east-1.snowflakecomputing.com:443/
(Snowflake 5.2)
ERROR:
Unable to determine the original schema for the connection
----------------------------------------------------------
SQL State : XX000
Error Code : 200001
Message : JDBC driver internal error: Fail to retrieve row count for first
arrow chunk: null.
Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver
internal error: Fail to retrieve row count for first arrow chunk: null.
ERROR: Job failed: exit code 1


The same error occurs when running outside of gitlab with the following
Dockerfile:

FROM flyway/flyway:latest-alpine

LABEL maintainers="Aaron Smalls <asmalls@eab.com>"

USER root

RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

RUN update-ca-certificates

ENV PATH=/flyway:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

USER flyway
ENTRYPOINT [""]


This only occurs for snowflake, existing postgres db does not have this
issue.  What I want to understand, is why there is different behavior based
on the entry point? Clearly this can work with snowflake.  But there seems
to be something I'm missing when changing entrypoint.


Aaron Smalls
aaron.smalls@gmail.com


"Without ambition one starts nothing. Without work one finishes nothing.
The prize will not be sent to you. As to methods there may be a million and
then some, but the principles are few. The man who grasps principles can
successfully select his own methods. The man who tries methods, ignoring
principles, is sure to have trouble."

     -- Ralph Waldo Emerson

**Comment by DoodleBobBuffPants** [comment]
Thanks for your patience, I have managed to reproduce this now

The problem stems from when we upgraded the version of openjdk used in our docker image, and this seems to be causing some incompatibility with the snowflake driver which causes it to return null and fail when we try to determine the schema

This isn't something we can revert, since we upgraded the version of openjdk due to a vulnerability

If all you require is an unset entrypoint, then our azure image (`flyway/flyway-azure:latest-alpine`) should work fine for you as it worked in our tests, otherwise your next step would be to raise an issue in the [snowflake driver's repo](https://github.com/snowflakedb/snowflake-jdbc) asking them to look into why openjdk-16 fails when openjdk-12 doesn't

**Comment by asmalls911** [comment]
Thanks.  I think that makes sense to me.  The only remaining question is
why the entrypoint matters.  Is it because the jdk version is different
based on entrypoint?

I tried my same configuration with the azure image, but it fails for a
different reason:
Flyway Community Edition 5.2.4 by Boxfuse
Database: jdbc:snowflake://eabpantodev.us-east-1.snowflakecomputing.com:443/
(Snowflake 5.3)
ERROR: Unsupported Database: Snowflake 5.3


Thanks for your responses here.  I will file bug reports with snowflake.
As an aside, are there plans to support the latest version of snowflake in
flyway?

**Comment by DoodleBobBuffPants** [comment]
> Is it because the jdk version is different based on entrypoint?

It isn't, so there might be some environmental difference about the way commands are processed which causes an issue in version 16 and not 12

> Flyway Community Edition 5.2.4 by Boxfuse

This indicates that you are using an old version of Flyway where Snowflake isn't supported. Can you double check that you are using the right flyway-azure image? The image is `flyway/flyway-azure:latest-alpine`

> As an aside, are there plans to support the latest version of snowflake in flyway?

In the latest version of Flyway, Snowflake 5.3 will produce a warning instead of an error, and this warning will go away after we have tested support. You are welcome to create a separate issue asking us to support 5.3 so that you can track it

**Comment by asmalls911** [comment]
After looking again I realized that flyway/flyway-azure:latest-alpine was
not 7.5.2.  Pulling the correct image resolves this issue.

Thank you!

>
