### ISSUE TITLE
Feature request - Multiple datasources

### ISSUE THREAD

**Issue by prashanth-92** [flyway/flyway#3069]
###### Which version and edition of Flyway are you using?
Flyway maven plugin 7.5.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)
Postgres SQL

###### Which operating system are you using?
Mac OS X Big Sur

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I am trying to incorporate flyway for my team to rollout database changes, but I came across a road block when I needed to roll out the same database changes for multiple shards. I see a workaround for this by explicitly using the flyway java API `migrate()` method multiple time configuring one shard at a time, but is there a plan to support multiple datasources any time in the future out of the box?

P.S: I was looking into the source code of flyway in Github and it seems inherently built on the fact of a single data source and it might need a fundamental change.

###### What did you expect to see?
N/A

###### What did you see instead?
N/A

**Comment by DoodleBobBuffPants** [comment]
This is closely related to the idea of executing migrations against multiple schemas, for which there is a general issue open (https://github.com/flyway/flyway/issues/2995). For schemas, we currently mention in our [FAQs](https://flywaydb.org/documentation/learnmore/faq#multiple-schemas) and in [this blog post](https://flywaydb.org/blog/multipleschemas) that you would need to iterate over each schema and invoke Flyway, since Flyway is designed to operate on one schema at a time. In your case you would need to iterate over each datasource and invoke Flyway instead

Do feel free to thumbs up and leave your thoughts on the above mentioned issue, but closing this as this is really an extension of #2995
