### ISSUE TITLE
Running flyway clean prints "ERROR: Skipping filesystem location:sql (not found)." 

### ISSUE THREAD

**Issue by dbrennan** [flyway/flyway#3073]
###### Which version and edition of Flyway are you using?
7.5.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command Line

###### Which database are you using? (Type & version)
Postgres 11.5

###### Which operating system are you using?
Ubuntu 18.04

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Command like:
flyway -user=root -password=password -url=jdbc:postgresql://localhost/database clean

###### What did you expect to see?
No error message because the clean operation worked. 

###### What did you see instead?

ERROR: Skipping filesystem location:sql (not found).

There is no error in this case so this message should not be printed.

**Comment by DoodleBobBuffPants** [comment]
We log an error when any provided location is not found since it's important for these locations to be correct for your migrations. You can avoid this error by setting valid locations or clearing the locations parameter. We will consider not checking locations for `clean` since it isn't strictly required
