### ISSUE TITLE
Oracle SQLPLUS option calculates different checksums for migrations when ORACLE_HOME is set to a valid install.

### ISSUE THREAD

**Issue by Sam-Redgate** [flyway/flyway#3074]
###### Which version and edition of Flyway are you using?
7.5.0 Teams

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Tested against Oracle 12c and Oracle XE 18.

###### Which operating system are you using?
Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
When generating the schema history table, I used `migrate -skipExecutingMigrations=true` with `-oracle.sqlplus=true`. This generated the table fine.

However, I subsequently used `validate` _without_ `-oracle.sqlplus=true`. All repeatable migrations were showing as "Pending" and validate thought my versioned migration had changed. This was because all the checksums for all my migrations were being calculated differently from when I called `migrate`. The files had not changed.

After much investigation, it turns out this behaviour is only exhibited when my `ORACLE_HOME` is set to an Oracle DB installation. If I unset this variable, both Flyway `migrate` and `validate` calculate the same checksums, whether or not `oracle.sqlplus` is set.

###### What did you expect to see?
I would not expect the presence of `ORACLE_HOME` to change the calculated checksums of my local migrations.

###### What did you see instead?
Calculated checksums change if `oracle.sqlplus` is set and `ORACLE_HOME` points to a valid DB installation.

A workaround is to make sure `oracle.sqlplus` is always set (either via the command line or the config file) when invoking Flyway. However this is odd behaviour as I wouldn't expect this option to have a material affect on checksum calculation.

**Comment by DoodleBobBuffPants** [comment]
After trying several test scripts I was unable to reproduce this behavior. It's possible that you have a site profile which is affecting the contents of your scripts, since this is only loaded when `ORACLE_HOME` is set. These are `glogin.sql` files which we read in when `sqlplus` is enabled. You can read more about them in our docs [here](https://flywaydb.org/documentation/database/oracle#site-profiles-gloginsql--user-profiles-loginsql)

If you remove this site profile and try again, do you still run into the same problems?

**Comment by Sam-Redgate** [comment]
Indeed that seems to be the case, removing the `glogin.sql` script resolve things. So when using the SQLPLUS parser it reads in that SQL script too? Even though by default it's just comments, I guess that affects the content the parser sees and hence the checksum generated.

**Comment by DoodleBobBuffPants** [comment]
Yes that is correct. In the presence of `login.sql` and `glogin.sql` files it then becomes necessary to enable `oracle.sqlplus` for any command that handles checksums

Is this acceptable?

**Comment by Sam-Redgate** [comment]
Thanks @DoodleBobBuffPants , that's effectively what we've done in our app - setting `oracle.sqlplus` for migrate / info / validate / repair.

Will have to bear it in mind for the future!

**Comment by henkkelder** [comment]
I am the customer (developer) suffering from this issue.
I am having this problem with a **default** installation of Oracle 12c. I did not create a glogin.sql but it still does exists.

This also means that whenever the contents of the glogin.sql file changes really all of my RCC scripts are marked pending by RCC. I don't think that is a good idea. It is just too much 'hidden' and will cause more problems for many users.
The non-repeatable RCC scripts will also be marked changed and will result in unrecoverable errors in RCC since non-repeatables should not change..

I would really suggest NOT including (g)login.sql while running the scripts since it introduces something that appears nice (doing things automatically), but reduces the flexibility one has a s a developer. For me this behaviour is totally unexpected and the fact that even Sam is unaware of this proves my point. Alternatively make it optional with a config option; 

I would also suggest not including the content of the login scripts in de checksums to avoid "total recall" when the login scripts are changed.

**Comment by Sam-Redgate** [comment]
I agree with @henkkelder that this behaviour was both surprising and subsequently difficult to discover.

However, I think Flyway's doing the right thing here. If the user is instructing Flyway to use the SQL*PLUS parser then I think it's not up to Flyway to modify that parser's default behaviour, as described in the Oracle documentation : https://docs.oracle.com/cd/E11882_01/server.112/e16604/ch_two.htm#i1133044

The fact that Flyway _doesn't_ ignore such sql scripts from its checksums, when they can materially affect the migrations as they are applied to your database, is probably a good thing, as it can lead to even more surprising (and potentially dangerous) behaviour where your migrations as applied to your database are different to those in your local files, without the user first understanding why or how such a situation can occur.

What I think could be improved is the reporting - maybe to warn users about `ORACLE_HOME` when calculating checksums with `-oracle.sqlplus=true` with a pointer to the docs? Or something a bit more sophisticated.

There are a couple things we can do from RCC's side to remedy this for users.

**Comment by henkkelder** [comment]
In my scenario I installed RCC before I had a local Oracle installation. Only later I installed Oracle and from that moment on my scripts were invalid. Now we know why that happens, but it took us a couple of weeks.

I can live with the fact that *if* the user instructs Flyway to use the SQL*Plus parser the login scripts are also included in the calculation, but in my case I did not make that choice. RCC made that choice for me in order to allow for the SET DEFINE statement to be set.

So maybe RCC should remove the ORACLE_HOME from the environment before spawning Flyway WHEN the user has NOT explicitily set the oracle.sqlplus=true. If the use however has set oracle.sqlplus=true RCC should leave the ORACLE_HOME enviroment variable untouched.
