### ISSUE TITLE
Migration Comands  order, validate is recommended ??

### ISSUE THREAD

**Issue by rodorico83** [flyway/flyway#3137]
Flyway version  7.5.4
Database Oracle
Using flyway command line 

This is not really about issue with the sw but rather is about which is the recommended approach in terms of commands and order to run on a flyway standard migration, a bit in relation with already closed issue https://github.com/flyway/flyway/issues/2987.

what you suggest to for a migration: 
migrate + repair (if previous fails)
validate (ignorePendingMigrations + ignoreMissingMigrations) + repair (if previous fails) + migrate (if validate or repair returns ok) + repair (if migrate fails)

I would appreciate some guidance :)

**Comment by DoodleBobBuffPants** [comment]
Your second approach is more like what you want to aim for, but there are a couple of recommended changes:

- Running `validate` first with the necessary 'ignore' options enabled lets you ensure you are in a correct state before you begin migrating

- If `validate` fails, then depending on the failure you can choose to run `repair` or break if the error needs manual intervention. You can use [JSON output](https://flywaydb.org/documentation/usage/commandline/#machine-readable-output) for inspecting the result

- After this `repair`, it's typical to run `validate` again or enable [`validateOnMigrate`](https://flywaydb.org/documentation/configuration/parameters/validateOnMigrate) before doing a migration to ensure the `repair` worked

- Running `repair` after a failed `migrate` lets you keep a clean schema history as `FAILED` entries are removed, but you'll likely want to know what those failures are, so it's a good idea to ensure logs or output is saved so that you can inspect the failure. Running the flyway commandline with `-X` as a parameter enables debug level logging should you need it

Hopefully this gives you some insight into the order you would typically use commands in a pipeline

**Comment by rodorico83** [comment]
Thanks,
this is helpful indeed :)
There is a list with the possible error outputs (in relation with the json messages) of validate command ?
Then i will know up front what casuistic i will need to handle.
Thanks again

**Comment by DoodleBobBuffPants** [comment]
Yes, there is a list of error codes for `validate` along with what causes them and a solution [here](https://flywaydb.org/documentation/usage/errorcodes/#validate-error-codes)

**Comment by rodorico83** [comment]
thanks
