### ISSUE TITLE
info and migrate command violates general contract

### ISSUE THREAD

**Issue by tejaspan** [flyway/flyway#3203]
###### Which version and edition of Flyway are you using?
7.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
No, I was not able to reproduce the same in 7.9.0. 

Since I have the older version in my repository, I would like to know if there is a workaround.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Azure SQL database
"Microsoft SQL Azure (RTM) - 12.0.2000.8   Jun  3 2021 19:34:57   Copyright (C) 2019 Microsoft Corporation "

###### Which operating system are you using?
Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
flyway -configFiles="azure.conf" -user="abc" -password="abc" info

OR

flyway -configFiles="azure.conf" -user="abc" -password="abc" migrate

###### What did you expect to see?
List of migration info

OR

Migration run

###### What did you see instead?
"ERROR: java.lang.IllegalArgumentException: Comparison method violates its general contract!"

**Comment by MikielAgutu** [comment]
This is a known problem that has been partially fixed since that version - which is possibly why you can't reproduce it in 7.9.0. Unfortunately there is no certain workaround.

It *might* be possible to fix it by setting the JVM property `-Djava.util.Arrays.useLegacyMergeSort=true` [See this Stack Overflow post](https://stackoverflow.com/a/33849589/5437021). However that's not a great solution.

The best thing I can suggest is to upgrade to the latest version of Flyway.

Does that help?

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity
