### ISSUE TITLE
QUOTED_IDENTIFIERS_IGNORE_CASE option is false SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". SLF4J: Defaulting to no-operation (NOP) logger implementation

### ISSUE THREAD

**Issue by brianrichardson1** [flyway/flyway#3218]
###### Which version and edition of Flyway are you using?

7.9.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using? (Type & version)
Snowflake

###### Which operating system are you using?
Linux Ubuntu and CentOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

flyway -info
Any flyway command will throw this.

###### What did you expect to see?
Nothing, just the return of the flyway -info command

###### What did you see instead?
Flyway Community Edition 7.9.2 by Redgate
QUOTED_IDENTIFIERS_IGNORE_CASE option is false
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by DoodleBobBuffPants** [comment]
This is due to some other dependencies that come bundled with the CLI, and shouldn't affect actual functionality

You can remove these messages regarding SLF4J by deleting the `aad` folder in `lib`, more specifically the `slf4j-api-1.7.30` JAR inside the `aad` folder

This folder of dependencies is only required for Azure Active Directory authentication and can be safely removed if you do not need this

**Comment by brianrichardson1** [comment]
Thank you, we will give this a shot over the weekend.  Much appreciated.
