### ISSUE TITLE
How to do flyway database migration for multiple database?

### ISSUE THREAD

**Issue by anjanitsip** [flyway/flyway#3233]
Hi 

I am using the flyway with spring-boot. I want to build a multi-tenant application with MySQL as a data store.

We are using the database-per-tenant pattern.

We have two sets of tables common tables and tenant-specific tables.  

We are struggling with how to achieve this, please suggest.

**Comment by DoodleBobBuffPants** [comment]
As Flyway operates on a per-schema basis, you will need to invoke Flyway multiple times, using the Java API or the Maven plugin, so that you can change the database you are migrating to each time

There is an article [here](https://www.red-gate.com/hub/product-learning/flyway/automating-migrations-for-multiple-databases-using-flyway) about multi-database deployments with Flyway

There is also a relevant blog post [here](https://flywaydb.org/blog/a-simple-way-to-manage-multi-environment-deployments) which describes how you can achieve this (it talks about different databases as different environments but the same principle applies)
