### ISSUE TITLE
Broken Automatic-Module-Name for flyway-mysql, flyway-sqlserver

### ISSUE THREAD

**Issue by A248** [flyway/flyway#3342]
JPMS module names must be unique. It seems that, in the creation of flyway-mysql, the module name for flyway-mysql was copied and pasted from the core flyway artifact. So, the flyway-mysql module has the wrong module name. This causes usage with JPMS to be impossible.

https://github.com/flyway/flyway/blob/142a1067ca85b2245905bebf4cd8d906e22356e2/flyway-mysql/pom.xml#L151

Also, I don't use SQL Server, but it seems the same mistake was made there:

https://github.com/flyway/flyway/blob/142a1067ca85b2245905bebf4cd8d906e22356e2/flyway-sqlserver/pom.xml#L162

###### Which version and edition of Flyway are you using?
Flyway 8.2.1, Community Edition

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Not applicable

###### Which operating system are you using?
Not applicable

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Run using the Java Module System (JPMS)

###### What did you expect to see?
Unique module names.

###### What did you see instead?
Ambiguous module names. The `flyway-mysql` artifact has the same module name as the core flyway artifact.

**Comment by A248** [comment]
The same mistake was repeated for the firebird module:
https://github.com/flyway/flyway/blob/553d1c0fb6bcb111b95b9b00b6199d33e4c4c319/flyway-firebird/pom.xml#L128

The issue is these module names are all the same. They must be distinct in order to be valid modules.

The bug isn't very difficult to fix. Choose distinct module names: for example, `org.flywaydb.mysql` for the MySQL plugin.

**Comment by agavrilov76** [comment]
I cannot upgrade to version 8.X due to this issue. Made a PR with a possible fix to speed up the process:
https://github.com/flyway/flyway/pull/3462

Note that the package name `org.flywaydb.database` is used across  the 'database' modules. So depending on db multiple modules at the same time wouldn't work due a package split.

**Comment by cowwoc** [comment]
Come on Redgate... Where is the transparency? When are you going to fix this critical bug?!

**Comment by Djaytan** [comment]
Hello,

Any news on it? This is a blocking issue when migrating to JPMS while relying on Flyway.

I'm really confused about the current situation : an easy fix with an associated PR ready to be merged since more than 1 year... But nothing more done.

What's the blocking point?

I may have to consider alternative it seems...

**Comment by JasonLuo-Redgate** [comment]
This issue was fixed in Flyway V10 release.

**Comment by Djaytan** [comment]
I confirm! Thanks a lot for your action!
