### ISSUE TITLE
Log4j bump to 2.17

### ISSUE THREAD

**Issue by larrydiamond** [flyway/flyway#3360]
CVE-2021-45105
More log4shell remediation
Patch forthcoming

**Comment by Barry-RG** [comment]
Hi @larrydiamond 
We are trying to keep up to date with the seemingly on-going Log4Shell developments. However, as Flyway's dependency on Log4J is optional and configured by our users we will be updating as part of our usual release pipeline schedule. 
This is because the version we state is only for development proposes and is under user control when running.
Please see our [blog post](https://flywaydb.org/blog/flyway-log4j-vulnerability) for further explanation.
