### ISSUE TITLE
Support JDK 17

### ISSUE THREAD

**Issue by knjk04** [flyway/flyway#3390]
###### Which version and edition of Flyway are you using?

6.5.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven

###### Which database are you using? (Type & version)

MySQL 8.0.19

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Upgraded Spring Boot project to JDK 17. However, I can see from your [documentation](https://flywaydb.org/documentation/getstarted/firststeps/maven) that JDK 17 is not supported. Is this something that you may consider?

###### What did you expect to see?

Support for JDK 17 or, failing that, for this to be included on the roadmap with an approximate timeline as to when this will be supported (if this is something that you plan to support soon).

I appreciate the JDK 17 is still fairly new, but, as this is the new LTS, it would be good to find out if this is something on the roadmap and an approximate timeline. Other projects may also be interested in upgrading at some point soon when libraries/plugins (such as this) provide support.

###### What did you see instead?

(I didn't expect this to work because I know you don't support JDK 17 yet, but I am adding this in for completeness).

FlywaySqlException. Stack trace here: https://gist.github.com/knjk04/424f927606df5645a95d519932a10d87.

**Comment by educostadev** [comment]
Although JDK 17 is not on the list of [supported Java Version](https://flywaydb.org/documentation/usage/api/), it worked for me using the **7.5.5 version**. I'm happy my project compiled, and the database was updated with success. Maybe using 8+ versions and some specific features can not work for you, but it was not my case. 

It would be awesome to homologate the flayway with JDK 17 LTS since more and more people are on this journey of upgrading their application to it. 

@knjk04 looking into your log error:
`java.sql.SQLException: null,  message from server: "Host '172.24.0.1' is not allowed to connect to this MySQL server"`

Looks like you have a database connectivity issue and not a JDK 17 incompatibility.

**Comment by odin568** [comment]
What does not work is compiling a JavaMigration against Java 17 and then using it with flyway. As Java 17 is a new LTS version, this should be supported, rather than i.e. Java 12. (I am building using gradle, but should be same with maven)

**Comment by frombrest** [comment]
8.0.5 working fine on JDK17 AWS Corretto-17.0.3.6.1 (build 17.0.3+6-LTS)

**Comment by JasonLuo-Redgate** [comment]
Will be supplied in the coming Flyway V10 release.
