### ISSUE TITLE
ignoreFutureMigrations=False in V9

### ISSUE THREAD

**Issue by esauser** [flyway/flyway#3411]
###### Which version and edition of Flyway are you using?
8.5.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
MSSQL 2014

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We've always had `ignoreFutureMigrations` set to `false`.  It defaults to `true`.  I see the warning that it is deprecated and is replaced with `validateMigrationNaming`.  I'm wondering what the equivalent setting is there for `ignoreFutureMigration` `false`.  Does it default to `*:Future`?  If so, I'm not seeing that documented.  If that is the case, do I need to set it to an empty string?  If it doesn't default, that's a breaking change that I'm also not seeing clearly documented.  Please advise.

The patterns make sense and work well for all the other since they default to `false`, but with this one defaulting to `true` it's not clear how to maintain that functionality.

**Comment by madninjaskillz** [comment]
Once we remove in V9 we will default all options to false as that seems the sensible approach.

**Comment by esauser** [comment]
I was trying to prepare for it ahead of time.  It sounds like that isn't possible as I currently need to set it to false, but then in V9 it will be removed and break, so I'll have to change it then.  Is that correct?

**Comment by agentgt** [comment]
Yes this seems ridiculous. Deprecating something without an option to do it the right way.

**Comment by rolfchess** [comment]
Ran into this issue when upgrading libraries in a project. It is indeed silly to remove this option without a clear alternative. It seems that by default, Flyway ignores *:future migrations. To change this, you'll need to explicitly set spring.flyway.ignore-migration-patterns to an empty string or define other patterns. 

This makes the default behavior problematic in our case: An old version of the software will happily start even though the database was initialized by a much newer version of the software and the old version of the software fails in unpredictable ways. Removing the ignore pattern is a strange way to tell Flyway to be strict about matching the database with the upgrade scripts.

What we did was add this function to our code:

```
private fun FluentConfiguration.ignoreFutureMigration(ignore:Boolean) =
    if (ignore) this.ignoreMigrationPatterns("") else this.ignoreMigrationPatterns("*:future")
```

So that we can configure Flyway in a more natural way:

```
init {
        Flyway.configure()
            .ignoreFutureMigration(false)
            .dataSource(driverDataSource)
            .load()
            .migrate()
```

On a different note: "ignore=true" is a very confusing, language wise. It is a mental "false = true", and would better be modelled as "include=true". In this case, I would have chosen for "allowFutureMigrations(false)". It results in less cognitive load, giving you more "brain power" to handle the task you are really working on.
