### ISSUE TITLE
No enum constant org.flywaydb.core.api.MigrationType.SCRIPT

### ISSUE THREAD

**Issue by xmanemran** [flyway/flyway#3413]
###### Which version and edition of Flyway are you using?
The old version was **8.0.0-beta2**.  Just update the version to  **8.5.4**. Both versions have the same issue.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
**Command-line**

###### Which database are you using? (Type & version)
**PostgreSQL 10.14**

###### Which operating system are you using?
**Docker image "adoptopenjdk/openjdk11:alpine-jre"**

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I'm trying to see the current state of the migrations by issuing `flyway info`. 
_Note I already have some applied migration's_
<img width="1252" alt="Screenshot 2022-03-18 at 12 08 59 AM" src="https://user-images.githubusercontent.com/4305563/158867998-273accec-39d3-4c49-8123-0ddada19b6dc.png">

###### What did you expect to see?
`flyway info` should return the current status of the migrations

###### What did you see instead?

Flyway is up to date
Flyway Community Edition 8.5.4 by Redgate
See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.4

Database: jdbc:postgresql://localhost:5432/dbname (PostgreSQL 10.14)
ERROR: java.lang.IllegalArgumentException: No enum constant org.flywaydb.core.api.MigrationType.SCRIPT

**Note: If I delete the migration type "script" from the flyway_schema_history table, it works as expected.**

**Comment by tjs145** [comment]
Script migrations are a Flyway Teams feature so presumably the script migration was applied during the Teams free trial period which was included in some versions (including `8.0.0`). 

When using Community edition (e.g. after the free trial period ended or the version was upgraded to `8.5.4`), Flyway no longer recognizes the script migrations so produces that error. 

There should be a fix in the next version that means Flyway no longer produces that error. Instead the script migration will be considered `Missing`, since Flyway Community cannot resolve script migrations.
