### ISSUE TITLE
Checksum fails with openjdk eclipse-temurin alpine

### ISSUE THREAD

**Issue by simao** [flyway/flyway#3431]
###### Which version and edition of Flyway are you using?

8.5.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

It's the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Postgres 12

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

This is most likely not a problem with flyway, but I'd like to ask here because maybe other people ran into this problem.

I have a production app with existing migrations previously executed successfully. The migrations were previously executed inside a container built from `adoptopenjdk/openjdk11:jre-11.0.11_9-debianslim` which uses debian.

When upgrading the image to use `eclipse-temurin:17-jre-alpine`, running alpine linux, running `migrate` fails with":

```
Migration checksum mismatch for migration version 1
-> Applied to database : 1683277987
-> Resolved locally    : -1888769356
Either revert the changes to the migration, or run repair to update the schema history.
Migration checksum mismatch for migration version 2
-> Applied to database : -2102150102
-> Resolved locally    : -486185622
Either revert the changes to the migration, or run repair to update the schema history.
Migration checksum mismatch for migration version 3
-> Applied to database : 456045874
-> Resolved locally    : 522070879
Either revert the changes to the migration, or run repair to update the schema history.
Migration checksum mismatch for migration version 6
-> Applied to database : 983113564
-> Resolved locally    : 1799084257
```

Running the same application, built in a container running `eclipse-temurin:17-jre-focal`, running ubuntu, the migration succeeds, that is no migrations are executed, but the checksum validations all pass.

Significantly, migrations 4 and 5 seem to pass the checksum validation, but there is nothing special about those files, none of the migrations were changed.

I dump that table and tried to reproduce locally, running the same containers but I cannot even reproduce this locally. This just seems so bizarre to me, any ideas why alpine would somehow influence the way flyway calculates the checksum?

###### What did you expect to see?

`migrate` should succeed, since no files were changed and no checksums should be different.

###### What did you see instead?

`migrate` fails due to checksum mismatch.

**Comment by Barry-RG** [comment]
When moving between Java JRE versions it is important to keep in mind any cryptographic changes that may have been made to Java between the releases you are upgrading from and to. In this case there does seem to be changes to the cryptographic  formula used around Java 17 due to Oracles roadmap and vulnerabilities discovered. This would cause the issues you are seeing.
However, it is due to changes like this that Flyway has yet to offer support to Java 17. Please see our documentation for supported Java versions. https://flywaydb.org/documentation/usage/api/#supported-java-versions

**Comment by simao** [comment]
That is fair enough.. but I isn't the checksum just a crc32 of the contents of the migrations? Didn't expect it to change.

**Comment by zs22** [comment]
Hi guys, I have the same problem with checksums, but I think the problem is in a used system library zlib 1.2.12-r0 in docker image - after I updated only this library in my docker image (without changing Java version) flyway fails on migration checksums mismatch and not only flyway - there is also a problem with checking indexes in JCR (Java content repository)
Any Idea how to fix it?
