### ISSUE TITLE
Comments in script files are not parsed correctly for Oracle

### ISSUE THREAD

**Issue by olavquorum** [flyway/flyway#3477]
###### Which version and edition of Flyway are you using?
8.5.11 

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes, have tested it using 8.5.13

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line, maven plugin

###### Which database are you using? (Type & version)
Oracle 19c

###### Which operating system are you using?
Windows and Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Created a script with comments and statement to create a table. 
[V001__Create_Table.txt](https://github.com/flyway/flyway/files/9037914/V001__Create_Table.txt)

```
/********************************************/
/* Testing 
/********************************************/
create table t (t varchar2(10));
```

The script runs successfully using SQL Plus and creates the table. Flyway runs successfully but doesn't create the table. 
Changing the comments to fix the issue
```
/********************************************
* Testing 
********************************************/
create table t (t varchar2(10));
```

###### What did you expect to see?

Flyway either run the create table statement or fail.

###### What did you see instead?

No error message or indication that the script was not run successfully

**Comment by DoodleBobBuffPants** [comment]
This is a limitation of our parsing

Flyway requires that all multi-line comments are appropriately closed

In your case, not closing the `/*` on the second line causes the whole script to be treated as a comment which is why nothing was reported. At the same time, nothing should've been executed too

We are unlikely to make changes here unless multiple people have this issue - in general we have found people prefer having multi-line comments appropriately closed, so closing until further interest
