### ISSUE TITLE
Undo doesn't work after an outOfOrder migration

### ISSUE THREAD

**Issue by pyrocks** [flyway/flyway#3480]
###### Which version and edition of Flyway are you using?
8.5.13 Teams

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Postgres 12

###### Which operating system are you using?
MacOs

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Tried to undo a migration after running an outOfOrder migration.
So this is the output of `info` before running undo:
```
Schema version: 2022.01.01.0001

+------------+-----------------+------------------+----------+---------------------+--------------+----------+
| Category   | Version         | Description      | Type     | Installed On        | State        | Undoable |
+------------+-----------------+------------------+----------+---------------------+--------------+----------+
|            | 1.0             | Base Migration   | BASELINE | 2022-07-11 15:21:11 | Baseline     | No       |
| Versioned  | 2022.01.01.0000 | create table foo | SQL      | 2022-07-11 15:44:40 | Deleted      |          |
| Repeatable |                 | utils            | SQL      | 2022-07-11 15:44:40 | Superseded   |          |
| Repeatable |                 | utils            | SQL      | 2022-07-11 15:52:49 | Success      |          |
|            | 2022.01.01.0000 | create table foo | DELETE   | 2022-07-12 11:59:02 | Success      |          |
| Versioned  | 2022.01.01.0001 | alter table foo  | SQL      | 2022-07-12 12:02:09 | Success      | Yes      |
| Versioned  | 2021.01.01.0000 | say hello        | SQL      | 2022-07-12 12:17:32 | Out of Order | No       |
+------------+-----------------+------------------+----------+---------------------+--------------+----------+
```

Then I ran undo:
```
flyway -configFiles=./config/flyway.conf -target=2022.01.01.0000 undo
...
Flyway is up to date
Flyway Teams Edition 8.5.13 by Redgate
See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13

Database: jdbc:postgresql://localhost:5432/deel (PostgreSQL 12.11)
Current version of schema "public": 2022.01.01.0001
Schema "public" has no migrations to undo.
```

With debug - the Undo migration passed validation - but still it didn't run:
```
...
DEBUG: Found filesystem resource: ./.DS_Store
DEBUG: Found filesystem resource: ./config/flyway.conf
DEBUG: Found filesystem resource: ./repeatables/R__utils.sql
DEBUG: Found filesystem resource: ./versioned/U2022.01.01.0001__alter_table_foo.sql
DEBUG: Found filesystem resource: ./versioned/V2021.01.01.0000__say_hello.sql
DEBUG: Found filesystem resource: ./versioned/V2022.01.01.0000__create_table_foo.txt
DEBUG: Found filesystem resource: ./versioned/V2022.01.01.0001__alter_table_foo.sql
DEBUG: Filtering out resource: ./.DS_Store (filename: .DS_Store)
DEBUG: Filtering out resource: ./config/flyway.conf (filename: flyway.conf)
DEBUG: Filtering out resource: ./versioned/V2022.01.01.0000__create_table_foo.txt (filename: V2022.01.01.0000__create_table_foo.txt)
DEBUG: Validating R__utils.sql
DEBUG: Validating U2022.01.01.0001__alter_table_foo.sql
DEBUG: Validating V2021.01.01.0000__say_hello.sql
DEBUG: Validating V2022.01.01.0001__alter_table_foo.sql
...
```

Then  I renamed `V2021.01.01.0000__say_hello.sql` to `.txt` and deleted the last row from `flyway_schema_history` - this time Undo worked:
```
flyway -configFiles=./config/flyway.conf -target=2022.01.01.0001 undo
...
Flyway is up to date
Flyway Teams Edition 8.5.13 by Redgate
See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.13

Database: jdbc:postgresql://localhost:5432/deel (PostgreSQL 12.11)
Current version of schema "public": 2022.01.01.0001
Undoing migration of schema "public" to version 2022.01.01.0001 - alter table foo
```

###### What did you expect to see?
outOfOrder migrations should not set the current schema version, nor should affect Undos.

###### What did you see instead?
It just didn't work as expected.

**Comment by tjs145** [comment]
We've updated the documentation around [`-target`](https://flywaydb.org/documentation/configuration/parameters/target) and [`undo`](https://flywaydb.org/documentation/command/undo) to make it a bit clearer. 

Currently, `undo` undoes migrations in reverse time order, rather than reverse version order, so migrations applied last are undone first irrespective of their version number.  

When using `-target`, Flyway undoes migrations in reverse applied order until it reaches a migration with a version number below the target, or one with no corresponding undo script. In the first case, no migrations were undone because the last applied migration (`2021.01.01.0000`) had no undo script, so Flyway stopped there. Removing the last row from the schema history table meant that `2022.01.01.0001` was the last applied migration, so it was undone successfully.

Specific migrations can be undone using [`cherryPick`](https://flywaydb.org/documentation/configuration/parameters/cherryPick). 

We could consider adding the capability to undo migrations in version order rather than time order if there's sufficient further interest.
