### ISSUE TITLE
PostgresSQL transaction locks even when disabling transactions

### ISSUE THREAD

**Issue by dragisak** [flyway/flyway#3492]
Version 9.1.2

As I understand, PostgresSQL transactional locks are now [enabled by default](https://github.com/flyway/flyway/issues/2895) since 9.1.0. 

If in my Vxxx.sql.conf file I specify `executeInTransaction=false`, does it still make sense to do transactional lock?

Per https://flywaydb.org/documentation/database/postgresql#lock-types I would have to disable transactional locks globally. But all I want is to do one migration that has `CREATE INDEX CONCURRENTLY`.

**Comment by DoodleBobBuffPants** [comment]
In the case of transactional locks, Flyway uses two connections - one for locking and making changes to the schema history table, and one for executing migrations. `executeInTransaction=false` is for the connection that executes migrations as opposed to the one for taking a lock on the history table. This lock is also taken for the whole `migrate` as opposed to per migration, so a per migration configuration wouldn't work

In this case we would recommend disabling transactional locks in order to use session locks - both types of locks will be supported so that we can support the full range of SQL

I'll be closing this for now unless it gets further interest, at which point we can revisit the current implementation

Out of interest, is disabling transactional locks globally an issue or blocker?

**Comment by dragisak** [comment]
We use flyway-play that currently doesn't have a good way to set `flyway.postgresql.transactional.lock=false`. For now, sticking to an older version of flyway works.
