### ISSUE TITLE
Transactional locks hanging for non-transactional migrations

### ISSUE THREAD

**Issue by danishnawab** [flyway/flyway#3497]
###### Which version and edition of Flyway are you using?
- org.flywaydb:flyway-core:9.1.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
- It is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

- Java API

###### Which database are you using? (Type & version)

- Postgres 12.4

###### Which operating system are you using?

- Docker container with Linux running on macOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

- Upgrading to flyway 9.1.2 caused existing migrations to hang indefinitely
- We have non-transactional migrations (e.g. `CREATE INDEX CONCURRENTLY index_name ON table_name(column_name)` that no longer work because the default behavior of flyway with postgres is to use a transactional lock starting flyway 9.1.2 (see https://github.com/flyway/flyway/commit/022a646b7959aa7a9a11760d8e93e5e238fbd6ec)
- Disabling the transactional log (`flyway.postgresql.transactional.lock=false`) works fine, but is such breaking behavior expected from a patch release?
- Does this interaction between non-transactional migrations and transactional locks make sense? 

###### What did you expect to see?

- Existing migrations to keep working after upgrading to 9.12

###### What did you see instead?

- Existing (non-transactional) migrations hang indefinitely

**Comment by DoodleBobBuffPants** [comment]
As you've noticed the behaviour did change in a minor version, and you can revert to the old behaviour with a configuration parameter

We likely won't change the default behaviour unless this is an issue for most users

**Comment by draganjovanovic1** [comment]
Same issue here.

**Comment by uwolfer** [comment]
> We likely won't change the default behaviour unless this is an issue for most users

This is also an issue in my setup.

**Comment by cbeardsmore** [comment]
+1 caused issues for us, running the same Postgres 12.4 and Flyway v9.1.4 via Docker

**Comment by LukasVyhlidka** [comment]
@DoodleBobBuffPants Hi, you refered this issue in https://github.com/flyway/flyway/issues/3506#issuecomment-1222246349 saying the problem is that concurrent indexes don't like transaction based advisory locks... Is this information written somewhere?

I run into the same issue as other did. And here is my experience....

My migration contained two statements to create indexes concurrently. Something like:
```
CREATE INDEX CONCURRENTLY index1 ON table(colA, colB);

CREATE UNIQUE INDEX CONCURRENTLY index2 ON table(colA, colC);

```

When the migration got stuck, I took a look into pg_stat_activity and there were two ongoing sessions regarding flyway:
- one that was holding the lock
  - state was `idle in transaction` 
  - query was `SELECT COUNT(*) FROM pg_namespace WHERE nspname=$1`
- the other was indefinitely waiting for the exclusive lock
  - query was the second index creation statement.
  
  
Actually, the first statement to create the index was fine and it proceeded, I could see that index already created.

Is it really about transaction based advisory locks not like concurrent indices?

I found this piece of code - https://github.com/flyway/flyway/blob/main/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLDatabase.java#L130

It changes between single and multiple connection based on the configuration you mentioned (`flyway.postgresql.transactional.lock`).

Can the fact that it runs in multiple connections / sessions be the problem? Like it is not releasing locks properly making something as deadlock?

**Comment by DoodleBobBuffPants** [comment]
@LukasVyhlidka 

It's documented on [this page](https://www.postgresql.org/docs/current/sql-createindex.html)

Multiple connections are required for scenarios where there is SQL that cannot be executed in a transaction - we still need a transaction in order to take a transactional lock, so we do it on a connection that updates the history table

**Comment by LukasVyhlidka** [comment]
Thanks, but...

This thing from the documentation is what you meant?
```
Regular index builds permit other regular index builds on the same table to occur simultaneously, but only one concurrent index build can occur on a table at a time. 
In either case, schema modification of the table is not allowed while the index is being built. 
Another difference is that a regular CREATE INDEX command can be performed within a transaction block, but CREATE INDEX CONCURRENTLY cannot.
```

Actually, the first index from the migration was created just fine. From the documentation it sounds as it should end up with the error but not with a deadlock.

**Comment by DoodleBobBuffPants** [comment]
This is the relevant paragraph:

> In a concurrent index build, the index is actually entered as an “invalid” index into the system catalogs in one transaction, then two table scans occur in two more transactions. Before each table scan, the index build must wait for existing transactions that have modified the table to terminate. After the second scan, the index build must wait for any transactions that have a snapshot (see [Chapter 13](https://www.postgresql.org/docs/current/mvcc.html)) predating the second scan to terminate, including transactions used by any phase of concurrent index builds on other tables, if the indexes involved are partial or have columns that are not simple column references. Then finally the index can be marked “valid” and ready for use, and the CREATE INDEX command terminates. Even then, however, the index may not be immediately usable for queries: in the worst case, it cannot be used as long as transactions exist that predate the start of the index build.

It implies that concurrent indexes will wait for any other transaction to terminate

**Comment by LukasVyhlidka** [comment]
Yes, it implies that... But when the other transaction is made again by the Flyway and never ends, it seems strange...
Now I am not very confident as my Flyway knowledge is very very low.

Will be the parameter supported in future versions?

**Comment by DoodleBobBuffPants** [comment]
Yes, `flyway.postgresql.transactional.lock` will continue to be supported as its the only way to get maximum compatibility with all of PostgreSQL

**Comment by LukasVyhlidka** [comment]
Thank you

**Comment by Ryokki** [comment]
I have a similar problem and I want to know why the process "SELECT COUNT(*) FROM pg_namespace WHERE nspname=$1" is Idle in transaction and what is waiting for in the application?
