### ISSUE TITLE
No Value Provided For Placeholder Encountered When Running Migration for Snowflake JS Procedure

### ISSUE THREAD

**Issue by jasonmcaffee** [flyway/flyway#3520]
###### Which version and edition of Flyway are you using?
7.7.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Unsure

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle

###### Which database are you using? (Type & version)
Snowflake

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Ran a migration that created a stored procedure that was written in js

###### What did you expect to see?
A successful migration

###### What did you see instead?
An issue with string interpolation in js.  We had a function that created a string that used interpolation

```
create or replace procedure doStuff()
    returns variant
    language javascript
as
$$
const value = "hello";
const str = `error was: ${value}`;

$$;
```

and received the error:

```
Caused by: No value provided for placeholder: ${value}.  Check your configuration!
```

**Comment by DoodleBobBuffPants** [comment]
The issue is that this syntax corresponds to Flyway's placeholder syntax

You can try changing the placeholder [prefix](https://flywaydb.org/documentation/configuration/parameters/placeholderPrefix) and [suffix](https://flywaydb.org/documentation/configuration/parameters/placeholderSuffix) or [disabling placeholder replacement](https://flywaydb.org/documentation/configuration/scriptconfigfiles#reference)
