### ISSUE TITLE
How do I configure flyway with official GCP SQL connectors?

### ISSUE THREAD

**Issue by red8888** [flyway/flyway#3556]
###### Which version and edition of Flyway are you using?
The latest enterprise version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using? (Type & version)
Cloud SQL postgres and mysql

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
GCP officially supports connecting directly with Java which flyway is written in: https://cloud.google.com/sql/docs/postgres/connect-connectors#java

This would mean I don't need to provide private network access or run the proxy in a separate process.

Is this supported?

**Comment by DoodleBobBuffPants** [comment]
This should work, however you'll need to add some dependencies to the Flyway CLI since we don't ship them for Cloud SQL support. You can add these JARs to the `drivers` directory

You'll need to get `com.google.cloud.sql:postgres-socket-factory` and any of its transitive dependencies. You can get them from [mvnrepository](https://mvnrepository.com/artifact/com.google.cloud.sql/postgres-socket-factory)

You should then be able to follow the [documentation](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/main/docs/jdbc-postgres.md#creating-the-jdbc-url) on how to configure your URL

Closing till further activity
