### ISSUE TITLE
Flyway DB Schema Scripts issues

### ISSUE THREAD

**Issue by salgotraja** [flyway/flyway#3591]
###### Which version and edition of Flyway are you using?

8.5.13 with springboot version 2.7.1 

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

No, application is in production and can't upgrade at the moment. Also this behaviour is not regular, it randomly marked the scripts with DELETE in flyway_schema_history table

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)
MySQL 8.0.29

###### Which operating system are you using?

Ubuntu 20.04 lts on EC2 instance

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Executed db migration script.

###### What did you expect to see?

If script is ok, it should execute successfully and mark migrated script in row with type = 'SQL' in flyway_schema_history table

###### What did you see instead?
Intermittently migration script marked as 'DELETE' in flway_schema_history. The behaviour is erratic, it picks up some rows in flyway_schema_history table and update those rows as type='DELETE' resulting into failed migration. Once these rows delete manually from table, migration runs successfully without any issues. This means there is no issue with the script but buggy behaviour of flyway.

Appending here screenshot for your reference

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/17561292/209949380-38c8a40a-7664-4324-929c-382c8cdb3107.png">

Thank you

**Comment by DoodleBobBuffPants** [comment]
This is expected behaviour introduced in Flyway v7 - [`repair`](https://documentation.red-gate.com/fd/repair-184127461.html) marks `missing` migrations as `deleted` in order to be more deliberate about removing migration scripts

Ideally you wouldn't be removing scripts, however this can occur if you aren't configuring `locations` when running `repair`

At the same time, if you'd like to remove migrations without marking them as `deleted`, you would need to configure the [`ignoreMigrationPatterns`](https://documentation.red-gate.com/fd/ignore-migration-patterns-184127507.html) parameter

**Comment by salgotraja** [comment]
Thank you @DoodleBobBuffPants for the response.  Will go deeper in documentation to understand the flow.
In my case problem is there is no missing migration. When i delete the rows manually and re-run deployment with same build it work. No change in code or migration scripts.

Thanks once again, and a very happy new year.
