### ISSUE TITLE
Why flyway 9.12 is not reflected here on github?

### ISSUE THREAD

**Issue by xtermi2** [flyway/flyway#3605]
###### Which version and edition of Flyway are you using?
9.11.0

###### What did you expect to see?
code and release of Flyway 9.12.0 is available via this repoitory on github

###### What did you see instead?
code and release of Flyway 9.12.0 is not available here on github. Last commt is 3 weeky ago (release of 9.11.0). 9.12.0 was released on maven central on January 19th 2023 - why not here on github?

**Comment by Barry-RG** [comment]
This was due to a pipeline issue that did not update our community repository. This will be updated in due course.

**Comment by joschi** [comment]
@Barry-RG Any news on this? Flyway 9.12.x and 9.13.x are neither listed in the releases on GitHub nor on the releases page at https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html.

**Comment by Barry-RG** [comment]
Apologies, I should have been more clear however I can update now. Unfortunately, 9.12.0 and 9.13.0 are not to be considered releases of Flyway. This is due to a release issue. All the changes were rolled into 9.14.1 as the next complete version of Flyway. Please only use versions of Flyway specified in the release notes.

**Comment by joschi** [comment]
@Barry-RG Thanks for the explanation!

Since Flyway 9.12.0 and 9.13.0 have artifacts on Maven Central, maybe it would make sense to add this to the release notes to not get people confused like myself. 😅 

- https://central.sonatype.com/artifact/org.flywaydb/flyway-core/9.13.0/overview
- https://central.sonatype.com/artifact/org.flywaydb/flyway-core/9.14.0/overview
