### ISSUE TITLE
Invalidate naming pattern for script only if it contains single underscore

### ISSUE THREAD

**Issue by Zanfo96** [flyway/flyway#3632]
Flyway version: 8.5.13

Which client are you using: Maven

Which database are you using: Oracle 21.6.0.0.1

Which operating system are you using: Services based on Alpine Linux

What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran): 

Using the script naming convention (e.g.) V1_namescript.sql (so just one underscore), flyway is validating this sql script even if it does not match the naming convention (with double underscore). What's happening is that the script seems to run, we can find it in schemaversion database table, with the actual correct naming regex (double underscore). What's actually happening is that the scritp has been insert in this table, but in reality it did not run and changed any data in DB. 

What did you expect to see: some kind of exception or at least invalidation of the sql script

What did you see instead: no error or warning at all

**Comment by Zanfo96** [comment]
Hi everyone, any news about it?

**Comment by yuliyasokh** [comment]
Hello Zanfo, I can implement this validation

**Comment by yuliyasokh** [comment]
Hello Zanfo, could you please check **flyway.validateMigrationNaming** configuration option? 

When set to true, validation will fail if any such scripts are found. If left as false (the default and current behavior), such scripts are ignored.
This can be useful to identify scripts with naming errors such as V1_My_description.sql (single instead of double underscore used as separator).

Details  can be found on https://flywaydb.org/blog/flyway-6-2-0 - Validate migration naming

**Comment by Zanfo96** [comment]
Hi @yuliyasokh, I will try it, thank you very much 😃
