### ISSUE TITLE
EnterpriseDB support

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#364]
_Original author: trivi...@upstreamsystems.com (October 12, 2012 07:44:28)_

Hello,

Since in my company we are using EnterpriseDB (commercial version of PostgreSQL) I couldn't use flyway because I got errors at the point flyway-core is comparing to the RDBMS name receiving when opening a connection. I had to download the sources and for the moment and add an OR check to use PostgreSQLDbSupport also for EnterpriseDB. So I had deployed a custom flyway version in our repository in order to get pass this problem.

Since EnterpriseDB is replacing Oracle in many small companies maybe you should consider also support for EnterpriseDB. I would be glad to join your team and contribute any EnterpriseDB specific features.

Thank you,
Marios

_Original issue: http://code.google.com/p/flyway/issues/detail?id=345_

**Comment by Bernado-P** [comment]
Hi there,

I am just encountering the same problem, that is we are using EnterpriseDB instead of Postgres. While the Postgres Driver does allow to connect and work with the database, there are still some minor differences ( e.g. like between Community mysql and Enterprise (Oracle) mysql ).
As far as flyway is concerned, the difference are probably irrelevant. Enterprisedb has some additional features ( e.g. Oracle Compatibility Mode ) and some add on tools. As far as database conversions over jdbc are in question there is almost no differences.

We currently have to stop using flyway or just put the patch in ourselves, as Marios mentioned in his post. It would be great if we could use flyway with enterprisedb, too. We are already using it with some mysql databases, and highly appreciate it.

Regards,

Bernado

**Comment by Bernado-P** [comment]
One more thing: I know this is an old discussions, but since it is still open, and the change is actually relatively minor, I still think it would be worth considering. Probably more interesting would be that the project also includes enterprisedb in their testsuites.

Regards,

Bernado

**Comment by axelfontaine** [comment]
Implemented by @rbellamy in #1286 . Thanks!
