### ISSUE TITLE
FlyWy doesn't execute SQL code

### ISSUE THREAD

**Issue by a-tarasiuk** [flyway/flyway#3655]
###### Which version and edition of Flyway are you using?
Last `9.16.3` version:
```xml
<dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-core</artifactId>
      <version>9.16.3</version>
</dependency>
```

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
`Maven`

###### Which database are you using? (Type & version)
`PostgreSQL`

###### Which operating system are you using?
`Windows 10 LTSC`

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
`application.properties` file:
```properties
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sbm_local_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate = true

# Hibernate
spring.jpa.hibernate.ddl-auto=update
```

`V1__add_country_field_for_user_table.sql` file located:
```
/resources/db/migration/V1__add_country_field_for_user_table.sql
```

`V1__add_country_field_for_user_table.sql` content:
```sql
CREATE TABLE distributors (
    id     integer,
    name    varchar(40) UNIQUE
);
```

Table `flyway_schema_history` was created successfully:
```csv
"installed_rank","version","description","type","script","checksum","installed_by","installed_on","execution_time","success"
1,"1","<< Flyway Baseline >>","BASELINE","<< Flyway Baseline >>",NULL,"null","2023-04-17 11:07:47.887948",0,True
```

###### What did you expect to see?
During application startup, the `distributors` table will be created

###### What did you see instead?
The `distributors` table is not created.

Spring Boot App logs:
```log
17-04-2023 13:41:43.431 [main] INFO  org.flywaydb.core.internal.database.base.BaseDatabaseType.info - Database: jdbc:postgresql://localhost:5432/sbm_local_db (PostgreSQL 15.1)
17-04-2023 13:41:43.466 [main] INFO  org.flywaydb.core.internal.command.DbValidate.info - Successfully validated 1 migration (execution time 00:00.015s)
17-04-2023 13:41:43.529 [main] INFO  org.flywaydb.core.internal.command.DbMigrate.info - Current version of schema "public": 1
17-04-2023 13:41:43.530 [main] INFO  org.flywaydb.core.internal.command.DbMigrate.info - Schema "public" is up to date. No migration necessary.
```

**Comment by Barry-RG** [comment]
This appears to be due to the use of 'Baseline on Migrate'. 
When using this function, Flyway will create a Version entry into your database which represents where the database is in comparison with your Flyway Migrations. As a result, Flyway will not migrate anything versioned on or below that version number. 
See the [baseline on migrate documentation](https://documentation.red-gate.com/fd/baseline-on-migrate-184127481.html): 

> This schema will then be baselined with the baselineVersion before executing the migrations. Only migrations above baselineVersion will then be applied.

In your output, it is showing that the baselineVersion is 1. This means that your Version 1 migration script is not above the baseline version. Your log output, `17-04-2023 13:41:43.466 [main] INFO  org.flywaydb.core.internal.command.DbValidate.info - Successfully validated 1 migration (execution time 00:00.015s)`, is showing that Flyway is seeing the migration but not executing. 

As a result, depending on your database set up, either you did not need to use 'Baseline on Migrate' or you need to take that baseline as your Version one script and your first script needs to be Version two, I.E. `V2__add_country_field_for_user_table.sql`.
