### ISSUE TITLE
Redshift test driver stopped working

### ISSUE THREAD

**Issue by yaelah-sf** [flyway/flyway#3680]
###### Which version and edition of Flyway are you using?
9.19.1
I am in the process of upgrading from 6.3.3 to 9.19.1 

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
9.19.1 is the latest as of today

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Postgres 13.9 simulation of Redshift

###### Which operating system are you using?
osx

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I am upgrading Flyway from version 6.3.3 to 9.19.1 .  We use a Redshift fake driver from https://github.com/opt-tech/redshift-fake-driver for our integration tests. It is capable of accessing Postgres to simulate Redshift. The JDBC url is "jdbc:postgresqlredshift://localhost:5432/foo" .

In version 6.3.3 of Flyway, this worked, but in version 9.19.1 of Flyway, I am getting an error

Caused by: org.flywaydb.core.api.FlywayException: No database found to handle jdbc:postgresqlredshift://localhost:5432/foo
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:54)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:89)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1711)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1400)
	at org.flywaydb.core.api.configuration.FluentConfiguration.configuration(FluentConfiguration.java:947)

###### What did you expect to see?
I expected a successful connection

###### What did you see instead?
The error above

**Comment by Barry-RG** [comment]
In the time between 6.3.3 and 9.19.1 Flyway has had to become more specific in how it detects which database it is connecting to for parsing and processing functionality as well as supporting derivative databases. In this case, 6.3.3's logic of anything which says its postgres is postgres can no longer be applied. Since postgres and redshift syntax are different, Flyway must know what it is parsing and the JDBC url of `jdbc:postgreqlsredshift:` is not supported since it is not a JDBC url used by any supported database type. 
A suggestion would be to see if redshift-fake-driver would accept `jdbc:redshift://localhost:5432/foo` and allow pointing at your local postgresql database. This would allow Flyway to parse your scripts as Redshift and use the redshift-fake-driver to connect to your local database.

**Comment by yaelah-sf** [comment]
Hi @JasonLuo-Redgate , I see this issue is marked as "Completed" . Does flyway support jdbc:postgreqlsredshift: again? thanks!
