### ISSUE TITLE
Add option to disable 'report.html.html' and 'report.html.json' created when using cli

### ISSUE THREAD

**Issue by red8888** [flyway/flyway#3685]
###### Which version and edition of Flyway are you using?
`redgate/flyway:9.19`

I'm confused why this was closed? https://github.com/flyway/flyway/issues/3652

Its still an outstanding feature request no? It wasn't "resolved", I still have no way of controlling if report files are generated and where they are written.

There should be a toggle to disable all together. This is messing up my deployment automation and writing files into app repos when run locally users need to remember to delete. Its not even in a subfolder to make it easy to git ignore.

**Comment by Phil-Factor** [comment]
I had an interesting example the other day.  A 10 Mb file of insert statements for test data failed due to a system-named constraint having a different name.  That generated an error that not only explained what was wrong but provided the entire contents of the file onscreen.  When Flyway does that, I just hit ^C to stop the endless scrolling, but now , errors like this get  into these files and bulks them up enormously from then on.  You can delete them in Flyway Teams with an afterInfo batch file but that is scarecly the point - it slows down Flyway Info to write them

**Comment by Phil-Factor** [comment]
@red8888  Hah! Me too.  I've always wanted to find a use for beforeInfo and afterInfo callbacks so I took pleasure it writing one. However I now find that I need to delete the awful files after  every  operation.

**Comment by sam-artuso** [comment]
This is annoying. Please fix it!

**Comment by bekoeppel** [comment]
You can disable the reports with the `flyway.reportEnabled` option: https://github.com/flyway/flyway/blob/5e894fed50b9ebdb122b1f6671679cb69e17e84c/flyway-core/src/main/java/org/flywaydb/core/internal/configuration/ConfigUtils.java#L117

On the CLI: `flyway -reportEnabled=false migrate`.

**Comment by Mario-Eis** [comment]
It should be disabled by default. Always typing this flag in the CLI is annoying.

**Comment by Phil-Factor** [comment]
I notice that '-outputType=json' has been removed from the documentation.  Is this now deprecated? If so, what is the new way of doing it? Do we now have to use report.json?  If so, how do we switch off the annoying 'report.html' and make report.json optional?

**Comment by JasonLuo-Redgate** [comment]
In V10 release, the report is disabled by default.

**Comment by Phil-Factor** [comment]
I want to use report.json because it now seems to be updated by Flyway after a migration or undo (though I cannot find this behavious Documented). I want to avoid having the tiresome report.html. Is report.json updated even if one has set reportEnabled to false in order to prevent the report.html being generated? Is report.json, on the other hand, switched on or off with the reportEnabled config setting?

**Comment by JasonLuo-Redgate** [comment]
Yes,  the `report.json` is also controlled by the `reportEnabled` config setting.
