### ISSUE TITLE
Postgres begin atomic

### ISSUE THREAD

**Issue by clansing33** [flyway/flyway#3703]
###### Which version and edition of Flyway are you using?
Flyway desktop 6.4/Flyway engine 9.20

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
This is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Flyway desktop

###### Which database are you using? (Type & version)
postgres

###### Which operating system are you using?
windows 11

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Created migration file

```
create procedure test()
language sql
begin atomic

    select 1;

end;
``` 

ran migration in flyway desktop

###### What did you expect to see?
a successful migration
flyway engine 9.18 says "Flyway now handles defining PostgreSQL functions using `BEGIN ATOMIC`."

###### What did you see instead?
"ERROR: syntax error at end of input"

**Comment by JasonLuo-Redgate** [comment]
Hi @clansing33 , have you tried using flyway engine directly to see if this can be handled as expected?

**Comment by clansing33** [comment]
I will give it a try and get back soon

**Comment by clansing33** [comment]
flyway engine 9.20

same result - "ERROR: syntax error at end of input"

**Comment by JasonLuo-Redgate** [comment]
Hi @clansing33 , I can reproduced this issue and it turned out that the postgres JDBC driver will attempt to split the statement into multiple commands.
If you want to use the `begin atomic `syntax, you need to make some changes in your JDBC url like this `jdbc:postgresql://localhost:5432/postgres?preferQueryMode=extendedForPrepared`
I locally verified this solution, it works fine.

More details please refer to https://postgrespro.com/list/thread-id/2571450?ysclid=l779hi96793448119

**Comment by clansing33** [comment]
Thanks for the follow-up.  I'll talk to the DevOps team here and see if they can make this change in our ci/cd pipeline
