### ISSUE TITLE
Flyway 9.19.0 use of event connection breaks previous behavior 

### ISSUE THREAD

**Issue by jclaudelin** [flyway/flyway#3709]
###### Which version and edition of Flyway are you using?

Flyway 9.19.0 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Oracle 19.10

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We have built a database installation tool on top of Flyway that are used to install the component's DB schema of our microservice based platform.  After upgrading to Flyway 9.19.0 we get failing tests and unpredictable behavior for our use case.

In order to support rolling upgrade of applications we are using an Oracle feature called Edition Based Redefinition (EBR) in Oracle which basically are versioned data models. 

The component migration scripts normally sets the edition on the connection (the connection can be considered as having the edition as a kind of state) before executing any other DDL statements to ensure that the any created schema objects ends up in the correct edition. In order to get a consistent behavior our installation tool has used callback scripts that are executed before and after each migration scripts to ensure that a known state/edition is achieved.

Since Flyway introduced a specific 'event connection' that callbacks are executed on, we can not ensure that the migration connection has a know state before the next migration script since it will remain in the same state/edition as the previous script left it in.

###### What did you expect to see?

No change in behavior after upgrading to Flyway version >= 9.19.0

The state of the migration connection(s) can be altered by script callbacks.

###### What did you see instead?

Breaking tests and non working functionality.

The state of the migration connection(s) can not be altered by script callbacks.

###### Request / proposal

Make it configurable whether the callbacks should be executed on a separate connection (default) or on the migration connection (as in versions <9.19.0)

**Comment by JasonLuo-Redgate** [comment]
Hi @jclaudelin , Flyway has to separate the connections between migration and callback because reusing the same connection will cause Flyway failing to secure the `Group `feature. https://documentation.red-gate.com/fd/group-184127506.html 
A related ticket is here https://github.com/flyway/flyway/issues/3671 

Basically it's not a committed Flyway protocol that the migration connection and the callback connection should be the same one. So it would be risky to reply on this assumption.

**Comment by jclaudelin** [comment]
Hello @JasonLuo-Redgate,
Thanks for the reply although we don't completely agree to the conclusion and hope that some solution can be found since this changed behavior is causing us some non-negligible pain. The main problem for us is that a migration script may change the state of a connection (in our case for Oracle, the edition = data model version) and we need to reset that state after each migration file is executed.

The provided link above points to the Group feature (understood to be used for databases supporting DDL transactions) which needs to be enabled explicitly. Couldn't it be 'logical' to use an event connection _if_ the Group feature is enabled and otherwise execute the callbacks on the migration connection?

Are there any other proposals for how we can get hold of the migration connection after a migration file has been executed to reset the connection state?

For performance reasons we are using a connection pool data source. Would not using a connection pool solve this issue? Is a new connection requested from the data source for each migration file?

**Comment by JasonLuo-Redgate** [comment]
Hi @jclaudelin ,
Many thanks for the advices, I will raise this topic "use an event connection if the Group feature is enabled and otherwise execute the callbacks on the migration connection" into internal team discussion, and get back with a feedback to this ticket.

**Comment by JasonLuo-Redgate** [comment]
Hi @jclaudelin ,

Many thanks for providing above detailed info, and glad to know that you can work around this with different callbacks. 

But in the long term, may I suggest that could you find some way to make your environment independent on assumptions  on `Connection `? Because these are undocumented and thus not unguaranteed behaviors.  For example, the javadoc mentioned  `in a separate transaction`, but not mentioning any info about `Connection`.

So to be honest, it's possible in a few releases later, even the `beforeEachMigrate/afterEachMigrate` callbacks can change their way of using `Connection`. Then your environment might be broken again.  

Regards
