### ISSUE TITLE
Flyway docker build is failing

### ISSUE THREAD

**Issue by kvneswar** [flyway/flyway#3776]
###### Which version and edition of Flyway are you using?

latest or 10-alpine

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
no issue with the older version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)
postgres

###### Which operating system are you using?
windows and linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Dockerfile:

FROM flyway/flyway:10-alpine

COPY target/com.someorg.flyway*.gz /tmp

RUN tar -xvf /tmp/com.someorg.container.flyway*.gz

RUN rm -f V*__\$\{args\}.sql

RUN mv *.sql /flyway/sql/

###### What did you expect to see?
should be able to copy the .SQL files to the directory /flyway/sql/

###### What did you see instead?
flyway build is failing with the error "mv: target '/flyway/sql/' is not a directory"

**Comment by Barry-RG** [comment]
This issue is due to the default `sql` folder no longer being shipped with CLI and Docker as we do not recommend using the install directory to store your migration scripts. 
This had been missed from the [release notes](https://documentation.red-gate.com/flyway/release-notes-and-older-versions/release-notes-for-flyway-engine) but have now been updated. Our apologies.
Please `mkdir` to create a folder to store your migrations.
