### ISSUE TITLE
Flyway upgrade from 9.16.0 to 10.10.0 fails flyway migration

### ISSUE THREAD

**Issue by Bekturdi** [flyway/flyway#3855]
###### Which version and edition of Flyway are you using?

I am using Flyway 10.10.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

-

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

sbt 1.7.1
"org.flywaydb" % "flyway-core" % 10.10.0
java version: 11

###### Which database are you using? (Type & version)

PostgreSQL 42.7.1

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I'm trying to upgrade the Flyway version from 9.16.0 to 10.10.0.
After updating the version I get the following compiler error:
```
java.lang.UnsupportedClassVersionError: org/flywaydb/core/Flyway has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

Note: same code with flyway 9.16.0 working fine

flyway code in scala: 
```
Fway
  .configure()
  .dataSource(config.url, config.username, config.password)
  .locations(config.location)
  .schemas(config.schema)
  .baselineOnMigrate(true)
  .table("flyway_schema_history")
  .load()
```      

###### What did you expect to see?

I expected the migration to go smoothly

###### What did you see instead?
-

**Comment by Barry-RG** [comment]
Hi @Bekturdi thank you for your issue. This is because Flyway is compiled for Java 17 since version 10.0.0, please see the [release notes](https://documentation.red-gate.com/flyway/release-notes-and-older-versions/release-notes-for-flyway-engine#ReleaseNotesforFlywayEngine-Flyway10.0.0(2023-10-31)) for the Java Compatibility. Please see the [API documentation page](https://documentation.red-gate.com/flyway/flyway-cli-and-api/usage/api-java) for the minimum version of Java that is now supported by Flyway.

**Comment by Bekturdi** [comment]
@Barry-RG Thanks for the quick reply!
