### ISSUE TITLE
ignoreMigrationPatterns: missing pattern does not work for if a future migration is missing

### ISSUE THREAD

**Issue by victornoel** [flyway/flyway#3897]
###### Which version and edition of Flyway are you using?

10.13.0 Community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Postgresql 15

###### Which operating system are you using?

Linux / Docker

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

- I am using `flywayConfig.ignoreMigrationPatterns(ValidatePattern.fromPattern("*:missing"));`.
- I have a successfully applied migration but dated in the future in my database
- I deleted that migration

###### What did you expect to see?

Flyway would ignore that previously applied migration during validation.

###### What did you see instead?

Flyway is failing because of that migration during validation:
```
org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected applied migration not resolved locally: 20241001000000
```

###### Workaround

If I use both `*.missing` and `*:future` for `ignoreMigrationPatterns` then Flyway ignore that previously applied migration during validation.

**Comment by JasonLuo-Redgate** [comment]
Hi @victornoel ,

A applied missing migration but dated in the future, is defined as `future` in Flyway, rather than `missing`. That's why `missing pattern` does not work in your case. 

I admit that this definition can be confusing; however, it has been a long-standing design choice in Flyway.
You can have a more in-depth explanation in this post https://stackoverflow.com/questions/16902255/flyway-info-screen-state-is-future-not-missing

**Comment by victornoel** [comment]
Hi @JasonLuo-Redgate, thank you for the explanation. This makes sense indeed!
