### ISSUE TITLE
Partial schema management with object prefixes

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#439]
_Original author: obd...@gmail.com (February 15, 2013 18:26:06)_

It would be useful to support only partial management of a schema.

Here's an example: Writing a module for a platform such as Oracle ATG requires me to add tables to a schema I don't fully control.  I'd like to be able to manage tables based on exclusion rules and have Flyway ignore everything else in the schema.

A non-invasive way to do it might be to allow the user to specify table prefixes.  By default, Flyway would manage everything in the schema, but if the user provides one or more table prefixes, then Flyway only manages tables with those prefixes, ignoring everything else.

I haven't poked around the Flyway codebase to determine how much effort this would be, but I'm willing to help out if Flyway feels that a feature like this is worthwhile for inclusion into the product.  I'd like to avoid managing my own fork, if possible.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=433_

**Comment by sanelson2000** [comment]
I know this is a really old issue, but perhaps I'm missing something.  This feature request was for Flyway to support table prefixes, and the issue marked as a duplicate was about separate schemas.  While, in an ideal world, separate schemas would be the way we all separate tables, that is not always possible, depending on what type of constraints the developer has on them in the database.

This issue was for allowing us to group tables in the same schema, using prefixes, so for, example, if we specify a table prefix of "MY_APP_", Flyway will only look for and manage tables, whose name starts with "MY_APP_", and ignore everything else.  You would end up with set of tables, like:
- MY_APP_USERS
- MY_APP_POSTS
- MY_APP_COMMENTS
- MY_APP_FLYWAY_SCHEMA_HISTORY

The schema might contain other tables, like:
- USERS
- POSTS
- COMMENTS
- YOUR_APP_SESSIONS
- YOUR_APP_FLYWAY_SCHEMA_HISTORY

And those tables would be ignored.

Is this currently possible?  This issue is the only thing that I've found so far on the subject, and it appears to be erroneously closed, from what I can see.

**Comment by DoodleBobBuffPants** [comment]
This is quite old now, closing until further interest
