### ISSUE TITLE
Clean on DB2 functions or procedures fails when two procedures have the same name

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#464]
_Original author: Mark.F.G...@gmail.com (March 27, 2013 16:25:04)_

In DB2, you can have 2 or more funcs or procs with the same name as long as their signature is different.  To drop them, the signature must be used.

Example:

CREATE FUNCTION TEST_FUNC ( PARAM1 INTEGER )
  RETURNS INTEGER
  LANGUAGE SQL
RETURN 
1;

CREATE FUNCTION TEST_FUNC ( PARAM1 INTEGER, PARAM2 INTEGER )
  RETURNS INTEGER
  LANGUAGE SQL
RETURN 
1;

CREATE FUNCTION TEST_FUNC ( PARAM1 INTEGER, PARAM2 INTEGER, PARAM3 INTEGER )
  RETURNS INTEGER
  LANGUAGE SQL
RETURN 
1;

DROP FUNCTION TEST_FUNC; --fails
DROP FUNCTION TEST_FUNC ( INTEGER ); --succeeds
DROP FUNCTION TEST_FUNC ( INTEGER, INTEGER ); --succeeds
DROP FUNCTION TEST_FUNC ( INTEGER, INTEGER, INTEGER ); --succeeds

_Original issue: http://code.google.com/p/flyway/issues/detail?id=463_

**Comment by pswrdf** [comment]
I faced with same error flyway 3.2.1: 
INFO: Database: jdbc:db2://localhost:50001/TEST1 (DB2/NT64 9.7)
Exception in thread "main" org.flywaydb.core.api.FlywayException: Unable to clean schema "DB2ADMIN"
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-476, SQLSTATE=42725, SQLERRMC=DB2ADMIN.MYFUNCTION, DRIVER=3.63.75

REFERENCE TO FUNCTION function-name WAS NAMED WITHOUT A SIGNATURE, BUT THE FUNCTION IS NOT UNIQUE WITHIN ITS SCHEMA
