### ISSUE TITLE
Condense existing migrations into a new initial one

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#470]
_Original author: theasp...@gmail.com (March 29, 2013 11:29:05)_

We have hundred migrations, tabels created and drops, unnecessary fields and so on. It will be great to add cummulative migration which can be applied to clean schema to optimize initial migration.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=470_

**Comment by sodik82** [comment]
+1 : we have similar home-made update mechanism and we are thinking about migrating to Flyway. Since we have a lot of version, the incremental creation of DB from scratch takes now almost 30 minutes so we were checking if it is possibility to "rebase" the DB. 

Therefore "the easy way: concat all scripts" might not help us so I was thinking about possibility to define rebase (SQL/java) in addition to normal V1,... V220 files, e.g. R200__rebase.sql would be equivalent to all increments from V1 to V200. And if Flyway detects the empty DB it can start from R200 and then just apply the rests of the increments V201...V220.

As it is not "feasible" to create just definition by Flyway auto-magically, it might be the responsibility of the user to create such definition (e.g. as mentioned "the hard way: dump the current state of the DB") but that's totally fine.

**Comment by priyasebastian** [comment]
+1

**Comment by 0x6e6562** [comment]
+1

I've just dumped my production schema and into a new `Vnnn__x.sql` outright migration and expected to rebase the `schema_version` table using the baseline command. In doing so, I've just realized that this is not the way it works -  a baseline is only relevant when Flyway wasn't previously being used.

My motivation is to compact n database patches down to one new outright patch. The driver behind this is to coalesce all of the patched DDL back down into a unified definition, rather that having to mentally apply all of the patches in order to figure out what the current DB state should be (without having to look into the database with a DB frontend).

So I guess what I'm going to have to do is to replace the latest patch file with the contents of the schema dump and then run a repair on the migrations table.

**Comment by mlovretovich** [comment]
+1

**Comment by jladenfors** [comment]
+1

**Comment by mcekovic** [comment]
Hi,

If a project contains tens or even hundreds of migrations, installing initial database schema on empty database can take a looooot of time. Tables get created, fields added, fields renamed, fields removed, FKs added, FKs renamed, FKs removed, indexes added, indexes removed, even tables dropped... In full initial install on empty schema, removed items should not be added at all, renamed items should be created with final name, etc...

Also, when upgrading existing production databases with several migrations where there is a lot of data in the database, it could also take a looooooot of time (of course depending on actual migration) which is often actually a downtime. Sometimes, this can be made much, much faster by providing special migration that can bring schema directly from version 1 to 3, skipping intermediate version 2.
 
This honestly makes Flyway not usable as DevOps tool for continuous delivery to production, but only as a developer tool for maintaining development and integration environment databases.

To address this above issue really need to be supported.
Flyway should allow full database to be installed from one script that would immediately bring database to version 123, skipping installing separate versions 1, 2, 3, ..., 10,... 100, ..., 120, 121 and 122.

You can add special naming scheme for manually adding special condensed migrations, like

V123_from_V45__Condensed_Migration.sql

Which would bring database schema from version 45 to version 123 in one hoop.
When Flyway recognizes that it should bring database schema from version 45 to version 123, it should check if there are condensed migrations available, and if they exist, apply them instead of version-by-version migrations.

For example existing schema is 45 and current version is 123:
If there is a file (or files) starting with:
V123_from_V45_NNN.sql
execute only them.
But if there is a file (or files) starting with:
V120_from_V50_NNN.sql
execute then:
V46__NNN.sql
V47__NNN.sql
V48__NNN.sql
V49__NNN.sql
V120_from_V50_NNN.sql
V121__NNN.sql
V122__NNN.sql
V123__NNN.sql

You get the point, execute all condensed migrations that could speed up the upgrade.

Finally, to support direct install to current version from empty database, support file names like:
V123_from_V0_NNN.sql

P.S. Hope you get the idea what is needed, actual naming conventions are of course up to you :)


Of course, using condensed migrations in Continuous Delivery needs special attention and special care with special tests, as screwing condensed migrations is easy and condensed migrations are usually not used on development and integration environments, but usually on environments nearer to production and production itself.

**Comment by mcekovic** [comment]
@axelfontaine
> I see two ways to approach this:
> the easy way: concat all scripts
> the hard way: dump the current state of the DB
> Currently I am leaning towards the former. The latter can then always be implemented later.

I believe Flyway should not implement either:
- Flyway should not try to concatenate files. There are other tools that can do that easily.
- Flyway should not try to be too smart and provide a dump of the all objects in the database. This is very complex problem to solve for one single vendor (ordering of object creation for example), let alone to be DB independent feature. There are plenty of other specialized DB tools that can do that.
What Flyway should support is ability to specify a single full install script entry to install schema from scratch, like rebase script suggested by sodik82 (like R123__Full_Install.sql) or specialized case of generic Condensed Migration (like V123_from_V0__Condensed_Migration.sql) by me in the above comment.

**Comment by axelfontaine** [comment]
@mcekovic You can already easily achieve this today by dropping the schema_version table and rebaselining the schema.

**Comment by mcekovic** [comment]
Not sure I understand how this is the same. What is needed is that we can specify a SINGLE script to bring EMPTY schema to current the version, but not executing all the migrations starting from V1 to V123, as this can take very long time if there are a lot of migrations (caused by new features but even more by refactorings).
Dropping the schema_version and rebaselining can be done only on already installed schema. Use case for efficiently install schema from scratch is not supported by Flyway currently.

**Comment by axelfontaine** [comment]
@mcekovic You dump your existing DB in a single script with the same version as the baseline. This allows you to quickly migrate fresh DBs to the same version. From there on both existing and previously fresh DBs are migrated as usual.

**Comment by mcekovic** [comment]
OK, lets say current version is 123 and I want to do baseline. I dump the DB in single script and put it in source control as V123__New_Beginning.sql. But I need to delete all other migrations, and leave only single migration script, did I?

Then bug is found in version 119, how do I create a schema with version 119 if I deleted migration history?

You can suggest to have a branch in source control for each of the database versions, but sorry, this is not a solution (way too complex then it should be).

The cleanest solution is full support for Condensed Migrations and Database Downgrade in Flyway. It will make Flyway THE DevOps tool for automating database installations (not only migrations!!!).
With Current features, Flyway is usable only as developer tool to maintain developer/integration DBs, it is usable as DevOps tool for simpler schema as well as for complex schema where schema is always instantly upgraded to new versions in production, but that is still not the common case in the industry (and is question if it will ever be, for non-technical reasons).

**Comment by mcekovic** [comment]
Here is the basic reasoning why Condensed Migrations (and thus Database Downgrade to support Condensed Migration testing) are really needed features:
- When you do software package installation, you do either clean full install, or you do upgrade.
- You should be able to do upgrade from any of the previous versions
Flyway do support both, but when migrations accumulate, both full clean install and migrations from very old versions can become inefficient.
In my company we have clients migrating complex schema (tens of schema, nearly thousand of tables, tens of thousands of columns) from product versions several years old. You can imagine how complex this task was. It was actually a separate project just to create a Condensed Migration script to migrate such customers to newest product version in order to minimize downtime. We did this manually of course as this was 7-8 years ago. Now such tasks can be simpler with a tools like Flyway, just Condensed Migrations and Database Downgrade features are needed to make it real DevOps gem.

**Comment by s-nel** [comment]
+1

**Comment by Ramblurr** [comment]
Are there any plans to address this?

**Comment by lslonina** [comment]
+1

**Comment by mikekeil-wf** [comment]
+1

**Comment by jlannoy** [comment]
+1

**Comment by grommitz** [comment]
+1

**Comment by eladtamary** [comment]
+1

**Comment by peteroreil** [comment]
+1

**Comment by paulmccarthy** [comment]
+1

**Comment by missingfaktor** [comment]
+1

**Comment by franciskittu** [comment]
+1

**Comment by tpischke** [comment]
+1

**Comment by callicles** [comment]
+1

**Comment by darksebius** [comment]
+1

**Comment by JWGmeligMeyling** [comment]
+1

**Comment by hotzen** [comment]
+1

**Comment by mary-gao** [comment]
+1

**Comment by pavel-kiselyov** [comment]
+1

**Comment by fdietze** [comment]
Please stop spamming with +1. This doesn't help anyone.

**Comment by mcekovic** [comment]
+2 :)
This is extremely important enhancement :), that is why people are 'spamming'.

**Comment by env0der** [comment]
Since switching to JVM world I'm really missing database migrations from Ruby on Rails. There every time you migrate a database a new schema file is produced. The schema file is usually committed to version control. And then one normally creates his local or test database from this schema dump. It's much faster then replaying the whole migrations history. Also schema file is extremely useful as it allows you to see your entire database structure in one file. One can read more here:

http://guides.rubyonrails.org/active_record_migrations.html#schema-dumping-and-you

**Comment by daviwu** [comment]
+1

**Comment by elfungi** [comment]
+1

**Comment by AlJohri** [comment]
in case it helps anyone, this is how re-baselining works: https://stackoverflow.com/a/33510851/1667241

**Comment by mcekovic** [comment]
Not sure how re-baselining helps in the scenario where condensed migrations are needed.
Condensed migrations are needed when:

- You need to do a full install from scratch of a huge schema that so far has hundreds of migrations. Sure you can leave Flyway with only one migration file with full install, but that way you lose the possibility to do migrations on some other environment. And no, branch-per-environment every time this is needed in not an option (branch-per environment is an anti-pattern if semantic versioning is used, and you need semantic versioning when you develop public software and not in-house software). So re-baselining can work in this scenario only for in-house software, where we can afford branch-per-environment.

- You need to migrate from a very old version, since which you have hundreds of migrations. Here also branch-per-environment can help, but as stated above, this is possible only with in-house software that does not apply semantic versioning and do not have multiple active releases (that need to be supported). Public software (either open source or commercial) almost always apply a public versioning model and almost always need to support multiple software versions in parallel and branch-per-environment is an anti-pattern in this scenario.

**Comment by timt** [comment]
We do this to allow us to compress scripts for building new DB in dev environments but also run against existing production DB without having to log on and delete the flyway_version_history table, and we can keep the scripts (mainly for reference):

Compress all the scripts to a new script e.g. V1 to V42 into a new scripts V43.
Convert V1 to V42 to text files by putting .txt on the end.

Set the baseline to 43.
Set flyway to ignore missing migrations.

In script V43 use an 'if' block to protect the create/instert statements so that they don't run for the existing production database. We use postgres so it is something like this:

```
DO $$
  DECLARE
    flywayVersion INTEGER;
  BEGIN

    SELECT coalesce(max(installed_rank), 0) INTO flywayVersion FROM flyway_schema_history;
    RAISE NOTICE 'flywayVersion = %', flywayVersion;
    IF flywayVersion = 0 THEN
      RAISE NOTICE 'Creating the DB from scratch';
      CREATE TABLE...
      .....
    END IF;
END$$;
```

The flyway command looks something like this:
```
Flyway.configure()
      .dataSource(...)
      .baselineVersion("43")
      .ignoreMissingMigrations(true)
      .load()
      .migrate()
```

**Comment by JWGmeligMeyling** [comment]
@timt Nice approach. One question: why would `ignoreMissingMigrations` be required if you rename the migrations anyway?

**Comment by nafg** [comment]
Hmmm... What if you delete all the migrations, create a new migration as version 1, set it as the baseline version -- and then modify your configuration to use a different table (e.g. `flyway_schema_history_2`)?

In existing databases, Flyway will see that you have a non-empty schema with no (recognized) flyway table and ignore the baseline migration. In new environments it will run the baseline migration too.

Am I missing anything?

**Comment by nafg** [comment]
This seems to be working. I haven't deployed to production yet, but I've tested it against my local populated database (which has the same schema as production) as well as a local fresh database (the convenience of docker!).

The one thing to be aware of is that if, as I tried initially, your current flyway table is the older `schema_version` and you set your new flyway table to be the newer `flyway_schema_history`, it won't work, since flyway is hardcoded to check those particular names, and if it sees that's the case, it assumes that `flyway_schema_history` is set by default, not explicitly, and that the real table is the previous one. So I used `flyway_schema_history_1` instead.

Versioning the versioner...

**Comment by nafg** [comment]
@axelfontaine do you think it's a robust solution? If so you could put it in the FAQ or something and close this issue (I'll report if I find any issue.)

**Comment by mcekovic** [comment]
@nafg
It can work if you have all non-empty (say production) databases on the same version.
But if you have many production databases on different versions, it cannot work.
For general case, condensed migrations are required.

**Comment by nafg** [comment]
Hmm. What if you have two Flyway objects, one for the old migrations with the old table and `locations`, and you have a different `location` for the condensed and new migrations. This way if the database is not up to date, it will still be able to apply the remaining old migrations first.

Once all databases are past the reset, you can delete the old code of course.

**Comment by SpokeyWheeler** [comment]
+1

**Comment by boonep** [comment]
+1

**Comment by damian-t** [comment]
+1

**Comment by meambobbo** [comment]
wanted to share my migration consolidation strats for multiple spring boot services:

- baseline-version and baseline-on-migration don't do anything if there is existing flyway history - we cannot inject a migration and baseline-version past it in the environments with already built and populated schemas
- ignore-missing-migrations and ignore-ignored-migrations is needed to start up after deleting legacy migrations and adding the new consolidated migration. not a good option IMO as we lose good validation

## Configure a new flyway schema table name

When configured to use a different flyway schema table name, flyway will detect being introduced into a new environment, build the schema history table and start running all scripts beyond the baseline-version. For new environments baseline-version should not be set and use the default of 0. For existing environments, baseline-version should be set to the version of the last script that was already run in the environment per service.

- V1_1__build_schema_v2.3.sql will be the consolidated 2.3 schema build script
- V1_2__populate_schema_v2.3.sql will be used to populate system tables where applicable
- R__ migrations will continue to be used to rebuild views. all views should be represented here
- V2+ will be any scripts applied post release 2.3 - they will be shifted from their current numbers
ie, if 2.3 release's last migration was V11, then the current V12 becomes the new V2, V13 becomes V3, V14 -> V4, etc.
- `spring.flyway.baseline-version` should be set to the highest V migration number in existing codebase master branch - this number will vary for each service
- the introduction of the config change to an existing codebase should not run any V migrations in an existing environment - should have already been run and baseline past them.
- `spring.flyway.table` should be set to `flyway_schema_history_2`
- no sidecar pod is needed to delete or alter existing flyway_schema_history, nor interface directly with flyway
- existing flyway_schema_history is not deleted and exists for audit/rollback capability if needed
- configmaps/.global.env should set FLYWAY_BASELINE_VERSION to 0 for provisioning a new environment. if running on an existing local database, set version to the last run V migration. Once each service is run once and a baseline migration is created, the version will have no impact and does not have to be maintained.

**Comment by Dissem** [comment]
For me, it's absolutely fine to take care of unifying the scripts myself. What I miss though is a way to introduce the new Baseline Scripts without messing with `flyway_schema_history`.
The easiest way would be to just have a flag to just not check any scripts below the Baseline version. Ideally it would also fail if the `flyway_schema_history` didn't reach the baseline version yet.

**Comment by DoodleBobBuffPants** [comment]
We now support this with [state scripts](https://flywaydb.org/documentation/concepts/statescripts) so closing this PR

Do let us know if this works as intended :)

**Comment by mcekovic** [comment]
Please be aware that while https://github.com/flyway/flyway/pull/2509 is indeed very useful, it does not solve this issue in full.
Please see comment https://github.com/flyway/flyway/pull/2509#issuecomment-790461508

**Comment by asafm** [comment]
@DoodleBobBuffPants Don't forget to mention it's a paid-only feature

**Comment by jwgmeligmeyling** [comment]
Thats a pity, was planning to integrate this soon. Time to go back to Liquibase I suppose.

**Comment by the-serious-programmer** [comment]
@jwgmeligmeyling I think this article answers your question best, as it is also possible to do this in a non paid way (but a bit more manual): https://medium.com/att-israel/flyway-squashing-migrations-2993d75dae96

For postgres a reusable script has been created that you could execute every so many months for instance: https://github.com/the-serious-programmer/flyway-postgres-squash-script

**Comment by arenk** [comment]
> Hmm. What if you have two Flyway objects, one for the old migrations with the old table and `locations`, and you have a different `location` for the condensed and new migrations. This way if the database is not up to date, it will still be able to apply the remaining old migrations first.
> 
> Once all databases are past the reset, you can delete the old code of course.

Based on this idea, I'm currently experimenting with the following setup in a Spring Boot application:

- A "chain" represents a series of migrations, each starting with a new baseline that contains all migrations of all previous chains in a single file.
- Each chain is located in a dedicated folder (in my example `db/migration/<CHAIN>`) and has its own `flyway_schema_history_<CHAIN>` table
- The following `FlywayMigrationStrategy` checks if the database already contains a `flyway_schema_history_<CHAIN>` table for the latest chain or does not have any flyway table so far (either due to empty schema or flyway not yet introduced)
  - **Yes:** Just migrate once with the configuration of the latest chain, effectively skipping all migrations of previous chains.
  - **No:** Start with the last supported chain (all migrations must still be present in the corresponding folder) and iterate through the following chains until all migrations up to the latest chain have been applied (I skipped migrations of chains where a table for the subsequent chain already exists for efficiency reasons).
  
 If I'm not missing something, this should have a few key advantages:
- Only uses the latest chain for new databases
- Also works if existing databases are not at the same version, since all previous migrations are always applied
- Keeps a copy of previous migrations/chains in folders and tables without slowing down the migration (except for the first time after creating a new chain), e.g. for audit purposes

Note: 
- Of course you may never add a migration to a chain that is not the latest one since this approach assumes that all migrations of previous chains have been applied as soon as a new chain table is available.
- If you introduce flyway for the first time on non-empty databases they must be in the state of the first version of the latest chain
- Naming convention in the example below is `VX.Y__` where X = index of chain and Y = index of version. E.g. the baseline for the chain 2 would be V2.1


```java
import org.flywaydb.core.Flyway;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.flyway.FlywayMigrationStrategy;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import javax.sql.DataSource;
import java.sql.SQLException;

@Configuration
public class CustomFlywayMigrationStrategy {

    private static final String TABLE_BASE = "flyway_schema_history_";
    private static final String LOCATION_BASE = "db/migration/";

    private static final int LAST_SUPPORTED_CHAIN = 1; //Migration files must still be present in corresponding location
    private static final int LATEST_CHAIN = 2; //Update when starting a new chain

    @Autowired
    private DataSource dataSource;

    @Bean
    public FlywayMigrationStrategy flywayMigrationStrategy() {
        return flyway -> {
            var flywayTables = getExistingFlywayTableNames();

            //Flyway not yet introduced or table for latest chain already exists: Just run migrate() with latest chain
            if (flywayTables.isEmpty() || flywayTables.contains(TABLE_BASE + LATEST_CHAIN)) {
                flyway = configureFlywayForChain(LATEST_CHAIN);
                flyway.migrate();

            } else {
                //Run migrations of all still supported previous chains; skip if subsequent chain table does already exist
                for (var chain = LAST_SUPPORTED_CHAIN; chain <= LATEST_CHAIN; chain++) {
                    if (flywayTables.contains(TABLE_BASE + (chain + 1))) {
                        continue;
                    }
                    flyway = configureFlywayForChain(chain);
                    flyway.migrate();
                }
            }
        };
    }

    private Flyway configureFlywayForChain(int chain) {
        return Flyway.configure()
                .failOnMissingLocations(true)
                .validateMigrationNaming(true)
                .baselineOnMigrate(true)
                .baselineVersion("" + chain + ".1")
                .table(TABLE_BASE + chain)
                .locations(LOCATION_BASE + chain)
                .dataSource(dataSource)
                .load();
    }

    private Set<String> getExistingFlywayTableNames() {
        try (var connection = dataSource.getConnection()) {
            var metadata = connection.getMetaData();
            var result = metadata.getTables(null, null, TABLE_BASE + "%", new String[]{"TABLE"});

            var chains = new HashSet<String>();
            while (result.next()) {
                chains.add(result.getString(3));
            }
            return chains;

        } catch (SQLException e) {
            throw new RuntimeException("Failed get existing flyway schema history tables", e);
        }
    }
}
```

**Comment by seanf** [comment]
> We now support this with [state scripts](https://flywaydb.org/documentation/concepts/statescripts) so closing this PR
> 
> Do let us know if this works as intended :)

For anyone else finding this old discussion, apparently [state scripts](https://web.archive.org/web/20210919141624/https://flywaydb.org/documentation/concepts/statescripts) are now known as [**baseline migrations**](https://documentation.red-gate.com/flyway/flyway-concepts/migrations/baseline-migrations), and it looks like they [no longer require Flyway Teams](https://documentation.red-gate.com/flyway/learn-more-about-flyway/feature-summary).

**Comment by gregjotau** [comment]
This is still not possible to do in an easy way if you want to also delete the old migration files. Then you have to also run flyway repair as well. 

We simply want to start from scratch with a fresh sql file `pg_dump` without any fuss or change of properties, repair or whatever.
