### ISSUE TITLE
Cassandra support

### ISSUE THREAD

**Issue by andrii-rubtsov** [flyway/flyway#823]
I am new to Cassandra and looking for Flyway-like tool.

Although Cassandra is not JDBC compatible, just wondering how feasible it is to implement Flyway-like or Flyway-for-Cassandra tool? I presume that some/most of the code could be reused.

**Comment by patka** [comment]
I started to have a look on this topic by implementing a JDBC wrapper around the Datastax driver. Until now I am able to create the schema_version table. However, I already discovered the following "challenges":
* the installed_on column depends on the default value for the timestamp being provided by the DB. Currently C* does not support default values for columns and will not fill the installed_on column automatically.
* C* seems to make a difference between single quotes and double quotes. [See here] (http://www.datastax.com/documentation/cql/3.1/cql/cql_reference/escape_char_r.html) I had to introduce a new quoteStringLiteral method in DbSupport to support this.
* Currently there are no functions in C* like current_user() or current_schema() that can be used to retrieve this kind of information
* ORDER BY does not work as in SQL databases. ORDER BY in C* requires a where clause which makes Flyway fail when trying to find applied migrations.

Just wanted to share my insights so somebody else does not need to fall into the same traps again.

**Comment by axelfontaine** [comment]
@patka  Thanks for the initial investigation. None of these issues seem insurmountable, so that's good.

We can have a closer look at this once your JDBC wrapper is available publicly on Maven Central. I am sure adjusting some of Flyway's abstractions to support this should not be a problem.

Cheers
Axel

**Comment by rdawemsys** [comment]
@patka I asked on the DataStax java-driver-user mailing list recently about when the DataStax driver will have JDBC support; you can see the thread here: https://groups.google.com/a/lists.datastax.com/forum/#!msg/java-driver-user/kspAx0neZlI/8A59HmYc-rwJ

I also recently looked into adding support for Cassandra to Flyway, but using the existing cassandra-jdbc driver from https://code.google.com/a/apache-extras.org/p/cassandra-jdbc/ , just to see how far I could get. I found a few issues:

1. It's unclear how keyspace creation could be integrated into Flyway. Perhaps this is something that will always be handled outside of Flyway, so that the replication factor, etc. is set appropriately by the sysadmins.
2. Flyway relies on the JDBC driver supporting transactions. cassandra-jdbc does not support transactions, since Cassandra has no direct equivalent.
  * I wondered if we could use Cassandra BATCHes instead, but I don't know if cassandra-jdbc supports the BATCH operation.
3. Flyway is expecting to find .sql files, but Cassandra CQL is conventionally in .cql files. For the R&D I put CQL in .sql files.
4. Flyway needs to know if schemas and tables exist. The DbSupport for Postgres queries the information schema. For Cassandra, we'd need the equivalent of "DESC KEYSPACES" and "DESC TABLES" from cqlsh.
  * For the R&D, I made the Cassandra DbSupport class always return true.
  * Cassandra has some tables describing its schema in the system keyspace – the schema_keyspaces, schema_columnfamilies, and schema_columns tables. See comment on CASSANDRA-2477 in the Apache JIRA.
5. Flyway uses a "schema_version" table in the schema (keyspace in Cassandra). When it's applying an update, it tries to increase some integer fields by 1 using SQL "UPDATE ... SET x = x + 1". This syntax is supported in Cassandra for counter columns. However, for tables containing a counter column, all the other columns have to be in the primary key. Having all the non-counter columns in the PK seems like it would conflict with how the "schema_version" table is used by Flyway.
  * I did not actually check whether having all the non-counter columns in the PK would be an issue.
  * I did not investigate this any further in MetaDataTableImpl.java.
  * Perhaps Flyway needs to support farming the update out to the DbSupport layer. We could implement this increment by reading the data, and then writing it back again with x = x + 1.
6. Flyway tries to use "SELECT MAX(...)" to find the maximum installed version of a schema update. This is not valid in Cassandra.
  * For Cassandra, we'd need to implement this by reading all the rows and computing the maximum ourselves.
  * The "SELECT MAX(...)" is in the core of Flyway. We'd need to allow the DbSupport layer to customise this behaviour, to allow the Cassandra DbSupport to override this behaviour.
  * Although I have heard that Cassandra 3.0 will support aggregates, so perhaps MAX() will be supported then.

I disabled or stubbed out code to get past these, but gave up soon after.

**Comment by patka** [comment]
@rdawemsys I stumbled over your question already as the DataStax website states for a long time now that they are going to release a JDBC driver. I also saw the Cassandra-JDBC project on google code but it still uses the old thrift protocol and the project does not seem to have much activity. Therefore I tried to implement the JDBC API as a kind of wrapper around the DataStax driver.

But, I also think that there are some issues because of the feature set that Cassandra supports.

**Comment by rkuris** [comment]
Cassandra isn't a relational database, even though it supports SQL. I think most of the operations that flyway performs on a regular basis are queries that can be optimized for cassandra with a different schema.

**Comment by jiteshvassa** [comment]
@patka Just wondered if you'd had any success on this?

**Comment by patka** [comment]
@jiteshvassa Sorry. So far no, because my employer basically postponed this topic. Maybe I can pick it up one day again but currently I cannot tell if and when this will be :(

**Comment by brianwawok** [comment]
@jiteshvassa the core concept of flyway is really simple. I think I ended up writing my own flyway like schema tool for cassandra in ~40 lines of code. Sure it is missing a few features but it beats nothin!

**Comment by mictadlo** [comment]
@brianwawok: Could you share your own flyway like schema tool for cassandra?

**Comment by brianwawok** [comment]
@mictadlo I don't have it packaged up.. but I have the actual code at https://gist.github.com/brianwawok/01db9d8a1efcff5d2691

Basic idea is

1) Throw in the main code.. have your app run it at startup (in my case a play app)

2) make files current-date.cql to run schema changes.. these will run in ABC order, so use current date to sort properly.

3) Sometimes I want to do something that you cannot due in cassandra (update users set last_name = foobar) due to always needing a whereclause.. for those cases I make a FooBar1234.scala file, and then in my CQL file I do "EXEC FooBar1234" to have it go run some scala code.

Not super fancy, no rollback support.. but it sure beats no flyway at all!

**Comment by mp911de** [comment]
Any update on this issue? It would be great having a tool for Cassandra database migrations. Cassandra batches can be only used to modify data but not for altering data structures.

**Comment by patka** [comment]
Sorry for my late reply. Because of a limited amount of time at that time I ended up writing a very small Cassandra Schema migration tool. Given the limited possibilities of Cassandra compared to a relational database, this seemed to be the far more easy solution.

I put the code here on Github and I will see that I release it soon to maven central. The repository can be found [here](https://github.com/patka/cassandra-migration).

I hope it will be useful to somebody.

**Comment by paudam** [comment]
Any news regarding this?

**Comment by mkobit** [comment]
It has been a little bit of time since the last update, so just wondering if this is still on the radar and if Flyway's APIs can be adapted to work with Cassandra? What would it take to support Cassandra (for example, in https://flywaydb.org/blog/flyway-6.0.0-beta)?

**Comment by rdosifyndna** [comment]
Can you let the community know if there are any plans to provide support for Cassandra? Is there any roadmap? Alternatives to flyway have support already in place, however they lack in other features. Flyway's native support for Cassandra will be great.

**Comment by armondoortega** [comment]
Adding support for Cassandra would be a great addition

**Comment by albcm-simetrik** [comment]
Any update about this ?

**Comment by LikDan** [comment]
Hi everyone :) 
I have write a driver for Cassandra for FlyWay. 
It imitates SQLite type, basically when FlyWay trying to execute query it converts to Cassandra and executes.

[Because FlyWay promise to add Cassandra pretty soon ](https://documentation.red-gate.com/flyway/flyway-blog/flyway-v10-has-landed) I did not do it customizable and scalable. Also the code style not the best. 

Most likely it does not supports every FlyWay query. But it works out-of-box to run your migrations.
[Here is the repo.](https://github.com/LikDan/FlyWayCassandraDriver)

**Comment by alistair-RG** [comment]
https://documentation.red-gate.com/fd/cassandra-database-236454646.html

**Comment by alistair-RG** [comment]
Sorry - my mistake. It's not made it into the OSS release (yet) as it is in preview.
For the moment you can get it if you pick up the Redgate libraries instead of the open source ones

**Comment by jorges119** [comment]
@murphye Did you get the problem solved? I am still seeing _No database found to handle jdbc:cassandra://..._ error with 

```
libraryDependencies ++= Seq(
      "org.flywaydb" % "flyway-core" % "10.17.1",
      "com.ing.data" % "cassandra-jdbc-wrapper" % "4.12.0"
)
```

**Comment by alistair-RG** [comment]
The docs aren't very explicit on this - we'll how we can improve them. Thanks
