### ISSUE TITLE
Rename init to baseline to avoid confusion

### ISSUE THREAD

**Issue by flavor8** [flyway/flyway#860]
The documentation implies that your first migration can be V1. However, a migration with version 1.0.0 is not ever run; in mergeAvailableAndAppliedMigrations, the migration with version 1.0.0 is merged with the already applied init migration, and thus not picked up. Please either fix the merge logic (to never merge the init) or the documentation to be clearer about the first migration name.

**Comment by dereknheiley** [comment]
> Please help me understand the thought process so I have a better chance at making this more intuitive in the future.
>
> * renaming init to something less attractive to blindly run/more descriptive of the intention
> * change the initVersion default away from 1.0
> * prevent init from being run against a blank database

Sorry to dig up a dinosaur here @axelfontaine, but i'm having an issue with using `basselineOnMigrate` over `initOnMigrate`. I'm not sure if it's a bug long since fixed from flyway 6.4.4 (can't upgrade at this time).

Scenario; trying to perform a 'factory reset' from java spring boot on postgres 12
0. user clicks factory reset
1. java drops all tables in schema, based on list in SELECT tablename FROM pg_tables WHERE schemaname = 'myschema'
2. restart java spring boot and flyway throws

`DEBUG ..sys.PostgresDbService      [128]dropTablesAndReleaseDiskSpace() dropped 'public' 'table_1' `
`DEBUG ..sys.PostgresDbService      [128]dropTablesAndReleaseDiskSpace() dropped 'public' 'table_2'`
`DEBUG ..sys.PostgresDbService      [128]dropTablesAndReleaseDiskSpace() dropped 'public' 'table_3'`
`DEBUG ..sys.PostgresDbService      [128]dropTablesAndReleaseDiskSpace() dropped 'public' 'table_4'`
`DEBUG ..sys.PostgresDbService      [128]dropTablesAndReleaseDiskSpace() dropped 'public' 'table_5'`
`DEBUG ..sys.PostgresDbService      [128]dropTablesAndReleaseDiskSpace() dropped 'public' 'table_6'`
`DEBUG ..sys.PostgresDbService      [128]dropTablesAndReleaseDiskSpaceBeforeRestart() also dropped unknown table 'public' 'unknown_1'`
`DEBUG ..sys.PostgresDbService      [128]dropTablesAndReleaseDiskSpaceBeforeRestart() also dropped unknown table 'public' 'unknown_2'`
`DEBUG ..sys.PostgresDbService      [128]dropTablesAndReleaseDiskSpaceBeforeRestart() dropped 'public' flyway_schema_history'`
` INFO ..sys.PostgresDbService      [128]Completed dropTablesAndReleaseDiskSpaceBeforeRestart() from Postgres repos : 519.260637ms`
`//restart`
` INFO ..cor.int.lic.VersionPrinter [1]Flyway Community Edition 6.4.4 by Redgate`
` INFO ..cor.int.dat.DatabaseFactory [1]Database: jdbc:postgresql://localhost:5432/smart (PostgreSQL 12.12)`
`DEBUG ..cor.int.dat.DatabaseFactory [1]Driver  : PostgreSQL JDBC Driver 42.2.24`
`DEBUG ..cor.Flyway                 [1]Schemas: public`
`DEBUG ..cor.Flyway                 [1]Default schema: null`
`...`
` INFO ..cor.int.com.DbValidate     [1]Successfully validated 15 migrations (execution time 00:00.037s)`
`DEBUG ..cor.Flyway                 [1]Memory usage: 71 of 358M`
`...`
`ERROR org.flywaydb.core.api.FlywayException: Found non-empty schema(s) "public" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.`

3. use intOnMigrate=true and Flyway creates version table without creating baseline migration as i'm expecting, and my first v1 migration runs normally (i could rename it to v1.1 i suppose).

In this case, i think the `FlywayException: Found non-empty schema(s) "public" but no schema history table` might be a bug caused by `spring.flyway.schemas=${my.app.postgres.schema}` being specified, because if i comment out that option, i do not get any error on the same schema (here i'm testing with `my.app.postgres.schema=public` for simplicity). The advantage of `initOnMigrate` i'm seeing is that it correctly warns me if the DB schema isn't empty - which i want, but otherwise creates the missing version table for me after i've dropped all my old tables

If i were to use `baselineOnMigrate` instead, it plows into the schema and assumes existing tables are fine - i don't want this to always be the assumption just to support a "factory reset". I want to configure with an application property and only enable 'baselineOnMigrate' when absolutely required (this would prevent dropping unknown tables as well - which is why i don't just drop the schema).

For example with
`spring.flyway.initOnMigrate=true`
`spring.flyway.baselineOnMigrate=${my.app.postgres.allowAndIgnoreExisingTables}`

**Comment by dereknheiley** [comment]
Nevermind, initOnMigrate didn't fix anything, manually dropping and recreating the DB gave me a false sense of hope that it did. My underlying problem seemed to be manually deleting tables along with the flyway version table resulting flyway throwing the above error because of something else in the schema related to flyway not being in an expected state. 

Solution was;
- drop the entire schema (which was complicated for me)
- use flyway clean (which didn't work so great on timescale MATERIALIZED views)
- manually delete my tables with cascade, and then call flyway clean to handle it's internal state and worked as expected when app was restarted and flyway found a scheme without tables matching it's migrations
