### ISSUE TITLE
Batch updates for SQL statements

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#94]
_Original author: kaczanow...@gmail.com (June 06, 2012 07:34:06)_

As discussed on http://stackoverflow.com/questions/10899727/executing-more-than-one-statement-at-once it would be nice to have an option of &quot;batch updates&quot;.

In short, current implementation sends statements to DB one by one which results in very slow updates (in case of large files and net lag).

Some DB vendors (e.g. PostgreSQL) support such thing natively.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=274_

**Comment by ZitZ** [comment]
Is this a definite as far as not going to implement?

It would be very useful for my workflow as it depends on callbacks which bootstrap and configure the database. These statements are written in an idempotent manner. I have had to do workarounds to get these idempotent statements to work through flyway, because the statements are not executed in a batch manner.

**Comment by axelfontaine** [comment]
@ZitZ This has been implemented and is available today as part of Flyway Pro and Enterprise Edition.
